### PR TITLE
move some threadData vars to global ones

### PR DESCRIPTION
**Pull request by adrpo**
this will fix some issues for Windows:
- symboltable (OMEdit crash on startup)
- codegen function list (FMU generation from OMEdit)

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-31_16-03-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5177/).

**Comment by hkiel** [comment]
Could this bug be seen in OMNotebook in v1.12 as well?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-01-31_16-20-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5178/console).

**Comment by adrpo** [comment]
@hkiel: this should fix all the QT clients on Windows for now, we will need to look into more details later why threadData local roots gets corrupted.

**Comment by adrpo** [comment]
@hkiel: no version previous to 1.13 are affected, these were some recent changes from @sjoelund that changed how the SymbolTable is handled.

**Comment by sjoelund** [comment]
Moving data to global data might break some clients because now you can't have two different symbol tables. Having them local is done for a very good reason...

**Comment by adrpo** [comment]
@sjoelund: true, but there is something fishy with threadData->localRoots. They are not added as GC roots in Windows it seems and they are collected! 

Using `export GC_DONT_GC=true` OMEdit doesn't crash anymore. 

I even tried adding `GC_add_roots(&threadData->localRoots[0], &threadData->localRoots[MAX_LOCAL_ROOTS])` and it still doesn't help.

No idea what's going on here.

**Comment by sjoelund** [comment]
@niklwors I suppose this affects you as well. Windows bugs relating to the garbage collection when trying to interface directly to OMC. You have had some similar weird bugs.

**Pull request closed without merging**
