### PR TITLE
added an extends VerificationModel

### PR DESCRIPTION
**Pull request by lenaRB**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-11-02_21-53-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4861/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-02_23-18-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4862/console).

**Comment by sjoelund** [comment]
Was this meant to be merged into master? If so, the PUSH checkbox should be enabled when running the Hudson job.

**Comment by lochel** [comment]
@lenaRB Should this be merged or closed?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-06_05-32-34](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5210/console).

**Pull request closed without merging**
