### PR TITLE
NFInst builtin function handling.

### PR DESCRIPTION
**Pull request by mahge**
- Most builtin functions are now handled.
   - A new builtin file NFFrontEnd/NFModelicaBuiltin.mo is used by the nwe instantiation now.
   - Builtin functions are handled by a combination of
      - gnenric functions
      - overloading
      - and special intenral handling when needed.

   - Error messages need to be improved in a number of places.
   - There are some builting functions which will pass when not suppsoed to. The will be fixed.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-11-28_13-52-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4990/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by sjoelund** [comment]
NFModelicaBuiltin.mo is not encoded as UTF-8

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-11-28_13-59-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4991/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-11-28_14-08-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4993/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-28_15-52-41](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4994/console).

**Comment by casella** [comment]
I just started a run of OpenModelica_TEST_LIBS_NEWINST/OpenModelica_TEST_LIBS_RIPPER to see what we get after this commit. I expect interesting results 😅

**Comment by casella** [comment]
@mahge it seems that your commit made things worse, see https://libraries.openmodelica.org/branches/history/newInst/2017-11-27%2021:02:22..2017-11-28%2016:35:47.html

**Comment by mahge** [comment]
@casella Yes I have noticed that :). I think most of the failures might be because we change arguments a bit in the new front end. And the back-end ended up getting things it didn't expect. 
For example I handle fill(s,a,b,c,...) as fill(s, {a,b,c...}) to make it a "valid" Modelica call.
I will try to locate them and fix them before passing to BackEnd. If that seems like too much work then we can fall back and manually deal with fill(s,a,b,..) and similar calls.

**Comment by casella** [comment]
OK, good luck 😃

**Pull request closed without merging**
