### PR TITLE
Changes to ModelicaBuiltin

### PR DESCRIPTION
**Pull request by sjoelund**
- Added type inference for Modelica builtin operators.
  When using annotation __OpenModelica_UnboxArguments=true, the result
  is an expression that is not boxed.
- Made the following functions not use the elabBuiltinHandler
  - delay (with a fix in ExpressionSimplify for 2->3 args)
  - diagonal
  - previous
  - subSample
  - superSample

### CODE REVIEW

**Comment by sjoelund** [comment]
@bernhard-thiele @adrpo: See https://github.com/OpenModelica/OMCompiler/pull/1428/files#diff-e1f289b95a2ab6168d3e9bd2936551b4 for the changes to ModelicaBuiltin.mo. I didn't do all functions because I want to see the test suite pass first.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-01-27_14-07-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3812/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-01-27_14-24-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3813/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-01-27_14-29-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3814/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-27_14-35-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3815/).

**Comment by sjoelund** [comment]
The `diagonal` change doesn't work for InvertedPendulumTotal. There are some superfluous error-messages for `delay`. Should be possible to fix (re-add the old `diagonal` handler or fix the dimensions on the slots), and fixing error-messages for overloaded functions should be possible as well.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-02_14-41-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3849/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-09_09-22-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3876/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-02-09_09-51-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3877/console).

**Pull request closed without merging**
