### PR TITLE
remove tuple decompostion-recomposition

### PR DESCRIPTION
**Pull request by hkiel**
Fix the following code pattern to save memory
```
(a,b,c) := tpl;
(a,b,c) := funcWithTupleParam( (a,b,c) );
tpl := (a,b,c);
```

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-31_16-10-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2148/console).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler e0b38d17e50af0e3017270b455e0d847a23a2a54 3da291da91fba4b17a8782f6a66cfb9c01eb971e

**Comment by lochel** [comment]
Thanks for this. It seems that some of the patterns can be further cleaned up, because there is no need for having the tuples in them anymore.

**Comment by hkiel** [comment]
@lochel From a quick look only BackendDAEOptimize.copyNonParamVariables can be further reduced. Shall I commit?

**Comment by lochel** [comment]
@hkiel Oops! Sorry, I've looked at an old version. Never mind.

**Pull request merged**
