### PR TITLE
[NF] Constant evaluate fixed attributes

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by lochel** [comment]
@perost, I am not sure if this is really how/where it should be implemented. Can you please have a quick look before I continue?

**Comment by lochel** [comment]
This depends on #1527 for expression simplification.

**Comment by perost** [comment]
>@perost, I am not sure if this is really how/where it should be implemented. Can you please have a quick look before I continue?
Sorry, I seem to have missed the notification somehow.

Anyhow, for the constant evaluation to work correctly the expressions needs to be typed (to e.g. handle array dimensions). So the call to evalBinding should be moved to below the call to typeBinding, and evalBinding should be changed to work with typed bindings.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-17_12-36-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4046/console).

**Pull request closed without merging**
