### PR TITLE
Match more nonlinear equations first while tearing

### PR DESCRIPTION
**Pull request by ptaeuber**
Until now possible equations for the tarjan matching while tearing are chosen sequentially. These changes choose the most nonlinear equations first to receive preferably linear residual equations.

See also comments on [PR1668](https://github.com/OpenModelica/OMCompiler/pull/1668).

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-06-12_14-32-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4306/console).

**Comment by casella** [comment]
Having residual equations which are linear in the  torn variables is not necessarily good, if the dependencies of those torn variables from the tearing variables (specified in the torn equations) are strongly nonlinear.

**Comment by ptaeuber** [comment]
Sure, you will never get a linear system from a nonlinear one. Even if the residual equations are linear in the torn variables and the torn variables occur linear in all the other equations, the nonlinearity goes down in the residual equations.

Nevertheless, I think it is better to have some heuristics than doing the matching randomly. At least it makes tearing a bit more deterministic regarding model changes.

**Comment by casella** [comment]
I agree with that

**Pull request closed without merging**
