### PR TITLE
Append in the fast order

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-12-09_15-35-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1323/).

**Comment by lochel** [comment]
Why should it be faster with this calls of `listReverse`?

**Comment by sjoelund** [comment]
Old code did `listAppend(inIndices, indices);`, which appends in the wrong order. sum(1+2+...+n) is O(n^2)

**Comment by casella** [comment]
As young Gauss discovered some time ago :)

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-12-09_19-50-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1332/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-12-09_20-41-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1333/console).

**Pull request closed without merging**
