### PR TITLE
ticket:4237 fix partition index in jacobians

### PR DESCRIPTION
**Pull request by wibraun**
- change default partition index of Jacobians => 0
- fixed a small cpp codegen issue

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_10-47-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3833/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_11-24-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3835/console).

**Comment by lochel** [comment]
Initialization of nonlinear systems fail for certain models, e.g. MixingUnit (clockedAlgloopTest):
```
assert            | debug   | residual function pointer is invalid
```

**Comment by wibraun** [comment]
@lochel But has nothing to do with the jacobians. We need to generate the nonlinearSystemData for synchronous stuff.

**Comment by lochel** [comment]
> We need to generate the nonlinearSystemData for synchronous stuff.

Sure, just do it.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_13-33-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3838/console).

**Pull request closed without merging**
