### PR TITLE
reduce memory usage

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-08_14-56-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2296/).

**Comment by hkiel** [comment]
please run again

**Comment by adrpo** [comment]
Running now.

**Comment by adrpo** [comment]
I will start it again after the CLANG build and test jobs are done. I put the wrong PR number :)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-08_16-46-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2301/).

**Comment by hkiel** [comment]
Found and fixed the last bug. Now the remaining tests also work here.
Please run again.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-09_08-46-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2308/console).

**Pull request closed without merging**
