### PR TITLE
GC.free() some temporary arrays

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by sjoelund** [comment]
I'm starting a job without push to see if performance improves.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-27_14-22-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2968/console).

**Comment by hkiel** [comment]
would be good to see if ScalableTestSuite runs more efficiently (less out-of-memory or faster execution)
From benchmarking ScalableTestSuite.Electrical.DistributionSystemDC.ScaledExperiments.DistributionSystemModelica_N_20_M_20 here it does give an improvement

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-27_15-27-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2969/console).

**Pull request closed without merging**
