### PR TITLE
Fix zero crossings for div calls

### PR DESCRIPTION
**Pull request by lochel**
see [ticket:4419](https://trac.openmodelica.org/OpenModelica/ticket/4419)

### CODE REVIEW

**Comment by hkiel** [comment]
looks like the same bug-source as my fix to the C-macros...

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-05-12_13-53-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4273/console).

**Comment by hkiel** [comment]
@sjoelund Can you add this to v1.9 and v1.11 branches?

**Comment by lochel** [comment]
@hkiel, @sjoelund I can do that.

**Pull request closed without merging**
