### PR TITLE
optimize memory further for ticket:1451

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-14_00-06-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4738/console).

**Comment by hkiel** [comment]
@sjoelund  @casella Shall this PR and #1900 go into 1.12? I do not see any other impact than reducing memory overhead.

**Comment by sjoelund** [comment]
For most models it is a quite minor memory overhead. I would say it's not needed in 1.12. Should be mainly bugs fixing crashes, not performance going into 1.12 at this stage.

**Comment by casella** [comment]
Let's play safe and keep it for 1.13.0. I'm pushing for better scalability, but that's a medium-long term feature, it's not at all urgent. Currently few people are pushing the tool to these limits, and if they do, they can (and should) use the nightly builds

**Comment by casella** [comment]
I'm not sure this helped, see [ticket:1451:comment:6](https://trac.openmodelica.org/OpenModelica/ticket/1451#comment:6)

**Pull request closed without merging**
