### PR TITLE
Run without OPENMODELICAHOME on Windows

### PR DESCRIPTION
**Pull request by sjoelund**
Use GetModuleFileName on Windows if the environment variable is not
defined. This is similar to Linux and OSX, where the pidpath and
/proc/self are used to find out where OpenModelica was installed.

If OPENMODELICAHOME is set, the same behaviour as before applies.

### CODE REVIEW

**Comment by sjoelund** [comment]
@adrpo: Can you check if the PR works on Windows; if it compiles at all or if there are more changes needed?

**Comment by adrpo** [comment]
@sjoelund: Just commit it and I'll fix it if it has issues.

**Comment by sjoelund** [comment]
No, you need to test it because the testsuite, etc sets OPENMODELICAHOME. And everyone has OPENMODELICAHOME set. So you will not see the functionality unless you try it out explicitly.

**Comment by adrpo** [comment]
I know. I have to see how to checkout a pull request as I have no idea.
That's why I said you can commit it and I can check it when is pushed in.

**Comment by sjoelund** [comment]
```sh
git remote add sjoelund https://github.com/sjoelund/OMCompiler
git fetch sjoelund
git checkout sjoelund/windows-no-envvar-needed
```
or:
```
git fetch origin pull/214/head:windows-no-envvar-needed
```
(can also put any branch name you want to check oput the reference as)

**Comment by sjoelund** [comment]
Any news?

**Comment by adrpo** [comment]
I had no time to look into this. I hope I'll have time to look at it on Friday.

**Comment by sjoelund** [comment]
I tested the above on wine, and it works. So I will run Hudson on these. (OPENMODELICAHOME will be optional also on Windows, and not necessary to set in the installer)

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-16_11-52-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1179/console).

**Pull request closed without merging**
