### PR TITLE
[NF] Ceval for builtin functions and other fixes.

### PR DESCRIPTION
**Pull request by perost**
- Implemented constant evaluation of many builtin functions.
- Always evaluate bindings of non-package constants.
- Show fewer but better errors when type matching function calls.
- Fix NFExpression.fold so it actually recurses all the way down.
- Various other fixes for builtin functions.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-12-19_17-34-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5049/console).

**Comment by adrpo** [comment]
@perost: have you forgot to check PUSH in the Hudson job?

**Comment by casella** [comment]
I guess so, the Hudson job reports no changes since 19 dec 10:07

**Comment by perost** [comment]
@adrpo Yes, it seems I did.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-12-20_12-11-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5050/console).

**Comment by casella** [comment]
I just started the [Hudson job](https://test.openmodelica.org/hudson/job/OpenModelica_TEST_LIBS_RIPPER/360/)

**Comment by casella** [comment]
The [results](https://libraries.openmodelica.org/branches/history/newInst/2017-12-19%2021:02:22..2017-12-20%2013:38:01.html) are not very encouraging: 48 improvements vs. 501 regressions

**Comment by perost** [comment]
@casella Should be fixed in about 2 minutes.

**Comment by casella** [comment]
In most cases the problem is 
Error: Internal error NFCeval.evalNormalCall: IMPLEMENT ME
but we also get 
Error: Internal error NFCeval.evalBuiltinCall: unimplemented case for Modelica.Math.asin

**Comment by perost** [comment]
@casella Yes, those are already fixed (just need another go at Hudson, had to update some tests). Or at least the second one is fixed, the first one was "fixed" by allowing evaluation of constant bindings to fail for now until we implement a more complete ceval (with function interpretation and so on).

**Comment by casella** [comment]
OK, I'll keep an eye on #2088 and restart the Hudson job when it's done.

**Comment by casella** [comment]
It seems that we are now more or less back to square one.

I don't understand why [this huge regression](https://libraries.openmodelica.org/branches/history/newInst/2017-12-20%2013:38:01..2017-12-20%2015:07:20.html) is blamed on @ptaeuber 's PR, but as it is restored by your later PR it may be the report is incorrect?

**Comment by perost** [comment]
@casella Yeah, it seems like the reporting of some of the regressions were delayed for some reason. But my fix fixed the regressions from both reports. So in the end this PR improved about 60 models, but I didn't really expect it to make a huge impact since most models are affected by one or more of the other common issues anyway (I'm currently working on the array issue with builtin type attributes that looks like the most common cause of failure right now).

**Comment by casella** [comment]
OK, very good 👍

**Pull request closed without merging**
