### PR TITLE
Add newline after annotation in AST dump - list()

### PR DESCRIPTION
**Pull request by sjoelund**
This newline is so OMEdit gets code folding by default. Each top-
level modification in the annotation gets its own line.

Also now handles newline in annotation String literals better (by not
converting Text to string in Susan, which messes with indentation).

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-12-14_11-50-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3560/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-12-14_13-38-26](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3561/console).

**Comment by sjoelund** [comment]
@adrpo @adeas31 - should this go into 1.11.0? It's a rather minor change, but looks nicer in OMEdit

**Comment by casella** [comment]
Please do. More nice-looking code produced with OMEdit that will stick around for some time.

**Pull request closed without merging**
