### PR TITLE
improved guess for non-linear system

### PR DESCRIPTION
**Pull request by wibraun**
### Improved basis for extrapolation 
* use a value list **in each** non-linear system to guess next solution instead of the ringbuffer old values
* the value list allows now also to interpolate some solutions 

### TODO:
* see impact on coverage test
* clean runtime for old approach

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-10-24_14-45-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1026/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-10-24_15-04-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1027/console).

**Comment by casella** [comment]
I'm eager to see the impact on ThermoPower_Experimental with the next nightly build :)

**Comment by wibraun** [comment]
Unfortunately, it seems there is currently no impact on ThermoPower_Experimental, but there is an impact on some MSL.Fluid examples. But I now working on a context dependent (ode vs. jacobian) extrapolation, I confident that this will have a bigger impact.

**Pull request merged**
