### PR TITLE
Allow inheritance when bootstrapping

### PR DESCRIPTION
**Pull request by sjoelund**
This fixes some issues in #3573, by making it possible to extend and
redeclare elements in different files also in the bootstrapped
compiler. The base package needs to be marked as such since the
definitions are part of the interface.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-11-26_16-16-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1259/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-11-26_16-45-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1262/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-11-26_17-06-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1264/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-11-27_16-26-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1272/console).

**Comment by sjoelund** [comment]
Do we have a ulimit for the compilation time? Seems doing instantiation of every model is very expensive. Maybe I should only do it for classes that actually do use extends clauses.
On Nov 27, 2015 16:31, OpenModelica Hudson <notifications@github.com> wrote:The job failed to compile; for details, see OpenModelica_TEST_PULL_REQUEST 2015-11-27_16-26-21.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-30_09-05-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1273/console).

**Comment by sjoelund** [comment]
This is now fast enough, when only doing instantiation when necessary (possibly breaks under some circumstances with weird inheritance structures).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-30_09-19-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1274/console).

**Pull request merged**
