### PR TITLE
ticket:3488

### PR DESCRIPTION
**Pull request by adeas31**
Read the __OpenModelica_commandLineOptions annotation and apply it.

### CODE REVIEW

**Comment by adeas31** [comment]
The only problem with the above code is that the flags sets via `__OpenModelica_commandLineOptions` are saved permanently. So we need something like,

- `getCommandLineOptions` to get the existing flags
- Apply the new flags retrieved from `__OpenModelica_commandLineOptions`
- Reset to the old flags.

@perost can you write `getCommandLineOptions`?

**Comment by sjoelund** [comment]
What's wrong with `Flags.saveFlags` followed by `Flags.loadFlags`? You just need to consider all execution paths (probably with a try-block) to avoid accidentally keeping the new flags.

**Comment by adeas31** [comment]
Yeah I expected that to work and tried it the other way around but it doesn't work,

```
flags = Flags.loadFlags();
read/apply new flags and do translations
Flags.saveFlags(flags);
```

What do you mean by execution paths?

**Comment by sjoelund** [comment]
Execution paths = control flow
```mo
try
  Flags.saveFlags();
  // apply new flags
  // do the stuff you wanted to do
  Flags.loadFlags(); // Resets to the original flags
else
  Flags.loadFlags(); // Handle a failed "stuff you wanted to do"; the reset is now always performed
  fail();
end try;
```

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-12_12-55-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2659/console).

**Pull request closed without merging**
