### PR TITLE
Redo of #1252 that was closed but not merged but Hudson after successful test

### PR DESCRIPTION
**Pull request by rfranke**

### CODE REVIEW

**Comment by sjoelund** [comment]
e02bbf266fa03066f7c00ae53f7fff7f8618bafb and ad7adca9d98ab3fc1f2e86b48f0efb9e23762f4a seem to have been rebased just fine.

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 42ed0f6165df5e2ba0d436385047954c24058c19 d9f30dc8be1f0ef69d551994b17e5afeecf6fb0d

**Comment by rfranke** [comment]
I think that #1252 had been taken over yesterday. Today it is unmerged again?! Redo fails. What is wrong???

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-27_17-34-26](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3468/console).

**Comment by sjoelund** [comment]
It's not unmerged. It is there. It was just rebased instead of merged. Just as usual.

**Comment by sjoelund** [comment]
See https://github.com/OpenModelica/OMCompiler/compare/407fc9c9b84c634d418022ad36e083f1285c0a6b...ce441e184cccd9914a6d517f188e1ed17ced8b57

The only thing added is some garbage commits to git, and an empty merge commit. No actual file changes.

**Comment by rfranke** [comment]
My fault. Sorry.

**Pull request closed without merging**
