### PR TITLE
Support vectorized flow connectors

### PR DESCRIPTION
**Pull request by rfranke**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-11-06_21-50-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6182/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-11-06_22-30-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6185/console).

**Comment by adrpo** [comment]
@rfranke very strange error you're getting:

```
clang -O2 -march=native -fno-stack-protector -fPIC  -Wno-parentheses-equality -Wno-unused-variable -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -I/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/build/include/omc/c -I../Util/  -DADD_METARECORD_DEFINITIONS=  -c -o build/InstStateMachineUtil.o build/InstStateMachineUtil.c
/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/Compiler/FrontEnd/InstStateMachineUtil.mo:841:31: error: expected expression
  create_index_spec(&tmp4, 0, );
                              ^
1 error generated.
<builtin>: recipe for target 'build/InstStateMachineUtil.o' failed
make[5]: *** [build/InstStateMachineUtil.o] Error 1
make[5]: Leaving directory '/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/Compiler/boot'
make[5]: *** Waiting for unfinished jobs....
```

**Comment by adrpo** [comment]
You shouldn't get such C code from MetaModelica, only from Modelica with array slice indexes.
What is even stranger is that you haven't touched that file.

**Comment by adrpo** [comment]
In my compiler I get this code for `incidence := fill(false,n,n);` in `InstStateMachineUtil.mo:841`:
```
#line 841 "C:/home/adrpo33/dev/OpenModelica/OMCompiler/Compiler/FrontEnd/InstStateMachineUtil.mo"
  tmp2 = 0;
#line 841 "C:/home/adrpo33/dev/OpenModelica/OMCompiler/Compiler/FrontEnd/InstStateMachineUtil.mo"
  fill_alloc_boolean_array(&tmp3, tmp2, 2, (modelica_integer)_n, (modelica_integer)_n);
#line 841 "C:/home/adrpo33/dev/OpenModelica/OMCompiler/Compiler/FrontEnd/InstStateMachineUtil.mo"
  copy_boolean_array_data(tmp3, &_incidence);
```
In your PR some bad code is generated using `create_index_spec`.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-11-06_22-57-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6186/console).

**Comment by adrpo** [comment]
The problem is in your changes to `SimCodeFunctionUtil.crefSubIsScalar`:
https://github.com/OpenModelica/OMCompiler/pull/2768/files#diff-09259109af7756dbab462753cb372f0bR83
In the case of `incidence = fill(false, n, n)` you get `listLength(subs) = 0` and `listLength(dims) = 2` and instead of returning true you return false.

**Comment by rfranke** [comment]
OK, I interpreted the function `crefSubIsScalar` wrong. I thought it should determine if a cref refers to a scalar. This applies to  scalars and to array crefs with a scalar subscript for each dimension that are reduced to a scalar in this case. This is why I added a check for the number of dimensions.

It seems the function I'm looking for is `ComponentRef.crefHasScalarSubscripts`.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-11-07_11-46-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6187/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-11-07_13-37-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6189/console).

**Pull request closed without merging**
