### PR TITLE
Use Autoconf.mo instead of external C functions

### PR DESCRIPTION
**Pull request by sjoelund**
This starts using Autoconf.mo for constants such as the dll extension.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-03-29_10-36-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6569/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-03-29_11-17-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6570/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-03-29_11-49-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6571/console).

**Comment by adrpo** [comment]
Why is this even working? In windows it does not work properly. We build the bootstrapped compiler out of the tar.gz C files and they expect the Compiler/runtime library to contain the functions that are called from System.c

**Comment by adrpo** [comment]
So in windows the build just dies with:
```
make -f Makefile.omdev.mingw Makefile.sources
make[6]: Entering directory '/c/home/adrpo33/dev/OpenModelica/OMCompiler/Compiler/boot'
/c/home/adrpo33/dev/OpenModelica/build/bin/omc.exe -g=MetaModelica -n=1 MakeSources.mos
We could not find any of:
        C:/home/adrpo33/dev/OpenModelica/build/MinGW/bin and C:/home/adrpo33/dev/OpenModelica/build/MinGW/libexec/gcc/mingw32/4.4.0
        $OMDEV/tools/MinGW/bin and $OMDEV/tools/MinGW/libexec/gcc/mingw32/4.4.0
Error processing file: MakeSources.mos
[C:\home\adrpo33\dev\OpenModelica\OMCompiler\Compiler\boot\MakeSources.mos:1:1-1:36:writable] Error: Class runScript not found in scope <global scope> (looking for a function or record).
[C:\home\adrpo33\dev\OpenModelica\OMCompiler\Compiler\boot\MakeSources.mos:2:1-2:15:writable] Error: Class mkdir not found in scope <global scope> (looking for a function or record).
[C:\home\adrpo33\dev\OpenModelica\OMCompiler\Compiler\boot\MakeSources.mos:3:1-3:19:writable] Error: Class cd not found in scope <global scope> (looking for a function or record).

# Error encountered! Exiting...
# Please check the error message and the flags.

```

**Comment by adrpo** [comment]
I cannot even debug this properly as we only have C files, not .mo files they were created from.

**Comment by adrpo** [comment]
Nevermind, I found the problem, #3020 should fix it.

**Comment by hkiel** [comment]
@adrpo Now OSX fails:
```
gmake[5]: Entering directory '/Users/om/src/OpenModelica/OMCompiler/Compiler/boot'
/Users/om/src/OpenModelica/build/bin/omc -g=MetaModelica -n=1 build/UnitChecker.stamp.mo.mos
We could not find any of:
	/Users/om/src/OpenModelica/build/MinGW/bin and /Users/om/src/OpenModelica/build/MinGW/libexec/gcc/mingw32/4.4.0
	$OMDEV/tools/MinGW/bin and $OMDEV/tools/MinGW/libexec/gcc/mingw32/4.4.0
```

**Comment by hkiel** [comment]
@sjoelund Also the Mac nightly build shows the above error/warning:
https://test.openmodelica.org/hudson/view/Nightly%20builds/job/OpenModelica_OSX_NIGHTLY_BUILD/lastBuild/consoleFull

**Pull request closed without merging**
