### PR TITLE
reduce implicit inlining

### PR DESCRIPTION
**Pull request by vruge**

### CODE REVIEW

**Comment by lochel** [comment]
@vruge What do you mean by implicit inlining and to what kind of functions does it apply?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-25_15-55-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2068/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-25_16-25-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2069/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-25_17-00-03](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2070/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-25_17-22-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2071/console).

**Pull request merged**
