### PR TITLE
ticket:4159 fix some flag descriptions

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-30_12-44-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3486/console).

**Comment by sjoelund** [comment]
Will you also fix the flags in the 1.11 maintenance release?

**Comment by casella** [comment]
Please do! :)

**Comment by wibraun** [comment]
Done.

**Pull request closed without merging**
