### PR TITLE
Improve performace of extractVarFromVar

### PR DESCRIPTION
**Pull request by wibraun**
try to fix [#3685](https://trac.openmodelica.org/OpenModelica/ticket/3685).

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 092e0f5e260e9f75897476f4aad373ad93608066 0278ca8e3353667d659ae7e40c5f04f084be7d12

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 092e0f5e260e9f75897476f4aad373ad93608066 93b1247783751488f4d15a70eb4026717b4b53b1

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-29_14-16-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1746/console).

**Comment by casella** [comment]
Compare [the new results](https://test.openmodelica.org/libraries/history/ScalableTestSuite_Experimental-2016-03-01.html) with [the old ones](https://test.openmodelica.org/libraries/history/ScalableTestSuite_Experimental-2016-02-24.html), in particular the StringModelica_N_XX models. N = 2 and N = 4 show a significant improvement, up to a factor 2. However, for larger ones the performance is still the same. I guess you have fixed a part of the code that scales badly, but there are still other one(s) that don't scale correctly, and they dominate the execution time from a certain size up.

Is it possible to have more fine-grained profiling to find out which parts of the MetaModelica code take the lion's share of the CPU time? I guess that would be very helpful...

**Comment by sjoelund** [comment]
Just run valgrind on the code. It's only a 100-time slowdown :) Or perhaps use operf.

**Comment by casella** [comment]
If the run time is 10 seconds, I guess Willi can afford a 100x slowdown.

**Comment by wibraun** [comment]
I'm quite confident that creating all SimVars is dominating the execution time in the SimCode phase, at least in all models I have tested. 
This job is done by the function extractVarFromVar, which basically creates a SimVar from a BackendVar and select the correct list for the corresponding variable. Anyway, here I've just tried to optimize this act, I guess we need here a better approach for handling of a lot long lists.

**Comment by casella** [comment]
But why creating two times as many variables should take 3.5 times more time? There really must be something fundamentally wrong in how these data structures are managed.

**Comment by wibraun** [comment]
Okay, I was wrong it's the function preCalculateStartValues, which takes so long.

**Comment by hkiel** [comment]
Valgrind exposes a huge amount of work in GC (at least here on my OSX machine).
I saw about 1/3rd of the time spent in GC, not the model.
Also -d=gcProfiling shows that 16GB or RAM were allocated (and "freed") during a simple simulation run.
I propose investigation of the use of #481 to get better results.
I suspect listAppend() is one of the big culprits.

**Comment by sjoelund** [comment]
```mo
rest := listAppend(rest,newEqIdcs); // Appending to the end of the list is slow :(
```

See #481 for an explanation of why

**Comment by sjoelund** [comment]
Actually, it seems the result of that iteration is not even used. So it can probably be removed (and it scales O(n^2))...

**Comment by sjoelund** [comment]
Never mind, it's used for some weird iteration building a list... Really odd case.

**Pull request closed without merging**
