### PR TITLE
fix attribute name for causality

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by adeas31** [comment]
It is wrong for FMI 1.0. In FMI 1.0 `parameter` is `variability` and in FMI 2.0 it is `causality`. I think you need to handle it by checking the version.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-08-03_11-57-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/471/).

**Comment by wibraun** [comment]
Ah, okay.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-08-03_14-00-31](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/478/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-08-03_14-49-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/481/console).

**Pull request closed without merging**
