### PR TITLE
Synchronous improvements

### PR DESCRIPTION
**Pull request by gossen**
Add partial synchronous support to SimCode and C code generator (no clocked continuous systems).

### CODE REVIEW

**Comment by lochel** [comment]
Can you please resolve the conflicts?

**Comment by gossen** [comment]
Resolved

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-28_11-42-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/445/).

**Comment by gossen** [comment]
What's wrong with test ComplexFun.mos?

**Comment by sjoelund** [comment]
Internal errors with line numbers from within the compiler. The test needs to be updated in order to pass.

**Comment by gossen** [comment]
Should these failed sub-tests be placed in failing tests section?

**Comment by sjoelund** [comment]
No. They should be baselined using rtest -b.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-28_19-27-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/450/console).

**Pull request closed without merging**
