### PR TITLE
New package AdjacencyMatrix

### PR DESCRIPTION
**Pull request by lochel**
This introduces a new package containing all the functions to create and process the biadjacency matrices.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-04-07_13-36-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4166/console).

**Comment by sjoelund** [comment]
This PR was not merged. Forgot to press PUSH and just forgot about the PR?

**Comment by lochel** [comment]
This is just not finished yet. It has low priority and for now I am too busy with other things.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-11_16-47-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4706/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-11_18-40-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4711/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-12_09-01-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4718/console).

**Pull request closed without merging**
