### PR TITLE
fix ticket:3897

### PR DESCRIPTION
**Pull request by hkiel**
- run install_name_tool on the libraries

### CODE REVIEW

**Comment by adrpo** [comment]
Isn't this already fixed by @sjoelund in: https://github.com/OpenModelica/OMCompiler/pull/846?

**Comment by hkiel** [comment]
I guess it is something different since this patch works on libSimulationRuntimeC.dylib and libOpenModelicaFMIRuntimeC.dylib, but I don't know exactly...

**Comment by adrpo** [comment]
@hkiel: ok, i'll start a PR job and we'll see how OSX likes it :)

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-17_10-43-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2683/console).

**Comment by hkiel** [comment]
@adrpo @sjoelund  the change should show an effect on OSX nightly build. But the hudson mac slave seems to have some processes running wild, since compilation takes much longer than some time ago.

**Comment by adrpo** [comment]
It seems it doesn't help:
https://test.openmodelica.org/hudson/job/OpenModelica_OSX_TEST/lastCompletedBuild/testReport/

**Comment by adrpo** [comment]
OSX is a pain :)

**Comment by adrpo** [comment]
OSX nightly builds got stuck in some sort of infinite loop but I think @sjoelund fixed it.

**Comment by hkiel** [comment]
ah, that's because of #844 
we need to fix for "*_idas" instead of "*_ida" now...

**Comment by hkiel** [comment]
Can I push to this branch again once it is merged???

**Comment by adrpo** [comment]
I don't know, @sjoelund, any idea?

**Comment by sjoelund** [comment]
Yes, but you need to create a new PR for github; it won't reopen the PR.

**Pull request closed without merging**
