### PR TITLE
fix BackendDAETransform.eqnAssignmentNonScalar()

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by hkiel** [comment]
was broken in commit d8ea3a02

**Comment by hkiel** [comment]
@sjoelund please start hudson

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_17-36-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2770/console).

**Comment by hkiel** [comment]
@sjoelund I wonder why this bug has no impact. AFAICS the function is used...

**Pull request closed without merging**
