### PR TITLE
Do not generate #define for variables

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-23_10-27-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2731/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-23_10-48-29](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2732/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 8d8058049155d496187d659d66eac3eb0c38b48f 3307029f3be49a885203c17fa7d5dd4413116db1

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-23_21-32-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2745/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_09-51-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2748/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_10-29-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2750/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_11-13-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2752/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler d409c4c1b00f9c61d5dd07e6b975ba39270721bd 848b00463426792f97c7076e6366eeaa8f6ea811

**Comment by OpenModelica-Hudson** [comment]
Rebase failed (please rebase your commit in the PR and try again). If rebase is not desired for some reason, select merge in the job options.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_13-29-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2760/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_16-09-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2764/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_17-18-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2768/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_19-17-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2772/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-24_20-32-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2773/).

**Comment by OpenModelica-Hudson** [comment]
Rebase failed (please rebase your commit in the PR and try again). If rebase is not desired for some reason, select merge in the job options.

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler b977085494c219ba9d20fb4c0ea8357360c62dcb 06d2ef523935830b406309090071db2026f57199

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-25_10-01-18](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2784/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 753077979f813274d5128267cfbe7c17f6794ea3 07eddaaf914368da7d50ddaac9b8c1fec8330d21

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-25_13-28-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2797/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-25_14-58-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2799/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-25_16-38-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2805/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 6fe2a2e9daffa6161fc1f8e00b05a2aa40bee0e4 619396aba07eb2f587fda31d69651e2b79c7eee6

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-25_17-46-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2807/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_08-01-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2811/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_09-39-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2812/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_10-15-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2813/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_10-54-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2814/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_11-27-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2816/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_12-40-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2821/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_13-15-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2822/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_13-41-31](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2823/console).

**Comment by jhag** [comment]
@sjoelund Hi, the model `/simulation/modelica/synchronous/synch.mos` has problems with `--postOptModules+=wrapFunctionCalls` . The crefs are not replaced in `Modelica_Synchronous.Examples.Systems.ControlledMixingUnit_15syn.c`. Maybe you can have a look?

**Comment by sjoelund** [comment]
If the crefs are not replaced it is because they were not put into the hashtable with the correct index (as cppruntime required). I can have a quick look, but I guess you need to fix something for wrapFunctionCalls/SimCode yourself.

**Comment by sjoelund** [comment]
Do you have some example where CSE is working and you geneate cse-variables in the source code?

**Comment by jhag** [comment]
https://github.com/OpenModelica/OpenModelica-testsuite/blob/master/simulation/modelica/commonSubExp/wrapFunctionCalls1.mos

**Comment by sjoelund** [comment]
The main difference between these two files is that in `wrapFunctionCalls1.mos` (which works), the `$cse1` is a part of the `_init.xml` file. In the synchronous example, it is missing from the xml-file (and the hashtable).

**Comment by lochel** [comment]
`$cse2` ends up in the `_init.xml` file, so it seems that clocked partitions are handled different to continuous time partitions.

**Comment by lochel** [comment]
I guess this could explain the issue:  [SimCodeUtil.mo#L6869](https://github.com/OpenModelica/OMCompiler/blob/master/Compiler/SimCode/SimCodeUtil.mo#L6869)

**Comment by ptaeuber** [comment]
@sjoelund This commit still breaks models. In SiemensPower (the confidential one) a model which was simulating fine fails because of this error kind:
error: <variable> undeclared (first use in this function) 
In _06inz.c and _08bnd.c.

**Comment by lochel** [comment]
@ptaeuber - What kind of variables causes the issue? Parameter? Inputs? Aliases? Are they also part of the simulation system?

**Comment by ptaeuber** [comment]
@sjoelund @lochel They are matrix elements PARAM(final = true ). Should they appear there at all?

**Comment by ptaeuber** [comment]
I created a [ticket](https://trac.openmodelica.org/OpenModelica/ticket/3967#ticket) with a minimal model.

**Pull request merged**
