### PR TITLE
New implementation of module wrapFunctionCalls

### PR DESCRIPTION
**Pull request by lochel**
* handles nested function calls
* doesn't introduce unnecessary cse variables

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-06-10_11-42-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2910/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-06-10_11-58-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2911/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-10_12-28-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2912/console).

**Comment by casella** [comment]
@lochel, do you think this commit will have a significant impact on compilation and simulation time?

**Comment by lochel** [comment]
@casella - This pull request doesn’t enable the module by default, so there shouldn’t be a big impact. However, it is already applied to improve Jacobian evaluations. So maybe there will be some impact.

This pull request fixes a bunch of issues with the old approach, especially with nested functions and functions returning multiple outputs. So in fact, more function calls should get substituted and thus it should have a positive impact on the simulation time for certain models.

The algorithm is designed to scale linearly with respect to the number of equations. So I expect that it will perform better than the previous implementation. However, this is not yet tested very well.

If you want to test the implementation: It can be used for the pre-optimization phase (`--preOptModules+=wrapFunctionCalls`), as well as for the post-optimization phase (`--postOptModules+=wrapFunctionCalls`).

**Pull request merged**
