### PR TITLE
Add support for a Mutable data structure

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-04-29_10-31-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4240/console).

**Comment by sjoelund** [comment]
@perost @adrpo - seems this requires a new bootstrapping tarball in order to be used in the frontend... Tell me if you think it's worth it. Mutable data would consume 32 bytes instead of 16 bytes for the `array<T>` used before. I can think of some ways of reducing it using external "C" tricks (storing it as `SOME(x)` instead of a uniontype; making the uniontype empty, etc). One advantage of this way is the ability to use the debugger without any changes. (Also, it was possible to use it in constants in NFBuiltin stuff like it was before; even though that should not have worked; changing to a uniontype without a record in it would make it impossible to create any such constants, but would save memory)

**Comment by sjoelund** [comment]
Never mind the needs bootstrapping tarball. Seems that's just a problem with dot notation in the tarball. Seems to work fine accessing using match.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-05-02_14-33-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4242/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-05-02_15-05-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4243/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-05-02_18-00-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4244/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-05-02_18-25-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4245/console).

**Pull request closed without merging**
