### PR TITLE
added scaling for f(u) in kinsol, based on jacobian

### PR DESCRIPTION
**Pull request by wibraun**
- add more debug info from kinsol if LOG_NLS_V is enabled
- start printVector with 1

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-04-11_00-35-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4187/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-04-13_11-16-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4197/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-04-19_14-29-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4215/console).

**Comment by casella** [comment]
@wibraun have you tried this on the tests of [#4359](https://trac.openmodelica.org/OpenModelica/ticket/4395)? Can you please report the results on that ticket?
Thanks!

**Comment by casella** [comment]
I have made some tests but they are not satisfactory at all. I'll report on [#4359](https://trac.openmodelica.org/OpenModelica/ticket/4395)

**Pull request closed without merging**
