### PR TITLE
Fix initialization of variable attributes

### PR DESCRIPTION
**Pull request by lochel**
see [ticket:4359](https://trac.openmodelica.org/OpenModelica/ticket/4359)

---

**TODO**
- [x] Fix code generation for c runtime
- [x] Fix code generation for cpp runtime
- [x] Fix openmodelica/fmi/ModelExchange/1.0/JuliansBib.mos
- [x] Fix openmodelica/xml/Bug3857.mos
- [x] Do some more testing

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-23_16-04-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4080/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-24_10-53-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4084/).

**Comment by lochel** [comment]
@niklwors @vwaurich This changes the representation of start values. Right now, we have a function call to access a start value, i.e. `$_start(var)`. In order to enable assignments to start values, I’ve introduced additionally a cref representation for this (`$START.var`). Please, can one of the cpp runtime developers show how to implement it in the code generation? I guess `template contextCref` is the place to do it.

**Comment by niklwors** [comment]
@lochel we have similar functions in our SystemDefaultImpl class, getRealStartValue, getIntStartValue, getBoolStartValue which returning the start value for a variable. In the template function daeExpCallStart this functions are used.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_10-38-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4085/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_19-30-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4086/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_20-40-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4087/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-25_21-24-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4088/).

**Comment by vwaurich** [comment]
@lochel Shouldn't it be sufficient to put check if init equations are only dependent on parameters and put them into the parameterEquations which are evaluated before initEquations?

**Comment by lochel** [comment]
@vwaurich The issue here is that the start values have to be calculated during the actual initialization phase because they depend on unfixed parameters.

**Comment by vwaurich** [comment]
The continuous variables can stay in the init system. Currently, unfixed parameter assignments occure in SimCode.initialEquations as well. They could be assigned beforehand. I thought we can put them in SimCode.parameterEquations.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-27_15-32-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4096/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-28_14-37-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4101/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-28_15-52-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4103/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-28_16-26-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4105/console).

**Comment by wibraun** [comment]
@lochel I assumed this PR fixes ticket:4359, but it does not. Can you elaborate a bit want you have done here?

**Comment by lochel** [comment]
No, this PR wasn’t intended to finally fix [ticket:4359](https://trac.openmodelica.org/OpenModelica/ticket/4359). It should just have fixed the initialization of start attributes. There is more to come.

**Pull request closed without merging**
