### PR TITLE
[FE] new API and replaceable support

### PR DESCRIPTION
**Pull request by adrpo**
- to use, just add +d=nfAPI to the OMEdit simulation flags
- handling of getComponentAnnotations via NF (some models are about 6x faster)
- some crashes in OMEdit, not debugged yet, for example: Modelica.Fluid.Examples.AST_BatchPlant.BatchPlant_StandardWater

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2019-05-14_02-05-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6758/console).

**Comment by sjoelund** [comment]
The bootstrapping does not depend on the NF files, so those are not included when compiling it (need refactoring and/or stubs).

**Comment by adrpo** [comment]
Yeah, I got that. I will see what I can do. I'll be back if I have issues.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-05-14_09-09-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6760/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-05-14_09-39-49](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6761/console).

**Comment by casella** [comment]
To use it, you should actually set `-d=newInst,nfAPI`

**Pull request closed without merging**
