### PR TITLE
Fix scaling issues for initialization

### PR DESCRIPTION
**Pull request by sjoelund**
Iterate over the smaller set of variables.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-12-09_15-59-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1324/).

**Comment by lochel** [comment]
That's not working, since the element indices based on `inEqSystem.orderedVars` is relevant.

**Comment by sjoelund** [comment]
Then it should be sorted in some other way afterwards, because this is causing an O(N^2) scaling for an algorithm that should be O(N) -- it's really slow in the larger models.

**Comment by lochel** [comment]
That should be possible, but not using `BackendVariable.getVarIndexFromVariables`.

**Comment by lochel** [comment]
I can do that with another pull request. Or are you going to fix it?

**Comment by sjoelund** [comment]
I might fix it tomorrow if I have time to spare.

**Comment by sjoelund** [comment]
I am now running the tests using the above approach.

**Comment by lochel** [comment]
Good - that should work.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-12-10_10-34-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1339/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-12-10_10-48-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1340/console).

**Comment by lochel** [comment]
How big is the impact of this improvement?

**Comment by sjoelund** [comment]
I will know in about an hour :)

**Comment by sjoelund** [comment]
Before: Performance of analyzeInitialSystem (initialization): time 1831
Now: Performance of analyzeInitialSystem (initialization): time 485

**Comment by sjoelund** [comment]
Of the remaining time, most of it is not relating to this fix, but rather the sorting+matching/etc of the largest system of equations in the initialization problem:

Performance of fixInitialSystem (initialization 2) [nEqns: 49146, nAddEqs: 4608, nAddVars: 0]: time 433.4
(Which is just the last part of one of the >20000 iterations)

So I am now sure this part of the code now scales O(N) instead of O(N^2).

**Comment by lochel** [comment]
Well, the example seems to be under-determined. Therefore, it will not scale {{{O(N)}}}. First, I think, we should focus on well-determined models.

**Comment by casella** [comment]
This has been solved thanks to Volker's analysis. Some parameters eventually multiplying derivatives were accidentally set to zero, and evaluateParameters removed some derivatives, so that there were a few more initial equations than states. After correcting this, the initial system became square and the time for analyzeInitialSystem dropped from 335 to 40 seconds, without using the latest commits of this branch, due to problems with nightly builds. We expect further improvements with the latest nightly, thanks to Martin's contribution.

**Comment by casella** [comment]
Martin's improvements slashed the execution time of analyzeInitialSystem by 50% to 20 seconds. Excellent job!

**Pull request closed without merging**
