### PR TITLE
fix copy&paste error

### PR DESCRIPTION
**Pull request by hkiel**
Fix typo from #2841

### CODE REVIEW

**Comment by hkiel** [comment]
@adrpo @sjoelund Please confirm and merge this fix (also to v1.13 branch)

**Comment by adrpo** [comment]
Thanks for noticing this.
I'm not sure I want to port this to 1.13.0. I will think about it.

**Comment by hkiel** [comment]
That was just in case you want to add your patch to 1.13.
I just started hudson job for this PR.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-12-20_14-12-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6296/console).

**Pull request closed without merging**
