### PR TITLE
[BE] Several improvments for diff module

### PR DESCRIPTION
**Pull request by wibraun**
- improve debugging
 - added size and range operator
 - fix transpose rule
 - added case for tuple statements with a CALL on the RHS
 - improved error handling in creating partial derivative by adding fallback case to use total derivative.
 - finally it fixes [ticket:3266](https://trac.openmodelica.org/OpenModelica/ticket/3266).

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-15_08-08-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5267/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-02-15_17-14-03](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5276/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-02-15_17-30-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5277/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-02-16_12-01-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5292/).

**Comment by wibraun** [comment]
@sjoelund The test OutOfMemory.mos seems to have a non deterministic behaviour or was this just bad luck.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-16_12-45-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5293/console).

**Comment by sjoelund** [comment]
@wibraun It seems none of your runs failed on the out of memory test. It should work just fine with make clean. If it doesn't there is some GC_malloc call that is unchecked that I need to fix (a backtrace would help).

**Comment by wibraun** [comment]
hm, I mean this one: [HudsonRun](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5292/).
In the next try the test passes, but I haven't changed anything, just start hudson once again. Before I was testing a bit on my machine and there the backtrace stack, was in all runs slightly different.

**Comment by sjoelund** [comment]
Yes, the backtrace printed in Error.mo will always be different since it's expected to crash in different places. But it's not supposed to segmentation fault. I would like a stacktrace of that :D

**Pull request closed without merging**
