### PR TITLE
Generating modelica output in the flat DAE dump

### PR DESCRIPTION
**Pull request by fbergero**
This is a fix for bug 2588.

Now when the -m flag is set, valid modelica code is generated when dumping the DAE.
With this fix I tried to cover the language structures that I know of that generate invalid modelica code:
* The dot operator on variable names is replaced by underscores
* The expansion of array into many variables with the same name are now dumped as different variables a_1, a_2 a_3. The same for multidimensional arrays.
* Adrian Pop pointed me that empty arrays constructors {} are also invalid so they are replaced by fill(0,0). Perhaps some more more work is needed here to correctly type the fill call.

Does any body knows some more language structs that would generate invalid modelica code in the DAE dump??

### CODE REVIEW

**Comment by perost** [comment]
>Does any body knows some more language structs that would generate invalid modelica code in the DAE dump??

There's a couple of things that comes to mind, for example this model:
```Modelica
package P
  record R
    Real r;
  end R;

  function f
    input R ri;
    output R ro = ri;
  end f;

  type E = enumeration(one, two, three);

  model M
    R r;
    R r2 = f(r);
    E e;
  end M;
end P;
```
gives this output when flattening P.M:
```Modelica
function P.R "Automatically generated record constructor for P.R"  // Qualified name.
  input Real r;
  output R res;  // R not defined, different to P.R used elsewhere in the flat model.
end P.R;

function P.f
  input P.R ri;  // P.R defined as function above, no record defined anywhere.
  output P.R ro = ri;
end P.f;

class P.M  // Qualified name, maybe this commit fixes this?
  Real r.r;
  Real r2.r;
  enumeration(one, two, three) e;  // Not valid type.
equation
  r2 = P.f(r);
end P.M;
```

**Comment by fbergero** [comment]
I see another problem, The `R` type is not dumped at all (used in `output R res`)

Anyway  what would be the right way to dump ` enumeration(one, two, three) e;` ? 
`
    type Tmp_Type = enumeration(one, two, three);
    Tmp_Type e;
`
generating a new type name for each variable?

**Comment by sjoelund** [comment]
You cannot dump `{}` as `fill(0,0)` - you need to check the type of the array and fill with an empty element based on its type: `"", 0, 0.0, false, Enum.First, Record(A,B,C)`, etc.

**Comment by fbergero** [comment]
Yes. I wrote that before. How should I generate an element based on the `Type ty` found in the `ARRAY` record?

**Comment by sjoelund** [comment]
You have the DAR.ARRAY().ty and can use that to create a zero element. Maybe by enhancing Expression.makeConstZero.

**Comment by adrpo** [comment]
You will need to re-run the pull request and also give the git hash a8f64e0cd22985a19e945e49632af5d417eaec81 besides the PR number 303.

**Comment by fbergero** [comment]
Does it have to be the complete hash? I used a8f64e0 and it failed.
https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/1239/console

**Comment by sjoelund** [comment]
Yes, it has to be the full hash

**Comment by fbergero** [comment]
Great. Tests running.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-24_19-49-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1243/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-11-25_14-21-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1254/console).

**Comment by fbergero** [comment]
This should close bug #2588. How should I proceed to close it?

**Comment by adrpo** [comment]
Just go into Trac search for #2588, click Modify Ticket and say is fixed :)
https://trac.openmodelica.org/OpenModelica/ticket/2588
You can give a link to the commit using a comment [changeset:GIT_HASH/OMCompiler]

**Comment by fbergero** [comment]
Thanks Adrian. Anyway, the commits is not merged yet, is this done automatically?
Sorry for all the questions!

**Comment by adrpo** [comment]
The commits are merged, see that the PRs are closed, this and also the testsuite ones.

**Comment by fbergero** [comment]
Great. Thx

**Pull request closed without merging**
