### PR TITLE
fixed PR 1148

### PR DESCRIPTION
**Pull request by vruge**
added losing case (_,_, ..., xi ,_,_) = f(.)[i]

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-10-22_11-59-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3260/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-22_12-02-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3261/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-22_12-53-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3262/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-22_20-26-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3263/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-23_15-00-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3264/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-23_21-34-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3265/).

**Comment by lochel** [comment]
As I said already a while ago, I think we should remove the entire module and just handle complex equations properly.

@vruge What did you change with #1148? Is there new functionality?

**Comment by vruge** [comment]
what do you mean by "properly"??

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-23_22-47-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3266/).

**Comment by lochel** [comment]
> what do you mean by "properly"??

The module `simplifyComplexFunction` is a workaround for wrongly handled or just unhandled cases that are related to complex equations.

@vruge What did you change with #1148? Is there new functionality?

Please add always a brief description to your pull requests that explain why you changed something and which new functionality is introduced.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-23_23-17-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3267/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-23_23-44-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3268/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-24_00-15-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3269/console).

**Comment by vruge** [comment]
> The module simplifyComplexFunction is a workaround for wrongly handled or just unhandled cases that are related to complex equations.
So simplifyComplexFunction solve some issues! Ok, I knownd it!
But there no answer of your "properly"!

**Comment by lochel** [comment]
The PNlib is still broken and I cannot see any good reason for keeping #1148 and #1152. @vruge please provide some information about your changes.

It would probably be the best to develop your changes on a branch and push them once they are working. @sjoelund @adrpo Should we revert the changes for now?

**Pull request closed without merging**
