### PR TITLE
Use a FIFO instead of slow listAppend

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
This might fix some performance issues discussed in #473. @wibraun @lochel @vwaurich make sure you understand the code :)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-01_16-11-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1760/).

**Comment by sjoelund** [comment]
Small error: `not listEmpty(rest) and not listEmpty(workList)` should be `not listEmpty(rest) or not listEmpty(workList)`

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-01_16-32-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1761/console).

**Pull request closed without merging**
