### PR TITLE
remove some matchcontinue

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-02-27_13-48-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1718/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by sjoelund** [comment]
OMCompiler/Compiler/FrontEnd/ExpressionSimplify.mo 1
make: *** [trailing-whitespace-error] Error 1

**Comment by hkiel** [comment]
ouch! How did that come in?

**Comment by hkiel** [comment]
@sjoelund Can you please start hudson again?

**Comment by lochel** [comment]
@hkiel can you please squash your commits?

**Comment by hkiel** [comment]
I succeeded in squashing and publishing that, but only with deleting the original branch -> new #468

**Comment by sjoelund** [comment]
Squashing the branch commands:
```bash
git fetch origin
git rebase -i origin/master # Mark commits for fixup / squash
git push -f # Since rebasing/squashing changes history
```
That means no new PR is needed :)

**Comment by hkiel** [comment]
I did it in this order, but I could not push (but did not use -f yet)

**Pull request closed without merging**
