### PR TITLE
Adds serialization functions for MetaModelica values

### PR DESCRIPTION
**Pull request by modlfo**
Adds package Serializer that contains functions to serialize values to files.

### CODE REVIEW

**Comment by sjoelund** [comment]
Awww... C++ code for hash maps? I try to use C hashes, but oh well. I will start hudson.

**Comment by modlfo** [comment]
I tried to stay with C++. This can be later changed if is problematic.

**Comment by sjoelund** [comment]
Sure. We might need to remove all C++ code at some point if we have trouble linking OMEdit due to different c++ features/flags. GCC 5.1 seems to have these [problems](https://test.openmodelica.org/hudson/view/Linux/job/OpenModelica_TEST_GCC_5.1/16/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-05-29_15-38-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/56/console)

**Pull request closed without merging**
