### PR TITLE
Extract variables from clocked partitions

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by lochel** [comment]
This is about to fix the issue that is mentioned in #871. @bernhard-thiele @rfranke does one of you know why clocked partitions are skipped there?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-14_16-05-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2920/console).

**Comment by lochel** [comment]
I am going to merge this, because it has no impact on the test suite.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-16_10-39-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2925/console).

**Pull request merged**
