### PR TITLE
fix for ticket:4109

### PR DESCRIPTION
**Pull request by wibraun**
- add xml root element for logFormat=xml

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-27_11-28-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3317/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-27_11-59-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3318/console).

**Comment by wibraun** [comment]
@sjoelund @adrpo The second run was working without any changes to the previous one, so we have some random testsuite behaviour ;(

**Comment by lochel** [comment]
Yes, that's totally annoying. We have this strange behavior for quite some time. Also the coverage test fails for individually models from time to time.

**Comment by adrpo** [comment]
I think is time for valgrind on these models, @wibraun can you do some testing?

**Comment by wibraun** [comment]
@adrpo okay, I'll start some tests.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-27_14-10-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3320/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 42e6eb7d929e4fb70da080208684f9513c7da943 b26188c656d93796d7ac4aa082163cdfc3c85c5d

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-27_14-29-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3322/console).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 42e6eb7d929e4fb70da080208684f9513c7da943 e6e61cb39277087611464a1d1961f3505a81934a

**Pull request closed without merging**
