### PR TITLE
Dynamic Tearing Full Prototype

### PR DESCRIPTION
**Pull request by ptaeuber**
- Dynamic Tearing also for
    - linear solver LAPACK (default) and umfpack
    - nonlinear solver homotopy (mixed)
- added flags and dumps

### CODE REVIEW

**Comment by lochel** [comment]
How did you produce duplicated commits, i.e., c73ddf2 and 0fabaa8?

**Comment by sjoelund** [comment]
Usually bad merging. Should probably be rebased by @ptaeuber to remove all the merges and empty commits that should appear

**Comment by lochel** [comment]
I see! Your history is multi-branched for some reason. Maybe that could be cleaned up a bit to keep things straight.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-11_13-44-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1872/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler dca967c81cfa372c0c5b35d2ce00ee37eb587fc4 24a34b779ba2c3be86711389ef32bf18abb71875

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-11_14-35-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1874/console).

**Pull request closed without merging**
