### PR TITLE
 Do not evaluate the residuals if xloc is inf or NaN

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
@wibraun Is it reasonable to avoid calculating residuals if the NLS makes guesses that values can be Inf or NaN?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-10-13_14-07-49](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4730/).

**Comment by wibraun** [comment]
@sjoelund Yes, actually it is reasonable, but we have to ensure the solver is capable to handle such case. The former default solver hybrid was able to recover from inf/nan values, but actually I'm not sure how our newton would behave. Do you have an example for this case?

**Comment by sjoelund** [comment]
I believe it was these models failing due to nominal=0 being the FMU default: https://libraries.openmodelica.org/branches/history/v1.12/2017-10-14%2000:04:00..2017-10-14%2011:17:47.html

Fixing that removes the errors. Otherwise you get a whole bunch of spam due to division involving inf/NaN being sent by the non-linear solver (and I guess they got inf/NaN due to nominal being 0 and having a division by zero in the NLS somewhere).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-03_11-03-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5062/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-03_13-06-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5063/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-01-03_13-26-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5064/console).

**Pull request closed without merging**
