### PR TITLE
Fix initial size of HashSet

### PR DESCRIPTION
**Pull request by hkiel**
reduces execution time of inlineWhenForInitialization from O(n^3) to O(n^2) (see ScalableTestSuite)
also change some matchcontinue to match

### CODE REVIEW

**Comment by hkiel** [comment]
@casella "inlineWhenForInitialization (initialization)" now scales like O(n^2) in ScalableTestSuite.Electrical.BreakerCircuits.ScaledExperiments.BreakerNetworkDelayed

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-05-04_15-48-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4249/console).

**Comment by casella** [comment]
@hkiel Thank you! I've just triggered a new run of the Hudson job to double check

**Comment by casella** [comment]
@hkiel are you sure about the new scaling? I checked the[ last hudson report](https://test.openmodelica.org/libraries/ScalableTestSuite_Experimental/BuildModelRecursive.html) and I got O(N^2.5). (0.4 s for N=320, 2.4 s for N=640, 12.2 s for N=1280)

**Comment by hkiel** [comment]
seems to be machine dependent. Maybe due to amount of RAM available? I only run one job, whereas hudson does many in parallel?

**Pull request closed without merging**
