### PR TITLE
Do not reset matching on no change

### PR DESCRIPTION
**Pull request by sjoelund**
For wrapFunctionCall, do not reset the matching unless the module
actually added an equation or variable.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-29_08-42-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2112/).

**Comment by lochel** [comment]
@jhag FYI

**Comment by sjoelund** [comment]
So it did manage to change something :D

**Comment by lochel** [comment]
I've triggered a Hudson push job.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-31_10-08-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2144/console).

**Pull request closed without merging**
