### PR TITLE
Use nominal value to define threshold for param division

### PR DESCRIPTION
**Pull request by ptaeuber**
see [ticket:4360](https://trac.openmodelica.org/OpenModelica/ticket/4360)

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-29_17-00-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4115/).

**Comment by ptaeuber** [comment]
Seems that division by zero always leads to a double free or corruption crash with the default linear solver

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-29_17-30-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4116/console).

**Comment by casella** [comment]
@ptaeuber mind adding a quick comment to [ticket:4360](https://trac.openmodelica.org/OpenModelica/ticket/4360) about this commit?
Thanks!

**Pull request closed without merging**
