### PR TITLE
added -nlsMaxDensity and -nlsMinSize simulation flags

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-18_20-17-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3704/).

**Comment by casella** [comment]
For simmetry with `-lssMaxDensity` and `-lssMinSize` (the double s meaning Sparse Solver), may I suggest to use `-nlssMaxDensity` and `-nlssMinSize` as flags

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-18_23-43-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3708/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-19_00-06-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3709/console).

**Comment by casella** [comment]
Folks,
if I try this
```
loadString("
model M
  Real x,y;
equation
  x*y = 10;
  sqrt(x+1) + y = 6;
end M;
");getErrorString();

simulate(M, simflags="-nlssMinSize=1");
```
I get

`warning | unrecognized option -nls=1`

I guess there's still something wrong here. Can you please fix it ASAP?

**Comment by lochel** [comment]
@casella This issue is that the runtime now detects `nls`, because it is a substring of `nlssMinSize`. I will fix that.

**Comment by lochel** [comment]
@wibraun This kind of errors could be easily caught beforehand if there were any tests in the test suite. 😉

**Pull request closed without merging**
