### PR TITLE
Cref metamodelica

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by lochel** [comment]
Will this fix the issues that I mentioned in #101?

**Comment by sjoelund** [comment]
Some of them. Except it seems to have crashed asap :)

**Comment by sjoelund** [comment]
Types like the following is the problem:
```modelica
uniontype AvlTree "The binary tree data structure
 "
  record AVLTREENODE
    Option<AvlTreeValue> value "Value" ;
    Integer height "heigth of tree, used for balancing";
    Option<AvlTree> left "left subtree" ;
    Option<AvlTree> right "right subtree" ;
  end AVLTREENODE;

end AvlTree;
```

I need to have the T_METARECORD as a part of the T_METAUNIONTYPE. But it would be a potentially infinite type... AVLTREENODE.left.left.left. Perhaps it can be solved with some smart caching, only fetching the T_METARECORD on demand.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-05_22-23-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/319/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-06_07-51-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/320/).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-07-06_09-09-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/321/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-07-06_10-01-18](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/322/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-06_10-32-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/324/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-06_10-47-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/325/console).

**Comment by lochel** [comment]
Singleton uniontypes are now supported much better. Great!

**Comment by sjoelund** [comment]
If you want to know how to delay a computation using a closure and compute it only once, see:
https://github.com/OpenModelica/OMCompiler/commit/cf5792fd524259afa39378c9fe9228ee6a90de15#diff-62472e2f742f0a60fb11e386240687cbR300

**Pull request closed without merging**
