### PR TITLE
Fix bottleneck for create model info

### PR DESCRIPTION
**Pull request by sjoelund**
This is related to ticket:3813. Uses an array of SimVar instead of
pushing everything into a large uniontype record for every change
to a simvar. The array is indexed by an enumeration, which maintains
some knowledge of which field a particular index belongs to. The
enumeration has elements ordered in FMI order since it is important
these indexes appear in a certain order.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-07_16-17-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2283/console).

**Comment by hkiel** [comment]
I you compare times in the TEST_PULL_REQUEST logs from previous (2282) to this version (2283), then you'll see that things got slower. Any idea why?

**Comment by wibraun** [comment]
wow, this looks quite pretty.

**Comment by sjoelund** [comment]
I'm not sure why it did not get faster. Maybe I sorted one array too many in some place. It should be (a lot) faster, and models from @casella did consume less memory as well. But it only really scales better for larger models. And performance of the test suite between 2282 and 2283 actually did get faster (within the margin of error). I compare the total wall-time taken for the runtests.pl command. I guess you looked at the total aggregate time for all (serial tests), which increased (but those times are summed up from integer seconds for tests, so they are inaccurate).

**Comment by sjoelund** [comment]
@wibraun Yes, we should use enumerations more often. It's a bit bad we can't index MetaModelica arrays with enumerations directly though (and Modelica-style arrays do not give good enough performance).

**Comment by casella** [comment]
The impact on the RETE_D model was dramatic: from 147.3 s down to 32.3. I wonder if there is some more room for improvement

**Pull request merged**
