### PR TITLE
Singleton uniontype

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-03_13-33-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/302/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-03_13-51-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/303/).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2015-07-03_15-40-34](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/305/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-03_15-44-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/306/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-03_16-09-29](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/308/console).

**Comment by sjoelund** [comment]
@gossen @lochel see d4cb637f3d0e8680ad4a80ac1bbb21778a508756 for example of what you can now do for refactoring (in the backend only).

**Comment by lochel** [comment]
thanks

**Comment by gossen** [comment]
Cool!

**Comment by lochel** [comment]
It seems not be possible to access a singleton unitiontype within a singleton uniontype (e.g., inDAE.shared.removedEqs). Maybe you could make that working as well.

**Comment by lochel** [comment]
It is also not possible to access an element of an array that is attribute of a singleton uniontype via bracket syntax (e.g., inEquationArray.equOptArr[inPos]).

**Comment by lochel** [comment]
It seems also to be a problem to elaborate such an expression inside a for loop range (e.g., "for i in 1:removedEqs.numberOfElement Loop").

**Comment by sjoelund** [comment]
98ca067f8e626b50f1e3e684406cc4d59081a8d4 fixes the for-loop ranges.

**Comment by sjoelund** [comment]
Things like inEquationArray.equOptArr[inPos] and inDAE.shared.removedEqs should now work as *rhs* expressions. For *lhs* expressions, use arrayUpdate for arrays.

**Pull request closed without merging**
