### PR TITLE
Allow fmi2SetInteger in continuous-time mode

### PR DESCRIPTION
**Pull request by lochel**
see [ticket:4192](https://trac.openmodelica.org/OpenModelica/ticket/4192)

### CODE REVIEW

**Comment by adeas31** [comment]
`fmi2SetInteger` shouldn't be allowed in continuous-time mode. See FMI specification page 85.

**Comment by lochel** [comment]
It should be allowed to call `fmi2SetInteger` between two `fmi2DoStep` calls for co-simulation right? Therefore, it is necessary to allow that call in continuous-time mode for co-simulation. I will check how I can check more accurately if it is allowed to call `fmi2SetInteger`.

**Comment by sjoelund** [comment]
How to check it: Implement the state machine defined in the FMI specification. It's not very many states...

**Comment by lochel** [comment]
> How to check it: Implement the state machine defined in the FMI specification. It's not very many states...

I think there is already something like that implemented. But the current implementation does only consider the calling sequence of model exchange c functions and not the calling sequence of co-simulation c functions. I will investigate this a bit more.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-06-09_11-33-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4304/console).

**Comment by adeas31** [comment]
This is not the fixed that we discussed, right?
It will now violates the model exchange fmus. We could check for fmu type and have different state checks based on it.

**Comment by lochel** [comment]
Sure, we have to do that. But it seems that no one is working on the FMU export and we pretend to support ME and CS. This is now a blocker for CS for half a year!

**Comment by lochel** [comment]
Now, I've improved the changes according to our discussion: #1674

**Pull request closed without merging**
