### PR TITLE
Detect tuples used as expressions

### PR DESCRIPTION
**Pull request by sjoelund**
Tuples may only be used on the left side of an assignment in Modelica.
In MetaModelica, we allow tuples anywhere.

### CODE REVIEW

**Comment by sjoelund** [comment]
Needs an accompanying test case. And probably breaks the test suite because we call elabExp from too many places.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-09-05_16-15-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3120/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-09-07_09-01-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3121/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-09-07_09-46-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3122/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-09-07_10-38-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3123/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-09-07_10-59-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3125/console).

**Pull request closed without merging**
