### PR TITLE
improved flags for symbolic jacobians

### PR DESCRIPTION
**Pull request by wibraun**
- adjusted description test
 - added flag "NLSanalyticJacobianDisable"

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-12_19-59-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1576/console).

**Comment by sjoelund** [comment]
Why name a debug flag NLSanalyticJacobianDisable? Why not NLSanalyticJacobian with a default of true so you can use -d=-NLSanalyticJacobian or -d=noNLSanalyticJacobian? -d=noNLSanalyticJacobianDisable is a bit awkward.

**Comment by casella** [comment]
I'm also a bit confused. What is the relationship with the existing NLSAnalyticJacobian? Has that been removed?

**Comment by wibraun** [comment]
Actually I have upgraded the flag "NLSanalyticJacobian" to a flag that force more "NLSanalyticJacobian" calculations and I wanted to have an other one to be able to disable it completely. So I result into NLSanalyticJacobianDisable, but true, that perhaps really a bit confusing.

Now, I would downgrade NLSanalyticJacobian again, and change NLSanalyticJacobianDisable to forceNLSanalyticJacobian to be able to activate analyticJacobian for more cases.

**Pull request closed without merging**
