### PR TITLE
Unit checking crashes because of the hash tables

### PR DESCRIPTION
**Pull request by lochel**
In some cases, the unit checking crashes. This is probably due to side-effects in the hash tables that are used.

### CODE REVIEW

**Comment by sjoelund** [comment]
Could HashTableStringToUnit be removed as well?

**Comment by lochel** [comment]
Sure, but I want to take one step after another ;)

**Comment by lochel** [comment]
We have also to do the same changes to the ported NF implementation...

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-10-18_14-51-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4778/).

**Comment by lochel** [comment]
For some weird reason, this changes the result of the unit checking in some cases.

**Pull request closed without merging**
