### PR TITLE
add sparse nonlinear solver support via kinsol

### PR DESCRIPTION
**Pull request by wibraun**
- enabled sparsity pattern generation for algebraic loops
-  enabled kinsol/klu support

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-11-24_14-22-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3448/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-11-24_14-28-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3449/).

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-11-24_15-19-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3450/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-24_15-28-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3452/console).

**Comment by casella** [comment]
@wibraun great news!
Are you going to push this in 1.11 or do you want to wait for the next one?

**Comment by wibraun** [comment]
@casella Actually, I wanted to wait for the release fork, what was planed for today, but now it's moved to Monday, so probably I can push it. But I'll have to check once again for side effects to the ordinary run.

**Comment by casella** [comment]
@wibraun: 1.11 has been branched, so you can proceed with the pull request

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-29_15-57-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3477/console).

**Pull request closed without merging**
