### PR TITLE
PDEModelica

### PR DESCRIPTION
**Pull request by jansilar**

### CODE REVIEW

**Comment by jansilar** [comment]
Please review especialy the first commit which is probably mostly influencing the rest of code.

**Comment by jansilar** [comment]
I mean commit 56dcf10a4875cee5ad7e6d76501758a2dd38376d ("All changes from PDE branch from svn in one commit."). It is first commit when pde branch is diverging from master. For some reason I don't see it here in list of commits of this pull request.

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-01-26_13-12-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1456/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by adrpo** [comment]
@sjoelund: seems that the spell checker found "aspell: PDEModelica", what should we do about that? Just add it to ".openmodelica.aspell" in the top directory?

**Comment by sjoelund** [comment]
Yes, that seems reasonable. Just note that you need to use aspell to add it to the dictionary as it is sorted in some odd way if I remember correctly.

**Comment by adrpo** [comment]
@jansilar: can you add PDEModelica word to the dictionary so we can run the pull request once again?

**Comment by jansilar** [comment]
I'm not sure how it should be added. I see dictionary file OpenModelica/.openmodelica.aspell . Is this the right one? This is plain text file. Martin suggests to use aspell to add the word, but aspell produces some binary file.

**Comment by adrpo** [comment]
@sjoelund: any suggestion on how to update the aspell file?

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-01-27_09-30-31](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1465/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by sjoelund** [comment]
It passes the spellcheck part now. But some commit has trailing whitespace in it. Any such commit should be amended.

**Comment by jansilar** [comment]
Trailing whitespaces should be fixed now. I corected old commits using interactive rebase and than force-pushed them. It is not obvious whether the modified commits are in the pull request, as the mesages and dates are not changed. But I hope it is OK now.

**Comment by jansilar** [comment]
Run the tests again, please.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-01-28_10-03-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1476/console).

**Comment by jansilar** [comment]
I'm not sure what is the problem now. What is the segmentation fault? Is the problem that my omc isn't compilable on Hudson? On my computer it is. (I did >>make clean & make omc just now to be sure). Does it make sense to rebase my branch on current master and check whether it builds then?

**Comment by sjoelund** [comment]
It means your omc breaks something so that it cannot handle everything in the boostrapping. Did you try running the entire testsuite using your generated OMC? On your computer, you might be using /usr/bin/omc to compile omc whereas on Hudson we do not allow this.

**Comment by jansilar** [comment]
I don't understand some essential aspects of bootstrapping. Am I right that after "make clean" omc is it built using /usr/bin/omc? How should be omc built again using the new built omc?

I compile the omc and run the testsuite this way:

~/EclipseWorkspace/OpenModelica$make clean
~/EclipseWorkspace/OpenModelica$ autoconf
~/EclipseWorkspace/OpenModelica$ ./configure CC=clang CXX=clang++ OMPCC="gcc -fopenmp" --with-cppruntime
~/EclipseWorkspace/OpenModelica$ make testsuite-depends -j8
~/EclipseWorkspace/OpenModelica$ make omc -j8
~/EclipseWorkspace/OpenModelica$ make omlibrary-core
~/EclipseWorkspace/OpenModelica$ cd testsuite/partest
~/EclipseWorkspace/OpenModelica/testsuite/partest ./runtests.pl

So it's probably wrong.

**Comment by adrpo** [comment]
You can add --without-omc to the configure command to make sure you don't use any existing omc. Then it will build it from the C files and then use that to build from your sources and then use that to build again. This way we make sure we don't break anything with regards to bootstrapping.

**Comment by jansilar** [comment]
Does it mean that when building with --without-omc I do just once "make omc" and it will do all you write at once?

**Comment by adrpo** [comment]
@jansilar: no as far as i know, just the first time (or if you do make clean), after that it will use the existing build/bin/omc

**Comment by jansilar** [comment]
OK. But for the first time after clean it does everything you write at once. No need to run the build several times to get the bootstrapped omc. Is it right?

**Comment by adrpo** [comment]
Yes.

**Comment by jansilar** [comment]
With the --without-omc switch it really doesn't compile. The last lines of the console output are below. There isn't any specific error message. Do you have any hint how to localize and resolve the problem?

 ** CodegenFMU template compilation ** 
/home/janek/EclipseWorkspace/OpenModelica/build/bin/omc CodegenFMU.tpl > CodegenFMU.mo.log || (cat CodegenFMU.mo.log && false)
 ** CodegenFMU1 template compilation ** 
/home/janek/EclipseWorkspace/OpenModelica/build/bin/omc CodegenFMU1.tpl > CodegenFMU1.mo.log || (cat CodegenFMU1.mo.log && false)
 
 ** CodegenFMU2 template compilation ** 
/home/janek/EclipseWorkspace/OpenModelica/build/bin/omc CodegenFMU2.tpl > CodegenFMU2.mo.log || (cat CodegenFMU2.mo.log && false)
 
 
 make[6]: Leaving directory `/home/janek/EclipseWorkspace/OpenModelica/OMCompiler/Compiler/boot'
make[5]: *** [generate-files-in-steps] Error 2
make[5]: Leaving directory `/home/janek/EclipseWorkspace/OpenModelica/OMCompiler/Compiler/boot'
make[4]: *** [bootstrap-from-tarball] Error 2
make[4]: Leaving directory `/home/janek/EclipseWorkspace/OpenModelica/OMCompiler/Compiler/boot'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/janek/EclipseWorkspace/OpenModelica/OMCompiler/Compiler/boot'
make[2]: *** [omc-bootstrapped] Error 2
make[2]: Leaving directory `/home/janek/EclipseWorkspace/OpenModelica/OMCompiler'
make[1]: *** [all-runtimeCPPinstall] Error 2
make[1]: Leaving directory `/home/janek/EclipseWorkspace/OpenModelica/OMCompiler'
make: *** [omc] Error 2

**Comment by sjoelund** [comment]
Running GDB on the code to find out where the code fails, etc.

**Comment by adrpo** [comment]
@sjoelund: could it be because  Compiler/OpenModelicaBootstrappingHeader.h is changed?

**Comment by sjoelund** [comment]
Not because the header changed. But quite probably because fields in existing structures in Absyn.mo changed (since it's new keywords, etc instead of annotations).

**Comment by jansilar** [comment]
The problem is probably introduced in my first commit 2b64ae7d3dc3. This commit is not buildable at all because I forgot to stage newly generated OpenModelicaBootstrappingHeader.h. The next commit which fixes it (aaf256d079) is buildable usign --with-omc=/usr/bin/omc but not --without-omc.
The uniontype ElementAttributes structure in Absyn.mo is here really changed. There is new isField property added in it. But I don't know, what it could break.

**Comment by sjoelund** [comment]
I would guess changing Absyn.EQ_EQUALS to two different ones would be better than the current approach. It could even be added as an annotation in the parser to make the compiler have fewer changes overall. The memory consumption for all EQ_EQUALS grows with this change... I guess a new bootstrapping tarball would be needed for this pull request otherwise. And there are still some fixes that should go in the compiler before the next one...

**Comment by jansilar** [comment]
I agree it's good idea. I splited EQ_EQUALS into EQ_EQUALS and EQ_PDE. But there are still some problems. I think it will need more time. Lets continue with this pull request after workshop/modprod. Thanks for help.

**Comment by sjoelund** [comment]
The location of OpenModelicaBootstrappingHeader.h has now moved (when #387 is working), and should not be updated in the same way it was done now. Instead, we should detect how many fields ATTR expects and not pass field if the bootstrapped version is generated. And similar for the special equation, an ifdef looking if the construct is defined, and if it is not do a nice fprintf + abort(). I could probably fix it tomorrow although I might end up creating a different pull request since I need to change some things.

**Comment by sjoelund** [comment]
I opened #392 instead

**Pull request closed without merging**
