### PR TITLE
unify the way we handle version in Windows / Linux

### PR DESCRIPTION
**Pull request by adrpo**
- add OpenModelica prefix to the CONFIG_REVISION in omc_config.h
- removed OpenModelica prefix from Windows generated revision.h

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-12-09_02-42-49](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3529/console).

**Comment by sjoelund** [comment]
+#define CONFIG_VERSION "OpenModelica " CONFIG_REVISION will not duplicate the Linux behaviour. Linux displays either "OpenModelica ..." or "OMCompiler ..." depending on which version/hash is being used.

**Comment by casella** [comment]
Does this fix [#3745](https://trac.openmodelica.org/OpenModelica/ticket/3745)? If so, please close the ticket.

**Comment by adrpo** [comment]
I think it needs more work. I guess in some cases we might double the "OpenModelica " prefix. I'll do some more checking.

**Comment by sjoelund** [comment]
And in some cases Windows builds might display OpenModelica for an OMCompiler hash?
On Dec 10, 2016 00:44, Adrian Pop <notifications@github.com> wrote:I think it needs more work. I guess in some cases we might double the "OpenModelica " prefix. I'll do some more checking.

**Comment by adrpo** [comment]
So how should we deal with this? We don't put any prefix on the thing we get from git and we add it inside the programs: omc, omedit?

**Comment by adrpo** [comment]
Also we need to keep in mind that we use the version number in some scripts (Hudson jobs) which expect no space in it.

**Pull request closed without merging**
