### PR TITLE
Improve tearing memory usage slightly

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-24_12-19-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2046/).

**Comment by hkiel** [comment]
@sjoelund Why don't you merge parts of that PR? Some things seem to be sensible and improve other places as well (e.g. change to List.mo)?

**Comment by sjoelund** [comment]
Mostly because @casella did not need tearing for his example model

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-10_21-48-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2332/).

**Pull request closed without merging**
