### PR TITLE
Ticket 3707

### PR DESCRIPTION
**Pull request by lochel**
This PR is about to fix [#3707](https://trac.openmodelica.org/OpenModelica/ticket/3707).

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_12-28-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1663/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_14-07-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1668/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_15-22-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1672/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_16-01-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1674/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_16-37-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1677/).

**Comment by lochel** [comment]
@sjoelund, @adrpo I cannot reproduce the failing test from the Hudson job, neither on Windows nor Linux. What can I do to push this changes? The changes would probably pass the Hudson check if I just update the expected output – but that seem to be wrong.

**Comment by sjoelund** [comment]
You probably did not bootstrap your compiler. The bootstrapped compiler should not produce these assertions, so the code either needs to be different for MetaModelica or you need to guard MetaModelica code whenever this code could be called.

**Comment by sjoelund** [comment]
I do believe Codegen knows if it is in function or simulation mode, so generate code without this assertion printed for MetaModelica (only calling MMC_THROW()).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_17-27-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1678/console).

**Comment by lochel** [comment]
@sjoelund Thanks!

**Pull request closed without merging**
