### PR TITLE
Fix bug in homotopy solver

### PR DESCRIPTION
**Pull request by ptaeuber**
Do not discard the solution at the beginning of each iteration step.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-08-30_10-53-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4512/console).

**Comment by casella** [comment]
Seems like a good idea :)

**Comment by ptaeuber** [comment]
It is not that grave as it may sound :) What is called homotopy solver in the OMC consists of several solvers called in order (newton, hybrid, actual homotopy). So in the most cases the actual homotopy solver (which was affected by the bug) is never used.

**Comment by casella** [comment]
Sure.
I have the feeling, remembering past debugging sessions, that also in other cases the iterative solution process was starting from the original start values instead of from the previous solution. It could be good to check that this doesn't happen anywhere.

**Pull request closed without merging**
