### PR TITLE
Fix runtime CFLAGS detection

### PR DESCRIPTION
**Pull request by sjoelund**
The old code only worked for some combinations of CFLAGS. It did not
actually find -fno-dollars-in-identifiers.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-17_07-44-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5580/).

**Comment by sjoelund** [comment]
@wibraun would it be possible to stop using macros the symbolic Jacobian code? Or at least stop using dollars in the identifiers?

**Comment by sjoelund** [comment]
I think we could just use System.unquoteIdentifier instead. I'll look into it...

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-17_08-35-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5581/).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-04-17_09-23-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5582/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-04-17_09-37-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5583/console).

**Comment by wibraun** [comment]
Yes, we can stop using macros in symbolic jacobian. I'll can try to do so.

**Comment by sjoelund** [comment]
Variables beginning with `$` will now be quoted in the same way that variables beginning with `'` are quoted. Of course, the C-code becomes unreadable anyway, so we might as well point directly to some array index but at least on some platforms where the linker does not support `$` in variable names, we can now compile models.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-25_10-52-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5628/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-25_11-20-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5629/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-25_12-41-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5631/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-25_13-33-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5632/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-02_09-02-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6588/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-02_11-28-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6591/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-02_13-16-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6593/console).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 3685fba58ccf00668d2ffc0c7b4d2518f4c98b1c d0c8da1532843f969c50f9855328ca8c53c27a4e

**Pull request closed without merging**
