### PR TITLE
Rename solvers

### PR DESCRIPTION
**Pull request by sjoelund**
- Radau1 is now impeuler
- Lobatto2 is now trapezoid

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-02-02_17-13-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1498/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-02-02_17-39-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1500/).

**Comment by casella** [comment]
IMHO, better to have aliases and keep the old names

**Comment by casella** [comment]
The documentation should then refer, e.g., trapezoid to lobatto2, but both should be present

**Comment by sjoelund** [comment]
Check the latest documentation to see if you are happy :)
On Feb 2, 2016 19:51, Francesco Casella <notifications@github.com> wrote:The documentation should then refer, e.g., trapezoid to lobatto2, but both should be present

**Comment by casella** [comment]
Not really, sorry.

[The user's guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-s) shows what different values of the -s flag do, but doesn't show what their values actually are for many of them, starting from Explicit Euler - what is the value of the flag for that option? And for symbolic implicit euler with step-size control?. 

To make things worse, the subsequent section "Integration Methods" discussess only part of them, and in a different order.

The result is indeed very confusing.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-03_07-48-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1506/console).

**Pull request closed without merging**
