### PR TITLE
fix ticket:3983

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-30_17-33-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2987/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-30_17-47-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2988/console).

**Comment by sjoelund** [comment]
Remember summaries like fix XXX doesn't give any information without visiting trac. It would be nice if the summary always said what the commit was supposed to do. Helps with git blame, etc 
On Jun 30, 2016 5:11 PM, wibraun <notifications@github.com> wrote:



You can view, comment on, or merge this pull request online at:
  https://github.com/OpenModelica/OMCompiler/pull/996

Commit Summary
fix ticket:3983

File Changes

    M
    SimulationRuntime/c/simulation/solver/ida_solver.c
    (2)
  
    M
    SimulationRuntime/c/util/simulation_options.c
    (10)
  
    M
    SimulationRuntime/c/util/simulation_options.h
    (2)
  

Patch Links:
https://github.com/OpenModelica/OMCompiler/pull/996.patchhttps://github.com/OpenModelica/OMCompiler/pull/996.diff

**Comment by wibraun** [comment]
@sjoelund Okay, you are right get helpful comments with git blame, etc is quite important.

**Pull request closed without merging**
