### PR TITLE
allow disabling of LOG_STDOUT and LOG_ASSERT streams

### PR DESCRIPTION
**Pull request by adrpo**
I implemented a fix for ticket:5039 (https://trac.openmodelica.org/OpenModelica/ticket/5039).
@lochel, @wibraun please have a look if is OK with you.
I changed the stream names 
"stdout" to "LOG_STDOUT"
"assert" to "LOG_ASSERT"
but maybe they should be kept, what do you think?

### CODE REVIEW

**Comment by adrpo** [comment]
I changed now so that we keep 'stdout' and 'assert' stream names and disabled their log with -lv=-stdout and -lv=-assert.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-07-08_15-52-29](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5877/console).

**Comment by adrpo** [comment]
@lochel disabling these streams is for people that know what they are doing. They are activated by default.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-07-09_11-33-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5878/console).

**Pull request closed without merging**
