### PR TITLE
Do partitioning for removed equations

### PR DESCRIPTION
**Pull request by gossen**
Each BackendDAE.EqSystem has its own removed equations section. Unpartitioned removed equations stay in BackendDAE.Shared. Output in BackendDump is changed as well.

Also  base clocks is added in synchronous dump info.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-09_18-44-31](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/359/console).

**Comment by adrpo** [comment]
@lochel, is the pull request OK with you, can I merge it? The testsuite is OK.

**Comment by lochel** [comment]
I will check the commits tomorrow morning.

**Comment by adrpo** [comment]
Thanks @lochel!

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-10_09-37-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/362/console).

**Comment by adrpo** [comment]
This commit makes 3 models in our non-public testsuite fail. I'll investigate more.

**Comment by lochel** [comment]
Okay. Let me know if I can help you somehow.

**Comment by adrpo** [comment]
@lochel, it seems that simulation works fine for the models but if we set these flags:

    setCommandLineOptions("+d=nogen,initialization,backenddaeinfo,discreteinfo,stateselection");

then the simulation fails. I'll send you a model via email so you can debug this.
I tried to remove each of these flags and it doesn't help, it fails with any of them (except nogen), so it seems to be some issues with handling the debug flags in the back-end.

**Comment by adrpo** [comment]
This also happens now for these two models in MSL:
    Modelica.Media.Examples.SolveOneNonlinearEquation.Inverse_sine
    Modelica.Utilities.Examples.readRealParameterModel
You can test with these using a script like:
    loadModel(Modelica); getErrorString();
    setCommandLineOptions("+d=nogen,initialization,backenddaeinfo,discreteinfo,stateselection"); getErrorString();
    buildModel(Modelica.Utilities.Examples.readRealParameterModel); getErrorString();

We should probably add a test with something like this after we fix the problem.

**Comment by adrpo** [comment]
I found the problem: 

    BackEndDump.dumpCompShort1 

fails when calling:

   comps := BackendDAEUtil.getStrongComponents(inSyst);

because inSyst has BackendDAE.NO_MATCHING which is not handled.

Hopefully I fixed this issue with commit:
https://github.com/OpenModelica/OMCompiler/commit/b25d1f38d8f55f48e306bcade41120076b32dacc

@lochel, @gossen maybe you can check why the system to be dumped has NO_MATCHING.
I tested with model Modelica.Utilities.Examples.readRealParameterModel.

**Comment by gossen** [comment]
I think the reason of changes is the new function [BackendDAEUtil.filterEmptySystems](https://github.com/OpenModelica/OMCompiler/commit/7c8141652c3aa99942360ed5964a8b8f2b6343dc#diff-fb8f0507e8e5a997f806123e20977ac9L7604).

The old function did nothing if dae had consisted of single eqsystem.
The new function processes and filters out all eqsystems. And if none of eqsystem is remained it creates new empty system.

**Comment by adrpo** [comment]
Eh, no matter, is better to handle the NO_MATCHING anyway. 
Hopefully this doesn't get us into any other issues :)

**Comment by adrpo** [comment]
I now added a test about the issue so we don't run into it again: https://github.com/OpenModelica/OpenModelica-testsuite/commit/f9c6fadfd4c4a09b2ac38d87e0ac00e8475f19c2

**Pull request closed without merging**
