### PR TITLE
fixes issues from ticket:4395

### PR DESCRIPTION
**Pull request by wibraun**
- added runtime option newtonMaxStepFactor, which adjustes the maximum
    step size of a newton step in kinsol.
  - used as: mxnewtstep = maxStepFactor * norm2(xScaling)
  - added a much better initial value for the maximum step size

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-08-31_18-29-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4514/console).

**Comment by casella** [comment]
I'm not sure I understand what you mean by "step size of the Newton step". Can you elaborate a bit more?

**Comment by wibraun** [comment]
With the newton step size I mean the the lambda in the update equation of one newton iteration:
`x_{n+1} =  x_n + λ * δ`
kinsol bounds that  `λ` with the following values:
`λ_min = steptol / norm(δ)`
and now
`λ_max = maxstepfactor * norm2(xScale)`

Before it was:
`λ_max = 1000 * norm2(x_0)`
and if `λ_max < 1` it is set to one.

**Comment by casella** [comment]
According to your experience, what are good values for this parameter and according to which criteria?

**Comment by wibraun** [comment]
I've set the default value for `maxstepfactor` to `1e12` more or less based on the experience with examples in ticket:4395.

**Pull request closed without merging**
