### PR TITLE
SimCode refactoring

### PR DESCRIPTION
**Pull request by gossen**
Replace record constructors, extract functions, refactor match statements.

### CODE REVIEW

**Comment by lochel** [comment]
I think it would be good to add a short comment for the new tuple-types (e.g. ``SimCodeUtil.AddTempVarsArg``) that describe what the attributes are used for, since the tuple attributes haven't even a name.

**Comment by lochel** [comment]
Please just squash the commits and then I will start the hudson job to merge your changes.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-07-22_15-03-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/420/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-22_15-43-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/421/console).

**Pull request closed without merging**
