### PR TITLE
Updated help text for optimization modules

### PR DESCRIPTION
**Pull request by lochel**
Added default values for "--preOptModules" and "--postOptModules" to help page.

This is absolutely necessary if one wants to use one of these flags, since most of the modules are essential and even the ordering is important.

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo Are there translations of the help page available that need to be changed as well?

**Comment by adrpo** [comment]
No idea. Maybe @adeas31 knows about this.

**Comment by lochel** [comment]
The default values are pretty long. So should they get line-wrapped or not? I think it is better for copy&paste usage to not line-wrap the values.

Using line-wrapping it would look like this:
```
The modules used by default are:
--preOptModules=unitChecking,evaluateReplaceProtectedFinalEvaluateParameters,st-
ateMachineElab,simplifyIfEquations,expandDerOperator,removeEqualFunctionCalls,-
clockPartitioning,findStateOrder,introduceDerAlias,inputDerivativesForDynOpt,r-
eplaceEdgeChange,inlineArrayEqn,removeSimpleEquations,comSubExp,resolveLoops,e-
valFunc,sortEqnsVars
```

Otherwise everything would be in one line:
```
The modules used by default are:
--preOptModules=unitChecking,evaluateReplaceProtectedFinalEvaluateParameters,stateMachineElab,simplifyIfEquations,expandDerOperator,removeEqualFunctionCalls,clockPartitioning,findStateOrder,introduceDerAlias,inputDerivativesForDynOpt,replaceEdgeChange,inlineArrayEqn,removeSimpleEquations,comSubExp,resolveLoops,evalFunc,sortEqnsVars
```

**Comment by adeas31** [comment]
Take a look at https://github.com/OpenModelica/OMCompiler/tree/master/Compiler/Translation. The instructions seems a bit old some references of SVN. @sjoelund time to update it.

**Comment by lochel** [comment]
As far as I understand there is no translation for the optmodules help page yet.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-30_13-53-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/456/console).

**Comment by adeas31** [comment]
You need to update it in order to generate the translation.

**Pull request closed without merging**
