### PR TITLE
Make KINSOL compatible with adaptive homotopy

### PR DESCRIPTION
**Pull request by ptaeuber**
This workaround sets -homotopyOnFirstTry so trying without homotopy
first is not possible (for kinsol with adaptive homotopy).

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-02-12_21-24-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5236/).

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-02-13_00-18-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5241/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-02-13_00-33-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5243/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-13_17-10-46](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5256/console).

**Comment by casella** [comment]
I am not sure I understand exactly what happened with this pull request. Why can't we first try kinsol without homotopy?

**Comment by ptaeuber** [comment]
You can, but then you have to compile with an **equidistant** homotopy approach. The **adaptive** approaches manipulate the relevant equation systems by collecting the homotopy components, adding a variable (`n x (n+1)` system) and calculating the symbolic jacobian for the `n x (n+1)` system. This structure can only be handled by the homotopy solver. The other solvers can be fooled more or less by just telling them it is a regular `n x n` system, but not kinsol...
What should be done in the future is to create separate components for a homotopy approach and a normal approach, similar to what is done in the case of dynamic tearing. Another way would be to have a third initialization DAE for lambda=1. With this approach the lambda1-DAE might also benefit from some optimization modules ...

**Pull request closed without merging**
