### PR TITLE
Initial OPC UA Support

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
@lochel @wibraun - does the functionality seem OK? The real-time synchronization does not consider events, but is otherwise working fine.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-03-22_19-42-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2005/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-22_19-46-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2006/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-22_20-11-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2007/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-22_20-57-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2009/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-22_21-40-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2010/console).

**Pull request closed without merging**
