### PR TITLE
Replace BackendDAE record constructors

### PR DESCRIPTION
**Pull request by gossen**
Replace BackendDAE record constructors in BackEnd and SimCode

### CODE REVIEW

**Comment by lochel** [comment]
It would be nice if you could squash your commits if the pull request is ready to merge.

**Comment by gossen** [comment]
Done.

**Comment by lochel** [comment]
Hudson already is testing.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-06_10-19-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/323/console).

**Pull request merged**
