### PR TITLE
Added flags for input and output path.

### PR DESCRIPTION
**Pull request by adeas31**
Input path flag `-inputPath` is used to read the model_init.xml and model_info.json files. `-f` flag for model_init.xml file gets the preference over `-inputPath`.
Output path flag `-outputPath` is used to write the output files like model_res.mat, model_prof.intdata etc. `-r` flag for model_res.mat file gets preference over `-outputPath` flag.
Fixes [ticket:4583](https://trac.openmodelica.org/OpenModelica/ticket/4583) where we need to set a different working directory for simulation executable.

### CODE REVIEW

**Comment by lochel** [comment]
@adeas31 I guess the ticket number is wrong.

**Comment by adeas31** [comment]
The ticket number is correct.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-02_21-27-29](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4860/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-07_12-29-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4890/console).

**Pull request closed without merging**
