### PR TITLE
some minor list optimizations

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by hkiel** [comment]
@sjoelund can you please run hudson on this? Saves a few MB for ScalableTestSuite

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-07-07_14-22-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3010/).

**Comment by hkiel** [comment]
@sjoelund Hum, ... overlooked the 'r' in List.map1r
Now fixed. Can you run again please?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-07-07_14-53-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3011/console).

**Pull request closed without merging**
