### PR TITLE
aktived solveSimpleEquation

### PR DESCRIPTION
**Pull request by vruge**
- don't do lateInlineFunction twice...

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-09-14_08-26-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/775/).

**Comment by adrpo** [comment]
@lochel, what do we do about this pull request? We just close it, or?

**Comment by lochel** [comment]
Yes, closing this request should be fine. One can open a new pull request if necessary.

**Comment by adrpo** [comment]
@vruge: we will close this issue. Please open it again if needed.

**Comment by vruge** [comment]
Okay, I will rewritte the module solveSimpleEquation.
Independent, lateInlineFunction should be deactived.

**Pull request closed without merging**
