### PR TITLE
Check if all inputs to external object constructors have been evaluated before calling them

### PR DESCRIPTION
**Pull request by lochel**
This is related to #1341 and #1496.

### CODE REVIEW

**Comment by lochel** [comment]
@sjoelund One need to test if all inputs to external object constructors are of parameter variability. I can do it in the backend, but maybe it would be better to check it in the frontend. What do you think?

**Comment by sjoelund** [comment]
You can't really check it in the frontend. External objects are allowed to be passed non-parameters. I'd say it's discouraged to pass it a time-varying signal though...

**Comment by lochel** [comment]
> External objects are allowed to be passed non-parameters.

Well, that is currently not supported by OpenModelica…

**Comment by sjoelund** [comment]
No, it is supported :) In functions, we can construct external objects just fine.

**Comment by lochel** [comment]
But not yet within models …

**Comment by sjoelund** [comment]
So it makes sense to check it in the backend, then. And use Error.mo message for the error so gettext is used and the message can be translated :)

**Comment by lochel** [comment]
I will not add error messages for that, but support it properly in the back end. It seems that there are some good reasons to do it, e.g. it is used within the DeviceDrivers library.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-21_14-53-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3942/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-02-21_15-51-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3943/console).

**Pull request closed without merging**
