### PR TITLE
Implement Bitmap

### PR DESCRIPTION
**Pull request by hkiel**
- [x] put base64 data into svg image
- [x] resolve image url

### CODE REVIEW

**Comment by hkiel** [comment]
How do I correctly reference image URLs (e.g. `modelica://Modelica/Resources/Images/Mechanics/MultiBody/Visualizers/PipeWithScalarFieldIcon.png`) in the SVG?

**Comment by hkiel** [comment]
@sjoelund Do I have to resolve the URI myself, or can I query omc for the data?
Something like loadBase64("file/URI") would be good (reads binary file and returns string with base64 data)

**Comment by sjoelund** [comment]
https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#uritofilename (and then open it in Python to encode it)

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-10-05_11-55-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6085/console).

**Pull request closed without merging**
