### PR TITLE
[NF] Replace package constants by default.

### PR DESCRIPTION
**Pull request by perost**
- Implemented new phase that replaces package constants.
- Added debug flag replacePackageConstants to toggle whether to
  replace or collect package constants (default replace).
- Added more generic traversal functions for Equation and Statement,
  and removed some duplicated code.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-22_14-28-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4980/console).

**Comment by casella** [comment]
I'm eager to see the impact on MSL 3.2.2 coverage of this PR

**Comment by sjoelund** [comment]
Fewer affected than I thought it would:
https://libraries.openmodelica.org/branches/history/newInst/2017-11-21%2021:07:18..2017-11-22%2015:08:16.html

**Comment by casella** [comment]
Yeah, there are still many undefined constants that break the compilation of C code, see e.g. [this one ](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.2/files/Modelica_3.2.2_Modelica.Electrical.Analog.Examples.OpAmps.Integrator.err) or [this one](https://libraries.openmodelica.org/branches/newInst/Modelica_3.2.2/files/Modelica_3.2.2_Modelica.Electrical.Analog.Examples.ThyristorBehaviourTest.err)

**Pull request closed without merging**
