### PR TITLE
Make translateModelFMU return the name of the FMU

### PR DESCRIPTION
**Pull request by lochel**
see [ticket:4262](https://trac.openmodelica.org/OpenModelica/ticket/4262)

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo @adeas31 Is this good enough?

**Comment by adrpo** [comment]
Yep, is OK. You will however need to change quite some tests also :)

**Comment by adeas31** [comment]
Looks fine to me. Maybe not required to update tests since you returning just the file name in that case.
Perhaps we should also update `translateModelXML`.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-10_16-23-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3896/).

**Comment by lochel** [comment]
I just noticed that `translateModelXML` is not mentioned [here](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html) and has no test in the test suite.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-02-10_19-21-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3897/console).

**Comment by adeas31** [comment]
Because `translateModelXML` is not part of `ModelicaBuiltin.mo`.
@alash325 can you fix this? Also add some tests.

**Comment by alash325** [comment]
@adeas31 I will fix it.

**Pull request closed without merging**
