### PR TITLE
Fix equation indexes for clocked equations

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-10_11-18-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3890/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-10_13-22-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3893/).

**Comment by sjoelund** [comment]
@lochel @vruge  I guess we should remove the unpredictable timings in this testcase form the testsuite... Or at least have a way to disable execution time measurements when running the simulation.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-02-10_14-19-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3895/console).

**Comment by lochel** [comment]
> I guess we should remove the unpredictable timings in this testcase form the testsuite... 

Sure, it's totally annoying...

**Pull request closed without merging**
