### PR TITLE
Fmu experimental

### PR DESCRIPTION
**Pull request by fbergero**
An extra non standard function is included in the generated FMU fmi2GetSpecificDerivatives
(if the +d=fmuExperimental flag is set).

This function allows the FMU user to evaluate some state derivatives (instead of all using fmi2GetDerivatives). This is useful for QSS and Multirate algorithms.

I briefly describe the changes I have made:
* A new function in OMCompiler/SimulationRuntime/fmi/export/fmi2/fmu2_model_interface.c
* Three functions in the OMCompiler/Compiler/Template/CodegenC.tpl template to generate the necessary functions in the C file.
* A new callback in the OpenModelicaGeneratedFunctionCallbacks structure, for the FMU to be able to call the newly generated functions.
* A few new functions in SimCodeUtil.mo to compute the algebraic equations dependencies of each state derivative. 
* A change in the CodegenFMU to include a compilation flag when this is turned on.
* A minimal change in CodegenFMU2 template to include a description in the LogCategories. This is only to keep the FMI Library happy. 

This extra functionality is turend on only with a special flag so it shouldn't change the overall
behavior.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-10-14_13-27-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/942/console).

**Comment by adrpo** [comment]
@fbergero: it seems that you got some conflicts in the meantime, can you fix them?

**Comment by lochel** [comment]
I take care of that and will push the changes in a minute.

**Comment by adrpo** [comment]
Thanks @lochel!

**Comment by fbergero** [comment]
Thanks @lochel . When I created the PR there were no conflicts so I went home happy

**Pull request merged**
