### PR TITLE
-added solver arkode to cpp runtime

### PR DESCRIPTION
**Pull request by RuedKamp**

### CODE REVIEW

**Comment by lochel** [comment]
What is the status of this pull request?

**Comment by adrpo** [comment]
Good question @lochel. I don't know. I'll run a testing of this in Hudson and see if is working fine.
The question from my side is where is the arkode solver code as I don't see any addition in 3rdParty.
Or is it already part of some other package we have there?

**Comment by niklwors** [comment]
arkode  is from the latest sundials  version. Rüdiger already updated the sundials in the omdev folder. 
But we are not sure if it's available on the hudson test servers

**Comment by adrpo** [comment]
Thanks @niklwors. I'm trying to run this on Hudson via OpenModelica_TEST_PULL_REQUEST but somehow it fails currently. I'll try again as I'm not very good at this yet :)

**Comment by adrpo** [comment]
@RuedKamp can you please close this pull request, merge the last changes from OpenModelica in your own github repository and the re-issue the pull request. Also, please remove trailing spaces in files:
OMCompiler/Compiler/Template/CodegenCpp.tpl 1
OMCompiler/SimulationRuntime/cpp/Solver/ARKode/ARKode.cpp 8
See:
https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/356/console

If you are using Eclipse you can install this editor which removes trailing whitespace automatically on save:
http://andrei.gmxhome.de/anyedit/

**Comment by RuedKamp** [comment]
@adrpo anyedit seems to work. Using notepad++ I was'nt able to see the errors.
I guess I can push my changes using the hudson. So the pull request is obsolete

**Pull request closed without merging**
