### PR TITLE
make SymbolicJacobian.createAllDiffedVars tail recursive

### PR DESCRIPTION
**Pull request by hkiel**
fixes ticket:4392

### CODE REVIEW

**Comment by casella** [comment]
Thanks! I'll run the large proprietary model again in the next one or two weeks to test Willi's improvements to the DAE solver, so I'll also check if the problem of ticket 4392 is gone.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-09-08_10-49-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4524/console).

**Comment by hkiel** [comment]
@casella Did you already check?

**Comment by casella** [comment]
Yes, and I no longer needed to increase the stack size to get the model to compile, so I guess your fix worked fine. I'll close ticket [#4392](https://trac.openmodelica.org/OpenModelica/ticket/4392) as well.

**Pull request closed without merging**
