### PR TITLE
Clean up obsolete files from new frontend.

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by lochel** [comment]
@perost Please try again.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-10-10_14-00-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4684/console).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 98f814b4435da831b5c0f26eb85ea252779847e1 ca5cf74771b89fc7918b70ac2f7697550dee345f

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-10_14-14-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4686/console).

**Pull request closed without merging**
