### PR TITLE
optimize List.sort() a bit more

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-17_17-44-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2685/).

**Comment by hkiel** [comment]
@adrpo please run hudson again

**Comment by adrpo** [comment]
Started.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-18_11-26-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2702/console).

**Pull request closed without merging**
