### PR TITLE
Initial MidCode implementation

### PR DESCRIPTION
**Pull request by sp1187**
@sjoelund will handle this PR.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the source code sanity check: [indentation](https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/5503//console)

**Comment by sjoelund** [comment]
It's just @lochel new indentation check that has too many false positives. The code itself should compile...

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-03-28_09-50-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5505/).

**Comment by wibraun** [comment]
New indentation check? Is there any documentation about it? 
Or are we supposed to beat it blindfolded?

**Comment by lochel** [comment]
It is experimental and disabled.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-03-28_10-44-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5506/console).

**Pull request closed without merging**
