### PR TITLE
recursion -> loop

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-17_15-07-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1938/).

**Comment by hkiel** [comment]
too big change... :-(
cannot find the error.

**Comment by hkiel** [comment]
I fixed a bug.
Please run Hudson again.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-18_09-36-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1945/).

**Comment by hkiel** [comment]
removed all problematic parts. Now the test run all fine here.
What I do not understand is the difference in function solvable() returning false and failing.
Is this behaviour wanted???

**Comment by lochel** [comment]
@ptaeuber Can you have a look?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-18_15-28-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1947/console).

**Comment by lochel** [comment]
@hkiel I don’t see how the function could fail. However, it would be good to have an assertion in an else-case for security reasons.

**Comment by hkiel** [comment]
It does fail for the models indicated in the last failing TEST_PULL_REQUEST.
Maybe it is worth investigating that? (Hidden bug?)

**Pull request closed without merging**
