### PR TITLE
Make non-default nonlinear solvers ...

### PR DESCRIPTION
**Pull request by ptaeuber**
... compatible with adaptive homotopy.

kinsol still not compatible

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-08_18-44-49](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5228/console).

**Comment by casella** [comment]
What is the problem with kinsol?

**Comment by ptaeuber** [comment]
It runs into segmentation faults like the other solvers did. But for kinsol I could not correct it in a hurry. I will probably have some time to have a look at it again.

**Comment by casella** [comment]
That would be great, I'll need to combine kinsol and homotopy in the very near future. If you can't do that, please instruct @wibraun on what is left to be done.

**Comment by ptaeuber** [comment]
@casella see #2185

**Pull request closed without merging**
