### PR TITLE
Cleanup ConnectUtil.

### PR DESCRIPTION
**Pull request by perost**
- Update ConnectUtil to modern MetaModelica, and remove unused code.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-01_19-54-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2174/console).

**Comment by sjoelund** [comment]
It got faster, so I guess we can push it.

**Comment by perost** [comment]
I'm already rerunning Hudson to push it in.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-01_20-16-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2175/console).

**Pull request closed without merging**
