### PR TITLE
fixed division by zero error and added homotopy solver

### PR DESCRIPTION
**Pull request by qichenghua**
fixed issue that occured if evaluating the algloop at the initial guess throws a division by zero error and added homotopy solver

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-02-24_10-02-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3951/console).

**Comment by sjoelund** [comment]
@qichenghua Since no test changed, I think you should add a testcase or two to the test suite that uses the new code.

**Comment by qichenghua** [comment]
@sjoelund The fix for the initial guess issue, which occured in the three springs model, was implemented in the Nox solver. We are trying to get the Trilinos package to work, which the nonlinear solver Nox depends on. Once that is done, the nonlinear solver Nox can be tested with the entire test suite. The modification in Kinsol has only changed the error message printed for example in the three springs model.

**Comment by lochel** [comment]
So does the cpp runtime now support the Modelica `homotopy` operator for initialization?

**Comment by qichenghua** [comment]
Unfortunately, not. The nonlinear solver Nox now supports homotopy methods for solving systems of nonlinear equations similar to those used in the c runtime.

**Pull request closed without merging**
