### PR TITLE
Avoid OMEdit crash when exporting a FMU on Windows

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adeas31** [comment]
@adrpo There is no ticket about it. The model that user provided for testing is confidential.

**Comment by adeas31** [comment]
I know but somehow this makes things work. We can run the testsuite and see. I will start hudson without push.

**Comment by adeas31** [comment]
Well I started hudson and just realized that hudson runs the tests on Linux so it doesn't make any difference.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-01-19_15-48-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5114/console).

**Comment by adrpo** [comment]
It could be that MinGW GCC generates bad code on Windows and this circumvents somehow the problem.

**Comment by adeas31** [comment]
See #2141 and #2149.

**Pull request closed without merging**
