### PR TITLE
Introduce aliasing of SimCode equations

### PR DESCRIPTION
**Pull request by sjoelund**
Very many equations are the same in the continuous, initial, lambda0,
and parameter equation systems. This makes some of these equations
become aliases to other ones. The aliasing is performed as the last
step before code generation since this is the most conservative
approach (it might be bad for performance since the same traversals
have been performed on the different systems). Strongly connected
components, if-equations, and algorithms are not considered yet.
Roughly 1/3 of the equations seem to be removed by this aliasing which
hopefully increases performance.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-13_11-17-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5564/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-13_12-58-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5567/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-13_13-27-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5569/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-04-13_14-01-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5570/console).

**Comment by casella** [comment]
How does this feature interact with removeSimpleEquations?

I would expect that a significant fraction of the alias equations are actually trivial equations such as a=b or a+b=0. Or is the 1/3 figure you are referring to a net figure after removing the simple equations?

**Pull request closed without merging**
