### PR TITLE
some optimisations

### PR DESCRIPTION
**Pull request by hkiel**
use List.mapFold* function with many arguments (instead of tuple)
avoid unnecessary creation of tuples

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-04_15-36-46](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2619/).

**Comment by OpenModelica-Hudson** [comment]
Wrong hash OMCompiler 696299383ca68e436cef9f45e618e4cd25c90289 bcd1f2bf720503040e71845717188d3e705de58e

**Comment by hkiel** [comment]
This is the only failure. For me both versions (old and new) of min and max look strange...
Is this really a bug?
```
Equation mismatch: diff says:
--- /tmp/omc-rtest-hudson/openmodelica/cppruntime/fmu/modelExchange/2.0/testModelDescription2.mos_temp1247/equations-expected2016-05-04 15:44:18.433456899 +0200
+++ /tmp/omc-rtest-hudson/openmodelica/cppruntime/fmu/modelExchange/2.0/testModelDescription2.mos_temp1247/equations-got2016-05-04 15:44:46.453959542 +0200
@@ -390,11 +390,11 @@
 valueReference=\"29\"
 description=\"temperature of drum\"
 variability=\"continuous\"
 causality=\"local\"
 initial=\"exact\">
-<Real start=\"500.0\" min=\"273.15\" max=\"2273.15\" nominal=\"500.0\"/>
+<Real start=\"500.0\" min=\"0.0\" nominal=\"500.0\"/>
 </ScalarVariable>
```

**Comment by hkiel** [comment]
found a typo, please let hudson check again

**Comment by hkiel** [comment]
@sjoelund can you please start hudson again?

**Comment by sjoelund** [comment]
Wrong hash happens if there is a different head in the pull request after the PR started (like if Hudson has a queue and something new was pushed, or the wrong hash was copy-pasted by whomever started Hudson).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-10_09-27-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2636/console).

**Pull request closed without merging**
