### PR TITLE
Make a special case for derived classes

### PR DESCRIPTION
**Pull request by sjoelund**
Handle derived class declarations with simple modifications special:
do not translate them using extends, but rather by directly using
the base class + modifiers.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-20_14-31-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2489/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-20_14-54-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2490/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-20_15-59-54](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2492/).

**Comment by sjoelund** [comment]
It feels like this should be faster especially considering some functions are eliminated since they are aliases, but it seems we actually slow down performance. Needs some more investigation.

**Comment by sjoelund** [comment]
I did my other measurements on the wrong branch, so I got bad values. Got 75% of the old time using this branch on larger models...

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-20_18-21-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2496/console).

**Pull request closed without merging**
