### PR TITLE
[BE] RemoveSimpleEquations: Make const exp mandatory for Ceval

### PR DESCRIPTION
**Pull request by kabdelhak**
Fixes ticket #4793

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-03-13_16-46-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6513/).

**Comment by casella** [comment]
@kabdelhak, I guess you should ask @adrpo full push rights and proceed with the merging yourself, unless you really want someone else to review your code, in which case you should probably invite them.

Otherwise, your pushes may remain parked in limbo for a long time...

**Comment by kabdelhak** [comment]
@casella No, somehow my local Runtest has different results so this is just kind of a check which tests i have to fix

**Comment by casella** [comment]
Ah, ok. I hope it's not too time-consuming.

**Pull request closed without merging**
