### PR TITLE
[NF] Improved handling of array modifiers.

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-11_14-11-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5084/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-01-11_14-32-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5085/console).

**Comment by casella** [comment]
@perost, why did this change mostly increase frontend and (surprisingly) backend times on many models and provide little other advantage on [testuite](https://libraries.openmodelica.org/branches/history/newInst/2018-01-11%2010:07:24..2018-01-11%2017:47:55.html)?

**Comment by perost** [comment]
@casella, this was one of the most common issues previously, but it seems like all models that were improved by this commit had other issues hiding behind this one. Not particularly surprising, and I will of course fix the minor issues uncovered by the testing.

**Comment by casella** [comment]
Of course, sorry for asking this all the time. I just wonder what is the depth of the hidden issue queue 😄

**Pull request closed without merging**
