### PR TITLE
Reduce bucket size for function inlining

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-29_09-33-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2114/console).

**Comment by sjoelund** [comment]
Seems to make code run slower. A bit surprising considering functions do not have many inputs or outputs. Perhaps the functions should share a large hashtable and clear it after use instead of the current solution to allocate a new hashtable for each inlined call.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-29_09-47-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2115/console).

**Comment by sjoelund** [comment]
This was resolved by making a single, global function tree shared by all calls.

**Pull request closed without merging**
