### PR TITLE
Fix ticket4407 case preserving filesystems

### PR DESCRIPTION
**Pull request by hkiel**
fixes problem with re-generating files on case-preserving filesystems
- removes files (with wrong case) before creating with correct case again

### CODE REVIEW

**Comment by hkiel** [comment]
@adrpo @sjoelund @adeas31 Can you have a look please? This fixes ticket:4407

**Comment by sjoelund** [comment]
Are you sure that works as expected on OSX? From the code, it seems to have a weird behaviour in two cases:
* When the file is writable and can be overwritten, but the file cannot be unlinked (directory read-only, file writable)
* When the file is not writable, but the directory is writable, a file not readable/writable is removed by OMC in order to create the new file

**Comment by hkiel** [comment]
@sjoelund If file/dir permissions are odd then you anyway will run into trouble, so I don't see a (new) problem here.
If unlinking fails, I guess also writing to the old file will fail!? Also, if the file did not exist before, the behaviour should be the same.

**Comment by hkiel** [comment]
@sjoelund I tried the patch on OSX (without any weird file permissions) and it works fine here.

**Comment by hkiel** [comment]
Can we add this patch?

**Comment by hkiel** [comment]
@lochel Do you work with Windows or OSX and experience the same problem?
This patch does not affect Linux.

**Comment by lochel** [comment]
No, sorry. I'm also using Linux...

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-06-16_12-41-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4329/console).

**Pull request closed without merging**
