### PR TITLE
fix "a or not a" and "a and not a" simplifications

### PR DESCRIPTION
**Pull request by hkiel**
optimize some simplify rules
reuse existing structures

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-11-17_16-44-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4961/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-17_19-36-49](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4963/console).

**Comment by hkiel** [comment]
This patch seems to kill PNLib. I will fix it asap.

**Comment by hkiel** [comment]
@sjoelund The problem comes in with changing `DAE.UNARY(DAE.AND(),...)` to the correct form `DAE.LUNARY(DAE.AND(),...)` which allows to optimize e.g. `a and not a` to `false`
Any idea why the compilation fails if this optimization is turned on??

**Pull request closed without merging**
