### PR TITLE
added new DAEMode module

### PR DESCRIPTION
**Pull request by wibraun**
- can be used with config flag --daeMode=new

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-31_18-17-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5179/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-31_18-34-18](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5180/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-31_18-37-29](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5181/).

**Comment by lochel** [comment]
What are the differences between the old and the new module?

**Comment by wibraun** [comment]
The difference is that in the old approach we had no module, the DAE equation were created additionally at SimCode phase. Now with this new approach there is Backend DAEMode Module which takes care about the necessary work  in on BackendDAE data structure.

**Comment by lochel** [comment]
I see. So there is no difference in terms of functionality?

**Comment by wibraun** [comment]
Actually, yes in the end both approaches should do more or less the same.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-02-01_08-41-46](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5186/).

**Comment by lochel** [comment]
Okay, but what are then the differences so far?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-01_09-53-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5190/console).

**Comment by casella** [comment]
If I understood correctly, the idea is to avoid performing tasks which are only relevant for ODEs, but not if DAEs are solved directly, thus cutting on model generation time. What we had until yesterday was terribly inefficient from this point of view. This is expected to have a very significant impact in the case of large-scale models

**Pull request closed without merging**
