### PR TITLE
update module sortEqnsandVars

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-06_21-24-34](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3988/).

**Comment by wibraun** [comment]
@lochel Because in this order, I think, the adjacency matrix is closer to a lower triangular form.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-06_23-08-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3989/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-07_00-25-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3990/console).

**Pull request closed without merging**
