### PR TITLE
Generate smaller tearing sets for initialization

### PR DESCRIPTION
**Pull request by lochel**
Some tearing sets are bigger than needed. The issue is that the BackendDAE data structure of the initialization system does not contain parameter information which lead to a bad analysis.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-25_14-29-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2533/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-08-11_10-56-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3098/).

**Comment by ptaeuber** [comment]
@niklwors 
Can you have a look at this two models please?:
[Modelica_Fluid_Examples_BranchingDynamicPipes_genDebugSymbols_mos](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3098/testReport/junit/(root)/openmodelica_cppruntime_genDebugSymbols/Modelica_Fluid_Examples_BranchingDynamicPipes_genDebugSymbols_mos/)
[Modelica_Fluid_Examples_BranchingDynamicPipes_hardcodedStartValues_mos](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3098/testReport/junit/(root)/openmodelica_cppruntime_hardcodedStartValues/Modelica_Fluid_Examples_BranchingDynamicPipes_hardcodedStartValues_mos/)

How to handle this kind of error?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-09-16_17-31-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3136/).

**Comment by ptaeuber** [comment]
This bugfix is deactivated for the Cpp-runtime for now.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-09-27_16-53-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3161/console).

**Pull request merged**
