### PR TITLE
Add support for the trapezoidal method (RK2)

### PR DESCRIPTION
**Pull request by sjoelund**
Error for der(x)=1-x shrinks by halving the step size:
* Euler: x2
* Trapezoidal: x4
* RK4: x16

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-02_12-21-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1493/console).

**Comment by vruge** [comment]
Look like Heun's method, which has explicit and not implicit like trapezoidal rule. 
trapezoidal rule: is A-stable.
heun is not A-stable.
By the way lobatto2 is trapezoidal rule (maybe unlucky naming)

**Comment by sjoelund** [comment]
Then fix the naming :)

**Comment by casella** [comment]
We have two problems: one is using the right names, the other is aliases.
I agree with Vitalij we shouldn't call this trapezoidal, but rather heun
We have aliases: lobatto2 is trapezoid, radau1 is implicit euler, how to make this clear and not confusing for users?

**Comment by sjoelund** [comment]
It's explicit trapezoidal :) But yes, @adeas31 OMEdit needs to once again show the tooltip for the description of the solver method as well (where it is easy to describe the aliases of the solvers)...

**Comment by vruge** [comment]
How about an other mapping in OMEdit:
implict euler/(radua1) -> solve=radau1

or renmaing radau1 and labotto2...

**Comment by adeas31** [comment]
Nothing is hard coded in OMEdit. Whatever we have in **simulation_options.h** is shown in OMEdit.

Properly populate the following arrays, 
**extern const char *SOLVER_METHOD_NAME[S_MAX];
extern const char *SOLVER_METHOD_DESC[S_MAX];**

and the solver name and description will be shown automatically in OMEdit.

**Comment by sjoelund** [comment]
@adeas31 SOLVER_METHOD_DESC is no longer used in OMEdit. It is missing those nice descriptions (at least for me on Linux)

**Comment by sjoelund** [comment]
@vruge perhaps it would be better to make the default names be impeuler and trapezoidal, with a description that it is lobatto/radau. I fixed the renaming of exp trapezoidal = Heun and added some descriptions to make things better. I should also fix the documentation generation as it is broken...

**Pull request merged**
