### PR TITLE
Use isPresent() to disable some allocations

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-03-04_16-25-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1809/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-03-04_17-21-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1810/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-03-04_17-25-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1811/console).

**Comment by sjoelund** [comment]
I will merge this after the bootstrapping tarball has been generated since it seems to not work trying to inline the call...

**Comment by sjoelund** [comment]
Or... I will change it to work on boxed types

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-04_22-32-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1812/console).

**Pull request closed without merging**
