### PR TITLE
Performance changes

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-11-30_14-47-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1277/).

**Comment by vruge** [comment]
differentiateEqnsLst:
I would try to move the case "// Why do we just return an empty set if we somehow fail?" in the for loop

**Comment by sjoelund** [comment]
But then the code does not do the same thing it did before. I think the breaking changes are due to trying to change the default for simplify.

**Comment by vruge** [comment]
You're dead right!

**Pull request closed without merging**
