### PR TITLE
List and match optimizations

### PR DESCRIPTION
**Pull request by hkiel**
Please review and let hudson test

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-17_23-02-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1600/console).

**Comment by casella** [comment]
Thanks Henning for all these optimizations. I hope they help streamlining the compiler performance. If you want to find out bottlenecks, I would suggest to profile the ScalableTestSuite library, https://test.openmodelica.org/libraries/ScalableTestSuite_Experimental/BuildModelRecursive.html

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-18_00-06-15](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1602/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-18_00-20-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1603/console).

**Pull request merged**
