### PR TITLE
recursive -> loop

### PR DESCRIPTION
**Pull request by hkiel**
replaced some recursions by explicit loops
optimized some case SOME()/case NONE() -> case SOME()/else

### CODE REVIEW

**Comment by sjoelund** [comment]
I am not sure `case SOME() case NONE()` is slower than `case SOME() else` because the former is usually optimized to a switch-statement anyway. But it does not really hurt.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-23_16-14-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1675/console).

**Comment by hkiel** [comment]
I checked the generated C code and it should be faster, because a for/switch is generated and in both cases optionNone() is called if using case SOME() case NONE().

**Comment by hkiel** [comment]
Also, shouldn't "else" be translated to "default:"?

**Comment by sjoelund** [comment]
It should not :)

**Pull request closed without merging**
