### PR TITLE
Use sets instead of lists in comSubExp

### PR DESCRIPTION
**Pull request by sjoelund**
This resolves some performance problems reported in ticket:4398.

### CODE REVIEW

**Comment by sjoelund** [comment]
This is the second half of #1943

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-25_17-08-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4815/console).

**Comment by hkiel** [comment]
I remember I added code to sort the lists to speed up comparisons. Is that patch still needed???
https://github.com/OpenModelica/OMCompiler/commit/9a5c35eeed772b0c4ab63acfdcdec65b76f2da81

**Comment by sjoelund** [comment]
I only removed parts of it (because a sorted list is not as fast as a binary tree for lookup / intersection; mainly the intersection on the sorted list created a temporary list that was not needed)

**Comment by hkiel** [comment]
So the remaining parts of the sorting must stay?

**Comment by sjoelund** [comment]
I think so. See also https://trac.openmodelica.org/OpenModelica/ticket/4589 for my proposal on how to help write better backend modules

**Pull request closed without merging**
