### PR TITLE
Replace old new instantiation with new new instantiation.

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-23_10-59-41](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2733/console).

**Comment by casella** [comment]
Did we already have a new instantiation, although old? I thought all new stuff was just in private branches.
Should we expect significant performance changes after this, in terms of coverage and speed?

**Comment by adrpo** [comment]
@casella: Yes, we did had some previous implementation but it was not completed (mostly because some things were not at all clear in the specification and the implementation could not be fixed). Now that the specification is a bit more clear (see https://trac.modelica.org/Modelica/ticket/1829) we can restart the work based on a new prototype from @perost but it will take a while to have something that will be usable.

**Comment by perost** [comment]
@casella: And to be clear, the old code wasn't actually used by anything, so it might as well have been in a private branch. But this was back in the days of SVN, where private branches weren't really a thing. The new code used to be in my own private branch, but is now replacing the old code in master to allow more people to work on it. Don't read too much into it, we're just moving some code around.

**Pull request closed without merging**
