### PR TITLE
Fix default value of startTime

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-27_21-26-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3962/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-28_08-01-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3963/).

**Comment by lochel** [comment]
Running a simple model using these changes gives the following error messages:
```
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed

Limited backtrace at point of segmentation fault
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7f7b78c66cb0]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x4)[0x7f7b78c9d8d4]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(omc_File_File_destructor+0x1e)[0x7f7b79feb3ee]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(omc_SerializeModelInfo_serializeWork+0x78d)[0x7f7b797f1f4d]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(boxptr_SerializeModelInfo_serialize+0x23)[0x7f7b797f2033]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(omc_SimCodeMain_callTargetTemplates_runToStr+0xdb)[0x7f7b797e8bab]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(omc_SimCodeMain_callTargetTemplates_runCodegenFunc+0x2b)[0x7f7b797e8a5b]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libomcruntime.so(+0x599eb)[0x7f7b7890c9eb]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libomcgc.so.1(GC_inner_start_routine+0x53)[0x7f7b77a10b73]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libomcgc.so.1(GC_call_with_stack_base+0x12)[0x7f7b77a0bc02]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184)[0x7f7b777d8184]
OpenModelica/build/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: (null) failed
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f7b78d2a37d]
Segmentation fault (core dumped)
```

@sjoelund @adrpo Is this connected to #1495?

**Comment by hkiel** [comment]
@lochel default values for fileNamePrefix, options, cflags and simflags also do look odd (string "<default>" instead of documented string)

**Comment by sjoelund** [comment]
There are a lot of weird things going on in here. The old default values are special and still need something special to mark them different from the user setting a value explicitly (because the default should be to get the value from the experiment annotation). 

I also managed to get `Error building simulator. Build log: /bin/sh: 1: cannot open default: No such file`.... which would be due to the `<default>` marker not being recognized and just sent to the shell command unescaped (meaning trying to redirect stdin from the file `default`). I guess errors might also be due to trying to open files with `<` or `>` in them.

The PR needs a lot more work to fit into the type system...

**Comment by lochel** [comment]
Well, I don't know much about the type system and I will not spend more time on this for now. However, please feel free to push further changes to this branch.

**Pull request closed without merging**
