### PR TITLE
remove List.appendNoCopy()

### PR DESCRIPTION
**Pull request by hkiel**
and replace calls to it by listAppend()

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-13_09-41-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2384/console).

**Comment by hkiel** [comment]
fixed typo
@sjoelund please re-run hudson

**Comment by sjoelund** [comment]
OK

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-13_11-36-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2390/).

**Comment by hkiel** [comment]
now the Compiler warning about misuse of listAppend() pops up...
I will look into fixing them first...

**Comment by sjoelund** [comment]
The one in Types.mo should be OK. Didn't check Graph

**Comment by hkiel** [comment]
same for Graph

**Comment by hkiel** [comment]
I currently cannot test, but don't know why...

```
Running tests...

OPENMODELICAHOME=  
 + DiffAlgorithm.mos                                                                 ... equation mismatch [time:8]

==== Log /tmp/omc-rtest-henning/openmodelica/bootstrapping/log-DiffAlgorithm.mos
true
true
true
""
true
""
true
false
"Error: Error building simulator. Build log: clang -I"/Users/henning/src/OpenModelica/build/include/omc/c"  -g  -O0 -march=native   -c -o TestDiffAlgorithm.o TestDiffAlgorithm.c
clang -I"/Users/henning/src/OpenModelica/build/include/omc/c"  -g  -O0 -march=native   -c -o TestDiffAlgorithm_records.o TestDiffAlgorithm_records.c
clang -single_module -dynamiclib -flat_namespace -o TestDiffAlgorithm.dylib TestDiffAlgorithm.o TestDiffAlgorithm_records.o "-L/Users/henning/src/OpenModelica/build/lib/" "-L/Users/henning/src/OpenModelica/build/lib/x86_64-darwin15.3.0/omc" "-L/Users/henning/.openmodelica/binaries/Print" "-L/Users/henning/src/OpenModelica/OMCompiler/Compiler/Util/Resources/Library/x86_64-darwin" "-L/Users/henning/src/OpenModelica/OMCompiler/Compiler/Util/Resources/Library/darwin64" "-L/Users/henning/src/OpenModelica/OMCompiler/Compiler/Util/Resources/Library" -lomcruntime -lexpat -lsqlite3 -llpsolve55   -lomniORB4 -lomnithread -lpthread -lomcgc -I"/Users/henning/src/OpenModelica/build/include/omc/c"  -g  -O0 -march=native   -L"/Users/henning/src/OpenModelica/build/lib/x86_64-darwin15.3.0/omc" -Wl,-rpath,'/Users/henning/src/OpenModelica/build/lib/x86_64-darwin15.3.0/omc'    -lOpenModelicaRuntimeC -llapack -lblas -lm -lm
ld: warning: directory not found for option '-L/Users/henning/.openmodelica/binaries/Print'
ld: warning: directory not found for option '-L/Users/henning/src/OpenModelica/OMCompiler/Compiler/Util/Resources/Library/x86_64-darwin'
ld: warning: directory not found for option '-L/Users/henning/src/OpenModelica/OMCompiler/Compiler/Util/Resources/Library/darwin64'
ld: warning: directory not found for option '-L/Users/henning/src/OpenModelica/OMCompiler/Compiler/Util/Resources/Library'
Undefined symbols for architecture x86_64:
  "_omc_Error_getCurrentComponent", referenced from:
      _c_add_message in libomcruntime.a(Error_omc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [TestDiffAlgorithm] Error 1
"

```

**Comment by hkiel** [comment]
@sjoelund please run hudson again, cannot test here
I'm not sure if change to Graph.mo is OK. I would expect that...

**Comment by sjoelund** [comment]
OK

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-13_14-47-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2393/).

**Comment by hkiel** [comment]
reverted Graph.mo to old behaviour and silenced warning.
@sjoelund please test again, should work now.

**Comment by sjoelund** [comment]
Running

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-13_15-14-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2394/console).

**Pull request closed without merging**
