### PR TITLE
Optional feature: global homotopy

### PR DESCRIPTION
**Pull request by lochel**
This recovers the global homotopy approach. It can be activated using  `--homotopyApproach=global`.

Global homotopy enables feedback of the homotopy parameter `lambda` to the entire initialization problem:

> _see Modelica language specification, section 3.7.2.4_
> In electrical systems it is often useful that all voltage sources start with zero voltage and all current sources with zero current, since steady state initialization with zero sources can be easily obtained. A typical voltage source would then be defined as:

```modelica
model ConstantVoltageSource
  extends Modelica.Electrical.Analog.Interfaces.OnePort;
  parameter Modelica.SIunits.Voltage V;
equation
  v = homotopy(actual=V, simplified=0.0);
end ConstantVoltageSource;
```

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-07-23_11-27-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4427/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-07-23_11-49-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4428/).

**Comment by lochel** [comment]
- requires compilation flag `--homotopyApproach=global`
- special treatment of lambda=0
- homotopy path is exported if `-lv=LOG_INIT` is set

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-07-24_15-02-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4432/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-07-24_15-40-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4434/console).

**Pull request closed without merging**
