### PR TITLE
Enhance elabBuiltinDynamicSelect for texts, ticket:3675

### PR DESCRIPTION
**Pull request by rfranke**
This is needed to get dynamic text annotation working in OMEdit.

### CODE REVIEW

**Comment by rfranke** [comment]
The Hudson failure is hardly related to the change!!!

**Comment by sjoelund** [comment]
There is no change to the machine since the last successful build though

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-27_07-25-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3313/console).

**Comment by rfranke** [comment]
The pull request didn't change either -- and passed now.

**Comment by sjoelund** [comment]
So there probably is something numerically tricky in that test, or a race condition.

**Pull request closed without merging**
