### PR TITLE
[OMSI] Fix linking shared libs on mac os

### PR DESCRIPTION
**Pull request by AnHeuermann**

### CODE REVIEW

**Comment by AnHeuermann** [comment]
@sjoelund or @adrpo Could you check if its working on mac OS?
Thanks a lot.

**Comment by adrpo** [comment]
I think we should just merge it and see how is working. I'll start the PR job with it.

**Comment by sjoelund** [comment]
It's using paths @rpath/OMSI/Build_dynamic/base/libOMSIBase.dylib for a file in $(OMBUILDDIR)/$(LIB_OMC)/omsi/libOMSIBase.dylib... Shouldn't it simply be @rpath/omsi/libOMSIBase.dylib ?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-04_17-55-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6636/console).

**Comment by adrpo** [comment]
Now there is a problem in OMEdit build so it seems this issue has been solved.

**Pull request closed without merging**
