### PR TITLE
[NF] Initial support for function vectorization.

### PR DESCRIPTION
**Pull request by mahge**
- Implemented function vectorization.
  - Improved mapping function implementations.
  - Lots of changes to function handling in general. See diffs.
  - Other minor fixes.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-03-15_18-04-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5419/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-03-15_19-02-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5421/).

**Comment by lochel** [comment]
@mahge I guess you can try again.

**Comment by mahge** [comment]
@lochel thanks.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-03-15_20-43-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5426/console).

**Comment by casella** [comment]
@mahge we have 593 regressions and 27 improvements after this commit, see the [Hudson report](https://libraries.openmodelica.org/branches/history/newInst/2018-03-15%2015:32:03..2018-03-16%2001:18:52.html).  

I guess #2282 tries to fix them, right?

@sjoelund  is there a way to check NF-related commits on the core testsuite (basically, the MSL) as we do for the normal ones, before the PR is pulled in? The NewInst testsuite has a typical 8-12 hours latency, so it doesn't help much.

**Comment by sjoelund** [comment]
You just need to manually add all the working MSL models to the test suite and add the -d=newInst flag to the tests. But it seems like a lot of work for such a moving target.

**Comment by adrpo** [comment]
We could automatically generate the tests rather easily from a list of working models

**Comment by casella** [comment]
Why just the working ones? My idea was that the core testsuite also contains the whole MSL 3.3.2 (or possibly MLS master) with d=newInst. That should be easy to add

**Comment by casella** [comment]
@mahge indeed #2282 improved things a lot, see [the report](https://libraries.openmodelica.org/branches/history/newInst/2018-03-16%2001:18:52..2018-03-16%2015:33:44.html).

**Comment by mahge** [comment]
@casella I think the memory issue is a manifestation of [this](https://github.com/OpenModelica/OMCompiler/commit/a134d4eadcc72fc2828d9e8779cc13a131d39daa#commitcomment-28104629). I will just disable that and see what happens. I was just waiting to see the changes from the other commits and didn't want to pile this one on it. I will check more.

**Comment by adrpo** [comment]
@casella: the improvement is like sale discounts, it looks good because you don't see the history :)
It was actually better a while back, but I guess we'll get there and more soon:
https://libraries.openmodelica.org/branches/history/newInst/Modelica_3.2.2-recent.svg

**Pull request closed without merging**
