### PR TITLE
[BE] adjust daeMode flag

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-12-13_16-53-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6276/).

**Comment by OpenModelica-Hudson** [comment]
Pull request did not pass the checks on GitHub. Please sign the CLA.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-12-13_17-25-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6278/console).

**Comment by casella** [comment]
Good that you removed the "new" option. There's nothing more annoying that have something labelled 'new' which is still used after 10 years and then it's replaced because it got old.

Like the new front-end 😄

**Comment by casella** [comment]
Please don't forget to merge this PR also on the maintenance/v1.13 branch, otherwise it won't make it in the final release

Thanks!

**Pull request closed without merging**
