### PR TITLE
model reduction algorithm 

### PR DESCRIPTION
**Pull request by niklwors**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-11-03_16-15-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4866/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by sjoelund** [comment]
Note that Hudson tells you to fix the bad commit instead of adding another one (commit --amend, etc)

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-11-03_16-41-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4868/console).

**Comment by niklwors** [comment]
The problem was the wrong format for ReduceDAE.mo

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-11-03_21-24-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4869/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-12-07_11-27-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5015/console).

**Comment by lochel** [comment]
@niklwors What is the model reduction algorithm doing?

**Comment by niklwors** [comment]
@lochel it is described here:  http://www.ep.liu.se/ecp/043/090/ecp09430136.pdf

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-12-07_14-57-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5017/console).

**Comment by niklwors** [comment]
Does anyone know what the problem is? If I start the build on dev.openmodelica.org the build works fine.

**Comment by hkiel** [comment]
Error comes in here:
```
CMake Error at CMakeLists.txt:576 (MESSAGE):
  Could not find libsundials_nvecserial!

-- Configuring incomplete, errors occurred!
See also "/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/SimulationRuntime/cpp/Build_dynamic/CMakeFiles/CMakeOutput.log".
See also "/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/SimulationRuntime/cpp/Build_dynamic/CMakeFiles/CMakeError.log".
make[4]: Entering directory '/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/SimulationRuntime/cpp/Build_dynamic'
make[4]: *** No targets specified and no makefile found.  Stop.
make[4]: Leaving directory '/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/SimulationRuntime/cpp/Build_dynamic'
Makefile:37: recipe for target 'runtimeCpp' failed
make[3]: *** [runtimeCpp] Error 2
make[3]: Leaving directory '/var/lib/hudson/slave/workspace/OpenModelica_TEST_PULL_REQUEST/OpenModelica/OMCompiler/SimulationRuntime/cpp'
Makefile.common:197: recipe for target 'runtimeCPPinstall' failed
make[2]: *** [runtimeCPPinstall] Error 2
make[2]: *** Waiting for unfinished jobs....

```

**Comment by niklwors** [comment]
yes, but the sundials library is normally build before the cpp runtime is build. But here the build for sundials starts after the cpp runtime.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-12-08_11-00-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5019/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-12-08_13-36-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5020/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-12-13_10-31-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5028/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-12-13_12-43-03](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5030/console).

**Pull request closed without merging**
