### PR TITLE
try to reduce memory usage

### PR DESCRIPTION
**Pull request by hkiel**
- use listReverseInPlace where possible
- use new listReverseArray(l) instead of listArray(listReverse(l))
- remove some recursions and matchcontinue
- avoid List.intersection1OnTrue if only one of the outputs is needed

### CODE REVIEW

**Comment by sjoelund** [comment]
Can you `git commit --amend` + `git push --force` to remove mention of `listReverseArray`?

**Comment by hkiel** [comment]
Done.

**Comment by sjoelund** [comment]
Thanks. Hudson started, so let's hope it passes. I really appreciate your fixes.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-03_19-41-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1796/).

**Comment by hkiel** [comment]
It already encountered a few Failures. I will need to investigate what is going wrong.
Maybe some matchcontinue/match changes...
The models I checked locally all worked fine.

**Comment by hkiel** [comment]
I found two places (one confused true/false, and one place where listReverseInPlace was wrong).
At least EngineV6 works again here. Can you please start hudson, to see what is still not working?

**Comment by casella** [comment]
@hkiel, just ask a password for hudson to @adrpo or @sjoelund

**Comment by hkiel** [comment]
I already did with negative response.
But I still think it is good to have the code reviewed by someone else before it can be pushed to the repo.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-04_10-56-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1799/).

**Comment by hkiel** [comment]
Question @sjoelund @lochel @adrpo:
List.setDifferenceOnTrue() removes only the first occurrence of each of the items to remove. Is that correct?

I would expect that function to throw out *all* occurences of the items to remove. Or is that another function?

**Comment by sjoelund** [comment]
It's more like sets are assumed to not contain duplicates...

**Comment by sjoelund** [comment]
Also, one thing I would like to implement in MetaModelica is the old `isPresent()` operator that was removed from the Modelica language. It is actually not hard to implement for arguments `2..N` and could mean we do not generate lists that are not used by the caller...

**Comment by hkiel** [comment]
Ok, but then I would expect List.intersection1OnTrue() to behave like working on sets as well.
Maybe everything is working fine with true sets, but one is more robust than the other...

**Comment by hkiel** [comment]
Is it okay to write a new function
List.removeOnTrue() with the same signature, but removing *all* occurences (i.e. not assuming uniqueness)?

**Comment by sjoelund** [comment]
Isn't that just `List.filter`?

**Comment by perost** [comment]
There already is a List.removeOnTrue.

**Comment by sjoelund** [comment]
Or something like `list(e for e guard not List.exists(e,lst2,func) in lst1)`

**Comment by hkiel** [comment]
blind me

**Comment by hkiel** [comment]
I removed the changes to the sets, now it works locally. Can you start hudson again, please?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-04_15-02-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1804/console).

**Comment by sjoelund** [comment]
In #507 I try to show how to use `isPresent`. I am unsure if the compiler allows it to be used in the frontend yet though. For example things like `List.splitOnBoolList` were used in a way that the second output parameter was never used... So now we can check for this and make conditional memory allocations.

**Pull request closed without merging**
