### PR TITLE
Use start values as initial guess for nonlinear systems

### PR DESCRIPTION
**Pull request by lochel**
see [ticket:4359](https://trac.openmodelica.org/OpenModelica/ticket/4359) and #1573 

---

**TODO**

- [x] Use start values as **initial guess** for nonlinear systems
- [x] **Don't** use start values if already calculated values are available
- [x] Fix homotopy-based initialization
- [x] Do some more testing

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-29_21-40-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4118/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-30_11-22-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4119/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-30_12-20-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4120/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-30_14-16-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4122/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-30_23-08-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4123/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-31_07-26-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4124/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-31_08-16-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4125/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-31_11-12-21](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4126/).

**Comment by lochel** [comment]
At least `Modelica.Fluid.Examples.Explanatory.MomentumBalanceFittings` simulates now correctly. Maybe this has also an impact on the library coverage tests.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-31_13-37-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4127/console).

**Comment by lochel** [comment]
@vruge This fixes also TFC4.mos from the optimization tests. Former, `y3` had been initialized (correctly) with `-1` and then it had (wrongly) jumped to yet another solution. Now, it keeps following the solution at which it is initialized.

**Comment by lochel** [comment]
@vruge This fixes also TFC4.mos from the optimization tests. Former, `y3` had been initialized (correctly) with `-1` and then it had (wrongly) jumped to yet another solution. Now, it keeps following the solution at which it is initialized.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-31_14-09-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4128/console).

**Comment by vruge** [comment]
@lochel, Are you sure? It's seem initialization from file are failed, now:
'-iif ReferenceFiles/testFinalCon3_ref.mat -iim none'
the solution should have same jump like in the ref file.

**Comment by vruge** [comment]
@lochel Can you explain, why you changes has impact of "-iim none"?

**Comment by lochel** [comment]
> @lochel, Are you sure? It's seem initialization from file are failed, now:
> '-iif ReferenceFiles/testFinalCon3_ref.mat -iim none'
> the solution should have same jump like in the ref file.

I don't get what you want to say.

**Comment by vruge** [comment]
@lochel 
the option **iif** ( Value specifies an external file for the initialization of the model.) is broken.
The value for y3 for time > 0 in the "external file " is posetive. The expected solution should have a jump from -1 to  (approximated) +1 at the beginning.

**Comment by lochel** [comment]
@vruge wrote:
>the option iif ( Value specifies an external file for the initialization of the model.) is broken.
> The value for y3 for time > 0 in the "external file " is posetive. The expected solution should
> have a jump from -1 to (approximated) +1 at the beginning.

The initial solution hasn't changed. So I still don't get your point.
  * So why do you think that the -iif option is broken?
  * Which external file contains the discrete change of `y3`?
  * Why should the continuous variable `y3` jump from one solution to another during continuous simulation mode?

**Comment by vruge** [comment]
@lochel 

> Which external file contains the discrete change of y3? 
Okay, I can repeat my self, no probelem.
In the example you can find `-iif ReferenceFiles/testFinalCon3_ref.mat`
so the file is `ReferenceFiles/testFinalCon3_ref.mat` (relative path). 
You already founded the file for modification in  
https://github.com/OpenModelica/OpenModelica-testsuite/pull/606/files.
  
> So why do you think that the -iif option is broken?
>Why should the continuous variable y3 jump from one solution to another during continuous simulation mode?

The optimization use the full trajectory as initial guess.
You can use the initialization log with "-lv LOG_INIT"  for better overview.

e.g. one of the line is  (before you broken the example)

```
done: time[5] = 0.164495LOG_INIT          | info    | import start values
|                 | |       | file: ReferenceFiles/testFinalCon3_ref.mat
|                 | |       | time: 0.2
LOG_INIT          | info    | import real variables
LOG_INIT          | info    | | x1(start=0.827423)
LOG_INIT          | info    | | x2(start=-0.612681)
LOG_INIT          | info    | | der(x1)(start=-0.857412)
LOG_INIT          | info    | | der(x2)(start=1.9519)
LOG_INIT          | info    | | $OMC$objectLagrangeTerm(start=0.0023959)
LOG_INIT          | info    | | cost(start=0.0023959)
LOG_INIT          | info    | | u(start=0.0489479)
LOG_INIT          | info    | | y1(start=1.12447)
LOG_INIT          | info    | | y2(start=-0.075526)
LOG_INIT          | info    | | y3(start=1.09545)
LOG_INIT          | info    | import real parameters
LOG_INIT          | info    | import real discrete
LOG_INIT          | info    | import integer parameters
LOG_INIT          | info    | import boolean parameters

```
The jump can find in the initial guess.

You committed massages confusing me.
I see by my analyses of the  code it's seem we work with `pre(value)` now. In the commit massage I  find the message "Use start values as initial guess for nonlinear systems ". 

Can you motivate you changes of the initial guess, please?
Why do think is better than the old approach?

**Comment by lochel** [comment]
I don't know how your memory management for the optimization works. However, the imported initial guess is still only an initial guess and doesn't necessarily represent a valid solution, right? So why should there be a discrete change of the continuous variable `y3` in the final solution?

**Comment by vruge** [comment]
if you don't understand optimization (based on your question is much more then memory management ).

Why do you provided wrong results???

**Pull request closed without merging**
