### PR TITLE
Changes for bootstrapping header

### PR DESCRIPTION
**Pull request by sjoelund**
OpenModelicaBootstrappingHeader.h is now treated as part of the tarball
for bootstrapping. This makes it possible to change Absyn.mo without
generating a new tarball.

The build system now generates special a-files for Compiler/runtime/
and Parser/ that uses the tarball version of the header for stage 1 of
the bootstrapping, and a fresh header for other objects. This file is
not copied to the build directory.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-02-09_16-44-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1537/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-02-10_09-29-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1540/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-02-10_09-38-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1541/console).

**Comment by lochel** [comment]
It seems that this broke the Windows build.

**Comment by sjoelund** [comment]
:+1:

**Comment by adrpo** [comment]
I'm trying to fix it but it still compiles on my machine.

**Pull request closed without merging**
