### PR TITLE
fix cosh^2(x)-sinh^2(x)=1 in ExpressionSimplify.simplifyBinary

### PR DESCRIPTION
**Pull request by hkiel**
also add acos(cos(x))=x to ExpressionSimplify.simplifyCall

### CODE REVIEW

**Comment by sjoelund** [comment]
acos(cos(x)) is not equal to x... For example acos(cos(13)) = 0.4336293856408271

And cos(acos(13)) is an error, not 13...

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-11-15_16-37-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4947/).

**Comment by hkiel** [comment]
@sjoelund you are right. The same holds for asin(sin(x)) and atan(tan(x)). So these rules should be removed as well!?

**Comment by hkiel** [comment]
Still sinh^2(x)+cos^h^2(x) is not 1. So the test must be fixed as well.

**Comment by hkiel** [comment]
cosh^2(x)-sinh^2(x)=1 is not commutative, so I need to move that code.
Could it be cosh^2(x)+ (-sinh^2(x))=1 at that stage???

**Comment by sjoelund** [comment]
acos(cos(x)) could be mod(x, pi)? And yes, it is rather common that x-y becomes x+(-y)

**Comment by hkiel** [comment]
acos(cos(x)) is not mod(x,pi), but some triangle function (try to plot it with e.g. geogebra)

**Comment by hkiel** [comment]
@sjoelund @casella I created [ticket:4630](https://trac.openmodelica.org/OpenModelica/ticket/4630) to clarify mathematical simplifications

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-11-16_10-54-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4950/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-11-16_11-40-49](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4951/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-11-16_12-14-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4952/console).

**Pull request closed without merging**
