### PR TITLE
fix in cpp runtime for VS 2013

### PR DESCRIPTION
**Pull request by niklwors**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-10-21_09-29-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3256/).

**Comment by sjoelund** [comment]
Is this PR still active?

**Comment by adrpo** [comment]
We can already compile the code with VS2013 and VS2014 but maybe this has something else in mind.

**Comment by niklwors** [comment]
This pull request is no longer needed

**Pull request closed without merging**
