### PR TITLE
Generate code with less nested brackets (ticket 3478)

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by sjoelund** [comment]
An expression like (a * b) + c will now generate code like (a) * (b) + (c)... Right? You would need to check operator precedence in order to omit unnecessary parenthesis.

**Comment by lochel** [comment]
(a * b) + c will be generated as (a) * (b) + (c)
(a + b) *c will be generated as (a + b) * (c)

**Comment by sjoelund** [comment]
I would still say it is an error if any simulation result changes...

**Comment by lochel** [comment]
No of the results changed, except of some minor numerical issues.

BTW: It is also possible to remove the unnecessary parenthesis for atomic expressions.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-10-02_08-37-53](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/867/console).

**Comment by adrpo** [comment]
Seems there are issues with the parallel tests since this change:
https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PARMOD/157/testReport/(root)/parmodelica_explicit/bug_3339_mos/

**Pull request merged**
