### PR TITLE
Restrict the API based on the access annotation of the encrypted class

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-06-08_23-48-03](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5777/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-06-09_00-26-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5778/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-06-09_00-41-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5779/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-06-09_01-38-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5780/console).

**Comment by sjoelund** [comment]
getAccessAnnotation should be in CevalScriptBackend since it is not used for bootstrapping.

**Comment by adeas31** [comment]
I tried that earlier ([see here](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5778/console)) but it doesn't work and then I moved `getAccessAnnotation` as well.
Probably because `checkAccessAnnotationAndEncryption` calls `getAccessAnnotation`.

**Comment by sjoelund** [comment]
Then you either move setSourceFile to the backend scripting or stub out `checkAccessAnnotationAndEncryption`. None of the encryption stuff belongs with the bootstrapping and it should not be needed to compile it to bootstrap OM.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-06-11_12-03-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5781/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-06-11_12-39-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5782/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-06-12_16-49-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5785/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-06-13_14-33-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5786/console).

**Pull request closed without merging**
