### PR TITLE
Ticket3539

### PR DESCRIPTION
**Pull request by adrpo**
- add support for packing Modelica resources in FMUs (C runtime only for now)

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-02-16_11-30-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3915/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-17_15-55-33](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3922/).

**Comment by OpenModelica-Hudson** [comment]
Rebase failed (please rebase your commit in the PR and try again). If rebase is not desired for some reason, select merge in the job options.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-17_06-39-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5106/).

**Comment by adrpo** [comment]
Closing, as this was already pushed in by  @sjoelund.

**Pull request closed without merging**
