### PR TITLE
fix modelicaStringToCStr for "'"

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by sjoelund** [comment]
I would rather make a general fix that handled escaping every possible name

**Comment by wibraun** [comment]
How would you do that?

**Comment by sjoelund** [comment]
A general approach like checking a regex if it is a valid C identifier and otherwise replace it with an escaped name, like we do for quoted identifiers:
```c
$P_omcQuot_72 = (2.0) * (data->localData[0]->timeValue); /* 'r' = 2*time */
```

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-17_21-32-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2687/console).

**Pull request closed without merging**
