### PR TITLE
changes to support Mingw64

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-07-10_01-50-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/360/console).

**Comment by sjoelund** [comment]
Note that printf macros should cast to long or int explicitly since they expect the input to be of a certain length. %lu expects a long.

**Comment by adrpo** [comment]
Or we could have different formatting strings depending on 32/64 bit. I'll deal with this.

**Comment by sjoelund** [comment]
Should not use different strings for this. Just cast to long and use long printf

**Comment by adrpo** [comment]
Why, if long is not always sizeof(void*). On Windows 64bit long long is sizeof(void*) so it wouldn't work properly.

**Comment by sjoelund** [comment]
Use %p if you want to print a pointer? Or the long long directive always.

**Pull request closed without merging**
