### PR TITLE
added improved symbolical inline solver

### PR DESCRIPTION
**Pull request by wibraun**
- symbolic inline integration is working by replacing the der operator with the
  difference quotient(forward/backward)
- solver supports explicit and implicit order 1 integration methods
  enabled by compiler flag --symSolver=(impEuler|expEuler)
- added solver methods to the runtime -s symSolver|symSolverSsc without and with step size control

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-02-02_14-24-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3848/console).

**Comment by casella** [comment]
@wibraun can you briefly comment in which respect this is different (and hopefully better) from the previously available inline integration methods?

**Comment by wibraun** [comment]
@casella This method replaces the der operators after index reduction by a difference quotient(backward-> implicit, forward -> explicit). The resulting algebraic system is passed though the Backend postOpt modules to achieve symbolical simplifications by removeSimpleEquations, Tearing and so on. In the previous version the replacement was done while code generation phase so that no symbolic simplification could utilized there.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-02-02_22-23-26](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3850/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-02-02_23-17-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3851/console).

**Pull request closed without merging**
