### PR TITLE
[OMSI] Add OMSIBase and OMSISolver libraries

### PR DESCRIPTION
**Pull request by AnHeuermann**
## Purpose
Will be used by OMSIC and OMSICPP libraries (not in master yet). The Base and Solver libraries contain common used functionalities independent of target Language (C or C++).

- Created build structure with Makefiles and CMake
  - Added OMSI to omc target in top Makefile
  - Added OMSI/omsi-clean target to Makefiles
  - Added Makefile.omsi.common with build rules for all OMSI stuff
  - Use CMake build for SimulationRuntime/OMSI
- Added OMSI in Simulation Runtime
  - OMSIBase library contains base functions for
    - data handling
	- event handling
	- solving loops
	- handling xml and json files
	- initialiazing/ freeing stuff
	- ...
  - OMSISolver library contains solver and interface
    - general solver API
	- KINSOL solver
	- LAPCAK solver
  - Data types
    - omsi.h contains most important definitions for OMSI Base lib.
    - solver.h contains most important definitions for OMSI Solver lib.

## Changed files
  - Makefile.common
  - Makefile.in
  - Makefile.omdev.mingw

## New files
 A lot of files are new...
### Used for build process
 -  Makefile.omsi.common
  - SimulationRuntime/OMSI/CMakeLists.txt
  - SimulationRuntime/OMSI/base/CMakeLists.txt
  - SimulationRuntime/OMSI/cmake_uninstall.cmake.in
  - SimulationRuntime/OMSI/solver/CMakeLists.txt

### Used for OMSIBase lib
  - SimulationRuntime/OMSI/base/include/omsi_event_helper.h
  - SimulationRuntime/OMSI/base/include/omsi_global.h
  - SimulationRuntime/OMSI/base/include/omsi_initialization.h
  - SimulationRuntime/OMSI/base/include/omsi_input_json.h
  - SimulationRuntime/OMSI/base/include/omsi_input_model_variables.h
  - SimulationRuntime/OMSI/base/include/omsi_input_sim_data.h
  - SimulationRuntime/OMSI/base/include/omsi_input_xml.h
  - SimulationRuntime/OMSI/base/include/omsi_mmap.h
  - SimulationRuntime/OMSI/base/include/omsi_posix_func.h
  - SimulationRuntime/OMSI/base/include/omsi_solve_alg_system.h
  - SimulationRuntime/OMSI/base/include/omsi_utils.h
  - SimulationRuntime/OMSI/base/include/uthash.h
  - SimulationRuntime/OMSI/base/src/omsi_event_helper.c
  - SimulationRuntime/OMSI/base/src/omsi_initialization.c
  - SimulationRuntime/OMSI/base/src/omsi_input_json.c
  - SimulationRuntime/OMSI/base/src/omsi_input_model_variables.c
  - SimulationRuntime/OMSI/base/src/omsi_input_sim_data.c
  - SimulationRuntime/OMSI/base/src/omsi_input_xml.c
  - SimulationRuntime/OMSI/base/src/omsi_mmap.c
  - SimulationRuntime/OMSI/base/src/omsi_posix_func.c
  - SimulationRuntime/OMSI/base/src/omsi_solve_alg_system.c
  - SimulationRuntime/OMSI/base/src/omsi_utils.c

### Includes for FMI and general data types
  - SimulationRuntime/OMSI/include/fmi2/omsi_fmi2_cs.h
  - SimulationRuntime/OMSI/include/fmi2/omsi_fmi2_me.h
  - SimulationRuntime/OMSI/include/fmi2/omsi_fmi2_wrapper.h
  - SimulationRuntime/OMSI/include/omsi.h
  - SimulationRuntime/OMSI/include/omsi_api_functions.h
  - SimulationRuntime/OMSI/include/omsi_callbacks.h

### Used for OMSISolver lib
  - SimulationRuntime/OMSI/solver/include/omsi_solver.h
  - SimulationRuntime/OMSI/solver/include/solver_api.h
  - SimulationRuntime/OMSI/solver/include/solver_global.h
  - SimulationRuntime/OMSI/solver/include/solver_helper.h
  - SimulationRuntime/OMSI/solver/include/solver_kinsol.h
  - SimulationRuntime/OMSI/solver/include/solver_lapack.h
  - SimulationRuntime/OMSI/solver/src/solver_api.c
  - SimulationRuntime/OMSI/solver/src/solver_helper.c
  - SimulationRuntime/OMSI/solver/src/solver_kinsol.c
  - SimulationRuntime/OMSI/solver/src/solver_lapack.c

Co-authored-by: niklwors <niiklas.worschech@boschrexroth.de>
Co-authored-by: wibraun <wbraun@fh-bielefeld.de>

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-03-20_14-07-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6522/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-03-26_14-19-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6545/console).

**Comment by adrpo** [comment]
There seems to be some sort of dependency issue on building sundials as the MacOS builds are failing.

**Comment by sjoelund** [comment]
There were also failures for building omc in the library testing scripts.

**Pull request closed without merging**
