### PR TITLE
Fix extends handling in NFInst.

### PR DESCRIPTION
**Pull request by perost**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-09_16-04-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3635/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-09_16-29-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3636/console).

**Comment by adrpo** [comment]
@perost: note that the pull request job does not have push by default anymore. you need to tick it.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-10_12-11-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3642/console).

**Pull request closed without merging**
