### PR TITLE
Implement numerical linearization

### PR DESCRIPTION
**Pull request by crupp2**
Implementation of numerical linearization and data recovery.

### CODE REVIEW

**Comment by crupp2** [comment]
This is for trac #3735.

Someone should check the code to make sure some of the variables in linearize.cpp are referenced correctly. In particular checking if the analytic Jacobians are available on line 495.

The code is set up to always default to analytical Jacobians if they are available, but if not then calculate them numerically.

Data recovery matrices are dumped to the file with a new flag -l_datarec. They are always calculated numerically. If someone knows how to calculate them analytically then that could be added.

The code passes the linearization test cases and I have a new validated case to add to the test suite if this request is accepted.

**Comment by sjoelund** [comment]
Please add a PR for OpenModelica-testsuite for your new testcase so we can run this PR against that test as well.

**Comment by sjoelund** [comment]
@wibraun any comments?

**Comment by lochel** [comment]
The implementation looks good. I triggered a hudson job to test the changes.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-28_12-07-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2089/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-29_20-56-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2125/).

**Comment by crupp2** [comment]
Is the correct procedure to rebase this to get rid of the empty merge (similar as for the testsuite)?

**Comment by sjoelund** [comment]
Yes. I always rebase my commits before making a PR :)

**Comment by lochel** [comment]
@crupp2 I've removed the empty merge commit and pushed your changes.

**Comment by adrpo** [comment]
Closing this as @lochel requested.

**Pull request closed without merging**
