### PR TITLE
Redesign SymbolTable handling

### PR DESCRIPTION
**Pull request by sjoelund**
The SymbolTable has been moved out from the frontend completely. It is
now handled by a new module called SymbolTable, which uses a thread-
local variable to avoid passing around the symbol table. This makes the
handling of caching SCode much simpler.

Some functionality has been removed:
- Cached classes in the symbol table (we use the FCache instead)
- Instantiated functions (since they were not used before, and -d=gen
  is not used anyway)
- The LoadedFiles list (since the result was ignored anyway)
- OpenModelicaInternal.simplify (since the bootstrapping tests can run
  simplify instead)

Other functionality has been moved between frontend and backend files in
order to make the interface cleaner.

The handling of loadResource has been updated. The locations of
resources is now stored in the runtime in order to make the handling
of URIs easier to implement for FMI.

### CODE REVIEW

**Comment by adrpo** [comment]
The LoadedFiles list was used by MDT as far as I remember but maybe i remember it badly

**Comment by sjoelund** [comment]
I guess it was working at some time, but the source code looked like it the result was always discarded. It can anyway be re-implemented easily with the changes.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-22_13-10-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5117/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-22_13-26-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5118/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-22_13-31-16](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5119/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-22_13-38-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5120/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-22_14-08-20](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5121/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-22_14-43-57](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5122/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-22_15-05-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5123/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_08-24-03](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5125/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_09-18-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5126/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_09-40-43](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5127/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_10-36-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5128/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_11-27-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5129/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_12-55-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5130/).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-23_13-59-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5132/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-23_14-19-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5133/).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-24_08-21-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5135/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-24_11-03-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5136/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-24_11-51-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5137/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-01-24_15-08-00](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5138/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-26_11-53-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5145/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-26_12-02-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5146/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-01-26_12-47-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5147/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-26_13-09-46](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5148/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-26_14-05-07](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5149/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-01-29_10-44-42](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5150/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-01-29_11-02-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5151/console).

**Pull request closed without merging**
