### PR TITLE
Fixed regression on BioChem library

### PR DESCRIPTION
**Pull request by lochel**
* BioChem library: BioChem.Examples.CellDivison.cell (564af844c47350e315cb663e2fa4119406117c83)

### CODE REVIEW

**Comment by adrpo** [comment]
Thanks @lochel! Maybe would be a good idea to add a test about it.

**Comment by lochel** [comment]
I am still not sure why/when PlanarMechanics.Examples.KinematicLoop_DynamicStateSelection started to fail.

**Comment by adrpo** [comment]
According to this was some change in 28 July as in 29 it started to fail:
https://test.openmodelica.org/libraries/trend-detailed.html
But maybe it could be a library change? Or some other changes on 28?

**Comment by lochel** [comment]
The test doesn't work for fd0d73bc4c2aba478d20807b0f3342384496a57c (24.07.). So maybe there were some library changes.

**Comment by lochel** [comment]
It doesn’t look like there were changes in that time frame. So maybe I am testing the wrong PlanarMechanics branch or something.

**Comment by adrpo** [comment]
If you configure with: --with-omlibrary=all it should install the library on make.

**Comment by lochel** [comment]
It's the same for the delivered library. I get tons of the following warnings during simulation and the simulation seem not to finish in a reasonable time frame:
```
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103828.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103828.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103829.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103829.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103830.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103830.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103829.
stdout            | warning | Solving linear system 956 fails at time 2.10383. For more information use -lv LOG_LS.
stdout            | warning | Error solving linear system of equations (no. 956) at time 2.103829.
```

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-08-04_09-01-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/491/console).

**Pull request merged**
