### PR TITLE
Do not use preprocessor for attributes

### PR DESCRIPTION
**Pull request by sjoelund**
Use the index stored in the SimVar directly instead of using the C
preprocessor to find the correct memory location for attributes.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-04_13-04-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2615/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-04_13-54-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2616/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-04_14-55-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2617/).

**Comment by hkiel** [comment]
@sjoelund Are you still working on this topic?
When you look at the SclableTestSuite there are a lot of large models where the main bottle neck seems to be the Compilation phase. So I would expect faster compilation if the generated C code is simplified.

**Comment by sjoelund** [comment]
I haven't had time to fix this properly, and yes I know it should help compilation time a lot. I know for the very large models, the `#include "X_model.h` takes something like 20 seconds for each file that is compiled which prevents us from splitting large files and compiling them in parallel.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-20_13-20-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2725/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-20_14-22-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2726/console).

**Comment by sjoelund** [comment]
Around 10 seconds faster for the entire suite :)

**Comment by hkiel** [comment]
Let's see how much impact this has on the ScalableTestSuite.
Is that one tested on Linux? I cannot reproduce the timings for compilation (it is much faster on my OSX, but maybe that is due to my SSD).

**Comment by casella** [comment]
The ScalableTestSuite is tested on Linux, but apparently the server is quite slow, compared to an average i5 or i7 laptop.
I will also try out the big network models and report to you

**Pull request closed without merging**
