### PR TITLE
Fix vararrayList

### PR DESCRIPTION
**Pull request by ptaeuber**
Decrease numberOfElements when deleting vars

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-26_21-37-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2833/).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-11-10_17-47-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3407/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-11-10_18-59-41](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3408/).

**Comment by vwaurich** [comment]
The problem is, that after SimCodeUtil.createStateSets() the A-variables of the statesets are added to the orderedVars. We should not change the BackendDAE.BackendDAE in createSimCode.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-21_12-35-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3433/console).

**Comment by ptaeuber** [comment]
@vwaurich Thanks!

**Pull request closed without merging**
