### PR TITLE
Implement and use List.listArrayReverse()

### PR DESCRIPTION
**Pull request by hkiel**
as a short cut for listArray(listReverse(lst))

### CODE REVIEW

**Comment by hkiel** [comment]
Is there a way to better pass the unused argument to arrayCreateNoInit()?
Or is it even possible to throw that UNUSED argument away?
My code fails when run on an empty list, but creating an array of length zero is otherwise just fine...

**Comment by sjoelund** [comment]
I think the following passes through the front-end:
```mo
if not listEmpty(lst) then
  defaultValue::_ := lst;
end if;
arr := arrayCreateNoInit(len, defaultValue);
```
But there is also the possibility to do a more safe:
```mo
if listEmpty(lst) then
  arr := listArray(lst); // Does not need listReverse
  return;
end if;
defaultValue::_ := lst;
arr := arrayCreateNoInit(len, defaultValue);
...
```

**Comment by hkiel** [comment]
I incorporated the second version, please let hudson run...

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-14_10-02-13](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1885/).

**Comment by hkiel** [comment]
the test needs to load List.mo
fixed in PR https://github.com/OpenModelica/OpenModelica-testsuite/pull/225

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-14_10-42-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1887/).

**Comment by hkiel** [comment]
forgot to push modification to BasePVector.mo
please run hudson again

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-14_12-18-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/1890/console).

**Pull request closed without merging**
