### PR TITLE
[SC] remove the replacement of the DIV operator by a call

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2018-04-18_02-24-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5592/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-18_02-29-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5593/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-18_14-32-28](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5596/).

**Comment by casella** [comment]
Does this attempt to fix [#4871](https://trac.openmodelica.org/OpenModelica/ticket/4871)?

**Comment by wibraun** [comment]
Not, really. It was about removing totally unnecessary operations, basically I've just remove 300 lines.

**Comment by hkiel** [comment]
What happened to those div-zero asserts? Are they really gone now or just the message removed?

**Comment by wibraun** [comment]
No, they are not really gone, and should be still visible with LOG_UTIL. But they occurred in an algebraic loops and  the solvers are able to handle them, so there is no need of throw an assert and restart the solver.  It's basically this [line](https://github.com/OpenModelica/OMCompiler/pull/2379/files#diff-420373e0dbd07a76c18d8f47e7935d6aR66), that do the job.

**Pull request closed without merging**
