### PR TITLE
Backend refactoring

### PR DESCRIPTION
**Pull request by gossen**
* Rename and change functions prototypes in BackendDAEUtil in a consistent manner,
 e.g. the function _setSharedAliasVars(BackendDAE.Shared,&nbsp;BackendDAE.Variables)_  will replace _aliasVars_ in BackendDAE.SHARED record.

* Replace BackendDAE.EQSYSTEM and BackendDAE.SHARED record constructors with BackendDAEUtil helper functions.

### CODE REVIEW

**Comment by sjoelund** [comment]
@wibraun @lochel - are the above commits fine for you?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-06-22_20-41-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/200/console)

**Comment by lochel** [comment]
I didn't review all the changes, but I wanted to do similar changes for a while. So I think we should just merge them.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-06-22_22-53-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/201/console)

**Pull request closed without merging**
