### PR TITLE
Follow FMI 2.0 schema (no empty output section)

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by sjoelund** [comment]
@adrpo @adeas31 - this one goes into maintenance so 1.11 FMUs are compliant to the FMI 2.0 spec.

**Comment by adeas31** [comment]
Push it in.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-19_14-42-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3722/console).

**Comment by adrpo** [comment]
I specifically remember that some tool, i guess the INTO-CPS COE didn't like this so I generated empty sections for these elements.

**Comment by sjoelund** [comment]
The official FMI tests for uploading FMUs reject those though. Better to follow the standard.⁣

**Comment by adrpo** [comment]
Ok. I'll check what changes I did we'll see.

**Pull request closed without merging**
