### PR TITLE
Please FMUChecker

### PR DESCRIPTION
**Pull request by rfranke**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-11-08_08-52-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3397/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by rfranke** [comment]
Another day, another surprise with Hudson. What does this mean?

aspell: Cpp
Makefile:48: recipe for target 'spellcheck' failed

**Comment by sjoelund** [comment]
Cpp is not in the dictionary. Add it if you want the job to pass: https://github.com/OpenModelica/OpenModelica/blob/master/.openmodelica.aspell

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-11-08_09-23-27](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3399/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by rfranke** [comment]
Many of my commit messages contain "Cpp" to better express what they are about. Can of course stop this habit. Changed the commit message from
```
  Check for FMUType with Cpp target
```
to
```
  Check for FMUType
```

**Comment by sjoelund** [comment]
It doesn't check the commit message; only the strings marked by gettext are part of the spell check.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-08_09-27-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3400/console).

**Pull request closed without merging**
