### PR TITLE
fix svg text height

### PR DESCRIPTION
**Pull request by hkiel**
- adjust text height to extent height if no text size is specified
- add option to create only a warning if a files already exists
- accept float for any decimal number
- some adaptions for Python 3

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
Pull request did not pass the checks on GitHub. Please sign the CLA.

**Comment by dietmarw** [comment]
Just tested it and it does not seem to fix the Complex icon.

**Comment by OpenModelica-Hudson** [comment]
Pull request did not pass the checks on GitHub. Please sign the CLA.

**Comment by hkiel** [comment]
@sjoelund @adrpo I signed the CLA quite some time ago and already committed with CLA. Now, hudson claims that I need to sign it... What do I need to do?

**Comment by OpenModelica-Hudson** [comment]
Pull request did not pass the checks on GitHub. Please sign the CLA.

**Comment by OpenModelica-Hudson** [comment]
Pull request did not pass the checks on GitHub. Please sign the CLA.

**Comment by adrpo** [comment]
What happens if you sign it again?

**Comment by adrpo** [comment]
What happens if you sign it again?
It might have been for another repo?

**Comment by atrosinenko** [comment]
It seems I had seen an option in my first PR - something like "re-check CLA" maybe under All Checks -> Details or something similar. Cannot find it again but probably because the check is already successful.

**Comment by adrpo** [comment]
Unfortunately I don't know how to fix this. @sjoelund has added this check. Maybe open a new PR with the same code?

**Pull request closed without merging**
