### PR TITLE
Look for homotopy in the whole system

### PR DESCRIPTION
**Pull request by ptaeuber**
... and not only in residual equations.

And removing obsolete and outdated code.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-12-20_13-35-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5051/console).

**Comment by casella** [comment]
Please see [#2266](https://trac.openmodelica.org/OpenModelica/ticket/2266#comment:20)

**Comment by casella** [comment]
@ptaeuber, it seems that this PR broke a large number of tests with the new front-end, see https://libraries.openmodelica.org/branches/history/newInst/2017-12-20%2013:38:01..2017-12-20%2015:07:20.html
Please check!

**Comment by casella** [comment]
Maybe it is just a mistake in the reporting. In the previous run after @perost 's commit, there were 501 regressions reported, and in the subsequent one by @perost there are 841 improvements.

**Comment by ptaeuber** [comment]
I don't think these changes are able to break so many models, especially not in the frontend. It must be a reporting error.
I left a comment on [#2266](https://trac.openmodelica.org/OpenModelica/ticket/2266#comment:21) about the current homotopy status.

**Pull request closed without merging**
