### PR TITLE
Improve Modelica 3.3 Synchronous features support

### PR DESCRIPTION
**Pull request by gossen**
* Improvements:
  * FrontEnd  
    * Clocked when equations;
    * Clock constructor is DAE.CLKCONST instead of function;
  * BackEnd  
    * Base-clock and sub-clock partitioning and inferencing, including clocked continuous partitions support;
    * _subPartitionIndex_ equation attribute removed &mdash; subclock partition maps on BackendDAE.EquationSystem and contains index of base clock;
    * Base clocks array is added in BackendDAE.Shared;
  * SimCode  
    * Add clocks and partition info;
  * Other  
    * New clocks-related errors;
* Should to do:
  * _interval_() operator support;
  * Partition errors output improvement;
  * Improve rational base clocks handling;
  * Code generation.

### CODE REVIEW

**Comment by sjoelund** [comment]
Note: If you make a pull request from master and push to master, the pull request is updated. It is better to make a topic branch and do the pull request from that branch instead.

**Comment by adrpo** [comment]
@bernhard-thiele could you please have a look at this pull request from @gossen and merge it if everything is fine?

**Comment by sjoelund** [comment]
https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/1/console
Used gcc-4.9 by accident; random2.mos is expected to fail. The rest should have succeeded, but did not. I also forgot to publish the test report, so I don't know exactly why they failed.

**Comment by gossen** [comment]
Most of the failures are caused by compiler backend changes, others failures are bugs. 
I'll reopen pull request after bugs fixing and tests modifying.

**Comment by sjoelund** [comment]
This fails to compile:
```
+ make -j40 bom-error utf8-error thumbsdb-error spellcheck
aspell: Inalid
aspell: subclocks
make: *** [spellcheck] Error 1
make: *** Waiting for unfinished jobs....
```
aspell has sub-clocks in the dictionary. Hudson will search all calls to gettext() for typos.

**Comment by gossen** [comment]
Typos are corrected.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2015-05-28_09-54-38](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/32/console)

**Comment by sjoelund** [comment]
@bernhard-thiele - are the changes OK? The test suite passes (the error is due to @vwaurich).

**Comment by bernhard-thiele** [comment]
Will have a look on it. Can rather comment on the front-end changes than on the back-end. Maybe @lochel wants to have look at the back-end, too.

**Comment by lochel** [comment]
Sure, I can have a look on the back end changes.

**Comment by bernhard-thiele** [comment]
Had a first look on it and regarding the front-end changes it should be fine.

Some documentation, e.g., what is a newly introduced function doing (e.g., `DAEUtil.verifyDAE`) wouldn't hurt. 

Some comments for changes in `Static.elabBuiltinClock(..)`
Patch simplifies the code by returning a DAE.CLKCONST(..) instead of a function call that needs to be elaborated later. However, there are a few issues (but they exist also in the current master branch code):

*1. How to handle code like that?*
```modelica
  constant Real sT[3] = {0.1, 0.2, 0.3};
  Clock c[3] = Clock(sT);
```
This calling style is currently not supported (it is not supported in Dymola either). However, it is not  explicitly forbidden in the specification, as far as I understand it.

*2. How to handle clocks that depend on parameters, e.g.,*
```modelica
  parameter Real sT = 0.1;
  Clock c = Clock(sT);
```
 In (some cases) it is possible to resimulate such models in Dymola without recompilation. 

However, I don't think that we need to support 1. or 2. now (maybe later).

**Comment by gossen** [comment]
Example 2 doesn't work now. It is clearly a bug.

**Comment by lochel** [comment]
I haven't anything to complain about yet. Unfortunately, I haven't found time to read it that carefully. Anyway, I think if this pull request passes the test suite, we should merge it.

**Comment by adrpo** [comment]
Ok, so it seems that we should merge this in from what i got from @lochel and @bernhard-thiele.
@sjoelund can you do that?

**Comment by sjoelund** [comment]
Sure. @gossen, note that your work has not been performed in a feature branch so you might not be have to git rebase origin/master after the commit is pushed since hudson rebases commits.

**Comment by adrpo** [comment]
@sjoelund, maybe you can explain a bit to @gossen a bit better what is expected from him so we can merge and close this issue.

**Comment by sjoelund** [comment]
The problem is this is the master branch of @gossen. And as such between the time it was reviewed and the time it was accepted, there have been additional commits.
I will merge in https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/32/parameters/ and the rest of the commits in here won't get in there and need to be manually merged.

**Comment by sjoelund** [comment]
I would also suggest @gossen to use the pre-commit hooks and setup the text editor to strip trailing whitespace, because that is the cause of the merge conflicts.

**Comment by gossen** [comment]
So should I reset my last commits?

**Comment by sjoelund** [comment]
No, I will reset and cleanup some of the problematic changes in the commits

**Comment by sjoelund** [comment]
a9954e8 is the problematic commit. It's not a merge commit, but a normal commit. And it touched some files it shouldn't have.
I really would suggest always using ```git pull --rebase``` or ```git rebase``` instead of ```git merge``` to work on branches.

**Comment by sjoelund** [comment]
Closed by #32. I included all of the above commits (minus the changes to SimulationRuntime, etc). They were all squashed into one single commit because they had trouble merging, rebasing, and cleaning up.

**Pull request closed without merging**
