### PR TITLE
Add failtrace flag to SimCodeUtil.createSimCode function

### PR DESCRIPTION
**Pull request by gossen**
The error message contains source info for function createSimCode and appears in some tests,
so changes in SimCodeUtil.mo may cause changes in tests output.
This patch add failtrace flag to createSimCode error message to hide it.

### CODE REVIEW

**Comment by sjoelund** [comment]
The sourceInfo() should not really be removed. Instead, the error should simple never appear or use the source information from the equation.

**Comment by gossen** [comment]
This error message can be hidden using failtrace flag.

**Comment by lochel** [comment]
I think the SimCode warning shouldn't be displayed if the initialization failed, since there should be always a proper error message from the initialization module.
But once I moved the initialization to the middle of the back end transformation, this will be obsolete anyway.

**Comment by lochel** [comment]
To make this clear: I don’t think it is a good idea to put this error message on a flag. SimCode should never fail, and therefore the error message can be just there. The only odd thing here is, that the initialization is performed in SimCode.
It would be fine to hide this warning if initialization fails, but otherwise it should be just there.

**Comment by gossen** [comment]
I don't think it can be done easily.

**Comment by lochel** [comment]
Probably, xou could do something like lochel/OMCompiler@470defb50.

**Comment by lochel** [comment]
It passed already the test suite together with lochel/OpenModelica-testsuite@6265190d.

**Pull request closed without merging**
