### PR TITLE
Add some example auto-completion information on Annotations for use by OMEdit (task#5333)

### PR DESCRIPTION
**Pull request by atrosinenko**
See also:
* PR in OMEdit: OpenModelica/OMEdit#219
* obsolete PR in ModelicaStandardLibrary: modelica/ModelicaStandardLibrary#2837

### CODE REVIEW

**Comment by atrosinenko** [comment]
Ping

**Comment by atrosinenko** [comment]
This is supposed to be not a work-in-progress, but finished extension point where OMCompiler developers who know more about actual annotations may trivially add content.

**Comment by casella** [comment]
@atrosinenko, the title of the PR was a bit misleading, because it lacked the information that it was all about annotations. I'd gladly work on this, but I won't have time for a while. 

I guess all the relevant information can be found here: https://webref.modelica.university/, in the bottom right corner (I'm not sure why @mtiller called it "Statements", I guess it should have been "annotations"). Maybe you want to give it a try?

**Comment by atrosinenko** [comment]
> I guess all the relevant information can be found here: https://webref.modelica.university/

Great cheat sheet, thanks! 

Right now, I fear copy-paste is inappropriate for legal reason and my rewordings may be wrong/misleading. On the other hand, this PR is not supposed to be complete for now -- it have not to be complete, it just have to be correct, placed to the right part of the right library, etc. It is merely a placeholder for demonstration of OpenModelica/OMEdit#219.

So, I expect review of this PR to be review of the future layout of the content. And just a small bit of actual information.

**Comment by atrosinenko** [comment]
Even more, in the future, other completion info (such as keywords) could probably be moved there. But, of course, this PR is about annotations.

**Comment by adeas31** [comment]
I tested a bit https://github.com/OpenModelica/OMEdit/pull/219. Seems to work fine. We can either merge this PR for now or can use this one to fill in all the annotations. @casella you think you can manage that?

**Comment by casella** [comment]
Not before April 8th, I'm totally swamped

**Comment by adeas31** [comment]
Don't bother then....I will add it myself.

**Comment by adeas31** [comment]
I added annotations based on the latest Modelica specification. There are few `TODO` in the code, I am not sure how to handle such cases.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2019-04-02_15-14-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6599/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-04-02_16-48-52](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6603/console).

**Pull request closed without merging**
