### PR TITLE
Backend memory

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-03-24_15-17-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2047/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-03-24_15-21-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2048/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-28_15-03-02](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2094/console).

**Comment by sjoelund** [comment]
Seems to run faster in the general case. This was true also for very large models.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-03-28_15-55-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2098/console).

**Pull request closed without merging**
