### PR TITLE
Add quotes around the full command

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adrpo** [comment]
Sounds good to me!

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-07-04_20-06-19](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5867/console).

**Comment by sjoelund** [comment]
Shouldn't quotes inside the command also be quoted then?

**Comment by adrpo** [comment]
@sjoelund no, in windows is weird and it just works like that

**Pull request closed without merging**
