### PR TITLE
fix some issues from static code analysis

### PR DESCRIPTION
**Pull request by hkiel**
ticket:3954

### CODE REVIEW

**Comment by hkiel** [comment]
@sjoelund Can you please start hudson?

**Comment by adrpo** [comment]
I had to kill the PR because the generated simulation code consumed 46G per process:
https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/2926/console

**Comment by hkiel** [comment]
Gracias! I will check.
Hum,... Patch seems to have larger impact than I thought.

**Comment by hkiel** [comment]
@adrpo Found a typo and tested that some of the failed tests work again.
Can you please start hudson again?

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-17_16-13-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2928/console).

**Pull request closed without merging**
