### PR TITLE
Split synchronous features into pre and post phase

### PR DESCRIPTION
**Pull request by lochel**
This should allow to handle higher-index problems within clocked partitions.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-19_12-02-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3719/).

**Comment by lochel** [comment]
@rfranke This is related to [ticket:4168](https://trac.openmodelica.org/OpenModelica/ticket/4168).

**Comment by rfranke** [comment]
Great if `Modelica_Synchronous.Examples.Systems.ControlledMixingUnit` works now. There still seems to be  an issue with initialization?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-25_19-34-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3789/).

**Comment by lochel** [comment]
Most of the state machines work if `removeSimpleEquations` is deactivated. Maybe it is reasonable to skip clocked partitions for module `removeSimpleEquations` within the pre-optimization phase, because `removeSimpleEquations` is also called within the post-optimization and then it should be no problem to handle the clocked partitions. @bernhard-thiele What do you think?

**Comment by lochel** [comment]
@rfranke I've now compared the results between the c and cpp runtime for that model. Obviously, there is still something wrong with initialization in the c runtime. However, at time=1 both trajectories drop and go up at the next sample point. Unfortunately, I have no other results for comparison. Is this still wrong or expected?

image

**Comment by rfranke** [comment]
That's due to d32ecbb30f3cd8de9baad8576b1f9a1df0425ec3 that re-implements ExplicitEuler. Was just about to inform you ...

**Comment by lochel** [comment]
My problem is just that I haven't seen the trajectories before your changes and thus I am not sure if it changed the results. Does that mean that the results are acceptable for now?

**Comment by rfranke** [comment]
The above trajectories are in fact from before the new ExplicitEuler. The second interval drops to below 300 in the first plot (cpp) and stays at about 303 in the second plot. After the change both runtimes stay at about 303.

Hudson reports an unstable testsuite though. The failing DID example is lacking the initialization of the Boolean state `first`. It starts with false so that y1 starts at 0 instead of y1_start=1 !?
```
model DID "Double Integrator Discrete-time"
  parameter Real p = 1 "gain for input";
  parameter Real y1_start = 1 "start value for first state";
  parameter Real y2_start = 0 "start value for second state";
  parameter Real dt = 0.1 "sample time";
  input Real u(start = -2);
  output Real y1, y2;
  Boolean first(start=true) "Used to identify the first clock tick";
equation
  when Clock(dt) then
    first = false;
    y1 = if previous(first) then y1_start else previous(y1) + p * u * dt;
    y2 = if previous(first) then y2_start else previous(y2) + previous(y1)*dt + 0.5 * u * dt*dt;
  end when;
end DID;
```

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-26_11-23-09](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3798/).

**Comment by lochel** [comment]
I think initialization is now working. At least the DID example works again. However, there are still some failing models.

**Comment by rfranke** [comment]
Well, `simulation_modelica_synchronous.SynchronousFeatures.ControlledMassBasic.mos` might be expected output, just with one variable more after your last commit.

`simulation_modelica_statemachines.MLS33_17_3_7NA.mos` and `simulation_modelica_statemachines.DeadEnd.mos` would pass the tests with the Cpp runtime. The C runtime reports an index error and terminates:
   "assert | error | Dimension 1 has bounds 1..1, got array subscript 2".

@bthiele might know more about these state machine examples.

**Comment by rfranke** [comment]
Alternatively to your commit WIP, one might also think of less drastic means to tell RemoveSimpleEquations to not remove variables that appear in previous().

**Comment by lochel** [comment]
> Alternatively to your commit WIP, one might also think of less drastic means to tell RemoveSimpleEquations to not remove variables that appear in previous().

Absolutely. However, there is still the post-optimization call of removeSimpleEquations. So I am not sure if it is really worth it.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-27_09-47-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3807/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_11-09-14](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3834/console).

**Pull request closed without merging**
