### PR TITLE
NFInst improvements.

### PR DESCRIPTION
**Pull request by perost**
- Merge the class and instance tree by merging ComponentNode into
  InstNode.
- Renamed NFInstance to NFClass.
- Removed Component.EXTENDS_NODE, use class InstNode instead.
- Improved lookupCref to be able to start with a class scope, to get rid
  of fake components.
- Got rid of Lookup.LookupResult, not needed with new InstNode.
- Got rid of Component.Scope, use InstNode as binding scope instead.
- Cleaned up lots of obsolete code.

### CODE REVIEW

**Comment by adrpo** [comment]
Very good! I wanted to propose this merging but it seems you already made it :)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-12-09_16-39-58](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3531/).

**Comment by perost** [comment]
@adrpo Btw, I didn't change your function handling code regarding fake component use. You haven't added any testcases for functions, so I figured you'd better change it yourself.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-12-09_17-10-05](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3532/console).

**Comment by adrpo** [comment]
Yep, i'll fix that and add some tests. I want to fix the records also first.

**Comment by casella** [comment]
Besides cleaner and leaner source code (which is very good), can you comment briefly about the impact of this change in the speed of instantiation, particularly for such critical cases as Modelica.Fluid connectors?

**Comment by perost** [comment]
@casella The performance impact is likely minimal, this just gets rid of some bad design choices that would've come back to bite us later.

**Pull request closed without merging**
