### PR TITLE
final algorithms of Nox Solver

### PR DESCRIPTION
**Pull request by qichenghua**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-07-18_04-47-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4408/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-07-18_05-07-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4409/console).

**Comment by lochel** [comment]
@qichenghua Please clean up your commits before pushing them to `OpenModelica:master`.

**Comment by qichenghua** [comment]
@lochel Ok, I'm sorry, I will do so in future. I'm afraid I cannot clean up the commits that have been pushed to master already without changing the history.

**Pull request closed without merging**
