### PR TITLE
Ticket 2763

### PR DESCRIPTION
**Pull request by lochel**
Try to fix ticket [2763] (https://trac.openmodelica.org/OpenModelica/ticket/2763).

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo I am not sure what function input_function_init was used for. I changed it to initialize the inputs with its start values. Is that fine or are my changes bad?

**Comment by lochel** [comment]
With this changes simulation/modelica/msl22/InputOutput.mos produces the same results for both targets, C and Cpp.

**Comment by adrpo** [comment]
@lochel, i don't know either, seems your assumption is right.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-09-15_08-36-01](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/781/console).

**Pull request merged**
