### PR TITLE
integrate implicit runge-kutta and lobatto

### PR DESCRIPTION
**Pull request by wibraun**
- add imprungekutta integration method
 - add simflag impRKOrder to select different order[1-6]

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_14-18-41](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3839/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-01-31_14-47-25](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3840/console).

**Comment by casella** [comment]
@wibraun are these algorithms fixed time step or variable time step with error control?

**Comment by wibraun** [comment]
@casella This are fixed time step, but I'm on the way to push one with step size control.

**Comment by casella** [comment]
Good! See [#4247](https://trac.openmodelica.org/OpenModelica/ticket/4247)

**Pull request closed without merging**
