### PR TITLE
Do lookup of varInfo directly

### PR DESCRIPTION
**Pull request by sjoelund**
This reduces the size of the model.h file for simulations, making
the pre-processor do less work.

### CODE REVIEW

**Comment by sjoelund** [comment]
I expect this to fail, but I don't know where :)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-27_14-34-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2554/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-27_14-52-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2555/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-27_16-13-39](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2557/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-05-04_11-14-48](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2613/console).

**Pull request merged**
