### PR TITLE
Change order in mergeZeroCrossings

### PR DESCRIPTION
**Pull request by sjoelund**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-07-05_08-41-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2997/console).

**Comment by lochel** [comment]
@sjoelund Does this fix the bad scaling issue?

**Comment by sjoelund** [comment]
It does not, but it makes it easier to see which part was not working properly. I am working on fixing the other parts to use DoubleEndedList.

**Comment by lochel** [comment]
Thanks for that!

**Pull request closed without merging**
