### PR TITLE
[FMI] Set nominal to 1.0 as a default

### PR DESCRIPTION
**Pull request by sjoelund**
This improves scaling of non-linear solvers. Also fixed some default
settings in FMUs, such as setting a default linear solver for non-linear
systems.

### CODE REVIEW

**Comment by sjoelund** [comment]
@adrpo @adeas31 @casella This should be considered for 1.12 (at least just the part setting default nominal attribute to 1.0)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-10-13_15-26-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4733/).

**Comment by casella** [comment]
Agreed

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-10-14_08-18-45](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4739/console).

**Pull request closed without merging**
