### PR TITLE
Fix broken PlanarMechanics examples

### PR DESCRIPTION
**Pull request by lochel**
The following models are broken due to code generation changes (9913bac06b22c2d3aa87497a8023f3fe84dcd129):
* PlanarMechanics.Examples.KinematicLoop_DynamicStateSelection
* PlanarMechanics.GearComponents.Examples.SpurGear

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2015-10-09_12-58-38](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/909/console).

**Comment by lochel** [comment]
PlanarMechanics.Examples.KinematicLoop_DynamicStateSelection doesn’t work yet.

**Comment by adrpo** [comment]
Ouch. Eh, nevermind, the fix is good. You can make a new one for that model if you find out the issues.

**Comment by lochel** [comment]
No problem. I have still no idea what is wrong in that case.

**Pull request merged**
