### PR TITLE
get absolute paths of resource files which are used for animation

### PR DESCRIPTION
**Pull request by vwaurich**
some debug printing for GlobalScript.SymbolTable
fixes crashing of fullrobot when animated and yes, animation is still wrong (dxf files are not yet implemented properly)

### CODE REVIEW

**Comment by sjoelund** [comment]
I don't quite get why `System.getFullPathFromUri` is not used

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-19_09-03-50](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3239/console).

**Comment by vwaurich** [comment]
There is no such function in System.mo

**Comment by sjoelund** [comment]
Sorry, `CevalScript.getFullPathFromUri` :)

**Comment by vwaurich** [comment]
Thats what I was asking for. I'll give it a try.

**Comment by vwaurich** [comment]
I suppose it is preferable to forward Absyn.Program to SimCodeutil.createSimCode instead this list<tuple<String,String>> package-path info type?

**Comment by vwaurich** [comment]
list(tuple(String,String)) is the type

**Comment by sjoelund** [comment]
I suppose so

**Pull request merged**
