### PR TITLE
Add support for some synchronous elements

### PR DESCRIPTION
**Pull request by bernhard-thiele**
@perost Is this about the style which should be used for adding functions to the new front-end? Improvement suggestions?

### CODE REVIEW

**Comment by rfranke** [comment]
What is the rationale for "some" in the titile of the pull request?
Why not support all (about twice as many oparators than implemented so far)?

**Comment by bernhard-thiele** [comment]
Because I want to understand what is good or bad style and what I can improve. Of course, the goal is to support everything finally.

**Comment by adrpo** [comment]
@bernhard-thiele: for now this is OK. We might change it a bit later but  it should not need too much adaptation.

**Comment by bernhard-thiele** [comment]
@adrpo OK, I will close this pull request and open a new one since I now have a few more operators which can be merged

**Pull request closed without merging**
