### PR TITLE
[DAEmode] Introduce evaluation stages on equation level

### PR DESCRIPTION
**Pull request by wibraun**
For the simulation it is needed to evaluate the related
equations at four different stages:
  - *dynamic* - Evaluate all dependent equations to obtain the
    residuals for the integration.
  - *algebraic* - Evaluate equations needed at the output points.
  - *zerocross* - Evaluate equations, which are needed to obtain the
    zeroCrossings expressions.
  - *discrete* - Evaluate the equations depending on the discrete equations.

Enabled for now only in DAE mode, but it's also applicable in ODE mode.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-10_13-30-10](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5543/).

**Comment by casella** [comment]
Please see [#4877](https://trac.openmodelica.org/OpenModelica/ticket/4877)

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-04-10_16-00-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5547/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-04-10_16-56-37](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5548/console).

**Pull request closed without merging**
