### PR TITLE
Make Compiler/runtime shared to avoid C++ issues

### PR DESCRIPTION
**Pull request by sjoelund**
This hopefully fixes OSX where there are multiple competing full C++
ABI's.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-15_15-06-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2431/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-15_15-13-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2432/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-15_15-16-22](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2433/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-15_15-25-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2434/console).

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-15_15-32-06](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2435/console).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-15_16-42-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2436/console).

**Comment by hkiel** [comment]
It got worse on OS X:

```
clang++ -shared -Wl,-rpath,'@loader_path/../lib/x86_64-darwin15.3.0/omc/' -install_name @rpath/libomcruntime-boot.dylib -o libomcruntime-boot.dylib Dynload_omc.boot.o Error_omc.boot.o FMI_omc.boot.o GraphStreamExt_omc.boot.o HpcOmSchedulerExt_omc.boot.o HpcOmBenchmarkExt_omc.boot.o ptolemyio_omc.boot.o SimulationResults_omc.boot.o System_omc.boot.o TaskGraphResults_omc.boot.o Print_omc.o  Settings_omc.o serializer.o IOStreamExt_omc.o ErrorMessage.o systemimplmisc.o UnitParserExt_omc.o unitparser.o BackendDAEEXT_omc.o Socket_omc.o matching.o matching_cheap.o Lapack_omc.o getMemorySize.o  omc_communication.o omc_communication_impl.o Corba_omc.o -L "/Users/henning/src/OpenModelica/build/lib/x86_64-darwin15.3.0/omc/"  -lOpenModelicaRuntimeC
Undefined symbols for architecture x86_64:
  "_METIS_PartGraphKway", referenced from:
      HpcOmSchedulerExtImpl__scheduleMetis(int*, int*, int*, int*, int, int, int) in HpcOmSchedulerExt_omc.boot.o
  "_XML_Parse", referenced from:
      XmlBenchReader::ReadBenchFileEquations(std::string) in HpcOmBenchmarkExt_omc.boot.o
      GraphMLParser::ParseGraph(Graph*, char const*, NodeComparator, std::string*) in TaskGraphResults_omc.boot.o
  "_XML_ParserCreate", referenced from:
      XmlBenchReader::ReadBenchFileEquations(std::string) in HpcOmBenchmarkExt_omc.boot.o
      GraphMLParser::ParseGraph(Graph*, char const*, NodeComparator, std::string*) in TaskGraphResults_omc.boot.o
  "_XML_ParserFree", referenced from:
      XmlBenchReader::ReadBenchFileEquations(std::string) in HpcOmBenchmarkExt_omc.boot.o
      GraphMLParser::ParseGraph(Graph*, char const*, NodeComparator, std::string*) in TaskGraphResults_omc.boot.o
  "_XML_SetCharacterDataHandler", referenced from:
      GraphMLParser::ParseGraph(Graph*, char const*, NodeComparator, std::string*) in TaskGraphResults_omc.boot.o
... (thousands of errors) ...
  "_solve", referenced from:
      _SystemImpl__lpsolve55 in System_omc.boot.o
      UnitParser::solveMIP(Unit, bool) in unitparser.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile.common:65: recipe for target 'libomcruntime-boot.dylib' failed

```

**Comment by sjoelund** [comment]
I have local fixes. It did not get worse :)

**Pull request closed without merging**
