### PR TITLE
clean up non-linear system code a bit

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-27_20-09-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2841/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-27_21-33-23](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2842/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-27_21-58-35](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2843/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-05-30_12-57-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2851/).

**Comment by wibraun** [comment]
Merge in PR954.

**Pull request closed without merging**
