### PR TITLE
fix event handling of ida solver

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-06-27_23-30-41](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2971/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-06-28_00-23-44](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2972/console).

**Comment by hkiel** [comment]
Does this fix ScalableTestSuite?
The run on 2016-06-08 had more cases that simulate fine, now I see the following errors from IDA:
```
stdout            | info    | ##IDA## -6 error occurred at time = 0.0012891140271981
stdout            | info    | ##IDA## -3 error occurred at time = 0
```

**Comment by wibraun** [comment]
hm, the run from 2016-06-27 does not includes this commit. I'll start it later today.

**Comment by wibraun** [comment]
@hkiel Now, this is fixed. The issue was ticket:3983.

**Pull request closed without merging**
