### PR TITLE
[BE] Fix mixed-determined dump and raise index to 10

### PR DESCRIPTION
**Pull request by kabdelhak**
fixes [#5316](https://trac.openmodelica.org/OpenModelica/ticket/5316) and [#5303](https://trac.openmodelica.org/OpenModelica/ticket/5303#comment:1)

### CODE REVIEW

**Comment by casella** [comment]
@adrpo, can you please accept this PR into master?

**Comment by hkiel** [comment]
@casella I just started hudson job.

**Comment by OpenModelica-Hudson** [comment]
The job failed the coding style; for details, see [OpenModelica_TEST_PULL_REQUEST 2019-02-07_10-27-24](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6424/console). Remember to clean up the commit you did that breaks the coding style rather than piling a new commit on top of the old ones. This goes double for accidental addition of files that you need to remove.

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2019-02-08_10-26-51](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/6430/console).

**Pull request closed without merging**
