### PR TITLE
Fix the front-end part of ticket:4304

### PR DESCRIPTION
**Pull request by adrpo**
- add new DAE.INITIAL_ASSERT and handle it in the front-end
- back-end handling still needs to be implemented

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-11_17-25-17](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4008/).

**Comment by lochel** [comment]
Backend will be fixed with #1537.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2017-03-11_18-29-56](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4009/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-03-11_18-41-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4010/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-03-11_19-49-59](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4011/console).

**Pull request closed without merging**
