### PR TITLE
new subclock partitioning implementation with new partition adjacency…

### PR DESCRIPTION
**Pull request by vwaurich**
use an adjacency matrix of sub partitions for inference instead of a BLT-sorting of subclock-variables

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2017-06-14_13-56-55](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4319/console).

**Comment by lochel** [comment]
Does this fix `Modelica_Synchronous.WorkInProgress.Tests.TestExactClockWithIntegrator`?

**Comment by vwaurich** [comment]
No, it doesn't. I haven't considered this test as its not tested anywhere.
The model does fail because of an incorrect separated clocked partition. I will check that. Thanks for the hint.

**Comment by vwaurich** [comment]
OK, I have fix for it but I would like to wait to see the coverage effects tomorrow. If that is fine, I'll push it.

**Pull request closed without merging**
