### PR TITLE
Split up knownVars

### PR DESCRIPTION
**Pull request by lochel**
`knownVars` should only contain those variables, that are constant for the entire simulation.
The newly introduced `globalVars` can be used for variables that are somehow known but not constant for the entire simulation.

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-04_11-39-30](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2219/).

**Comment by lochel** [comment]
It's just the optimization that has issues. @vruge Can you fix that?

**Comment by vruge** [comment]
no

**Comment by vruge** [comment]
I guess it is line 738 in DynamicOptimization
BackendDAE.SHARED(functionTree = funcs, knownVars = knownVars) := shared;
missing globalVars??

**Comment by vruge** [comment]
additional  RemoveSimpleEquations.removeSimpleEquationsShared need globalVars

**Comment by vruge** [comment]
and SymbolicJacobian.generateSymbolicJacobian

**Comment by lochel** [comment]
@vruge It would be good if you could at least fix the optimization, since I don’t get your code right.

**Comment by vruge** [comment]
why do you need an additional explanation with "It would be good if"?
Do you think the  "no" was gratuitous?

**Comment by lochel** [comment]
Unfortunately, that will lead to nothing.

**Pull request closed without merging**
