### PR TITLE
state attribute isValueChangeable

### PR DESCRIPTION
**Pull request by lochel**
see [ticket:4116](https://trac.openmodelica.org/OpenModelica/ticket/4116)

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-10-31_17-44-11](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3348/console).

**Comment by lochel** [comment]
The attribute `isValueChangeable` is not available in the backend. So what we can do is to restrict the changeability for states to constant start attributes (see 72ca9a6e57c0065c2d2b0d414edbcb2fb15a3934). @rfranke Is this good enough for now?

If we want to restrict this to iteration variables, we need to add this attribute to the `BackendDAE.VAR` type.

**Comment by rfranke** [comment]
See https://trac.openmodelica.org/OpenModelica/ticket/4116#comment:4

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-11-04_10-55-46](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/3375/console).

**Pull request closed without merging**
