### PR TITLE
attempt to fix Codegen issue of inverse algorithms

### PR DESCRIPTION
**Pull request by wibraun**
see ticket:4568

 - expand all crefs
 - use only solved vars as residuals variables

### CODE REVIEW

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-10-18_18-26-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4788/).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2017-10-19_18-24-46](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/4795/).

**Comment by lochel** [comment]
@wibraun What is the status of this pull request? Can you list the remaining issues, or is it obsolete and should be closed?

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-02-28_10-01-47](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5362/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-02-28_16-59-04](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5363/console).

**Pull request closed without merging**
