### PR TITLE
update wrapFunctionCalls module

### PR DESCRIPTION
**Pull request by jhag**
the module skips the equations (CREF=CALL and CALL=CREF) and the CREF is the new cse-variable.
furthermore, all skip cases of the FunctionCalls (i.e. noEvent()...) are listed in one function.
the module is still disabled.

### CODE REVIEW

**Comment by lochel** [comment]
I take care of this one. Some cleanup is necessary before I will merge this.

**Comment by OpenModelica-Hudson** [comment]
The job failed to compile; for details, see [OpenModelica_TEST_PULL_REQUEST 2016-04-04_09-59-12](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2216/console).

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2016-04-04_10-07-32](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2217/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2016-04-04_11-02-08](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/2218/console).

**Pull request merged**
