### PR TITLE
Fix InstUtil.splitInnerAndOtherTplLstElementMod.

### PR DESCRIPTION
**Pull request by perost**
- Rewrote splitInnerAndOtherTplLstElementMod to use a for-loop
  instead of non-tail recursion.

### CODE REVIEW

**Comment by adeas31** [comment]
Does that fix this [issue](https://openmodelica.org/forum/default-topic/2522-openmodelica-omedit-crushed-when-open-fcsys-package)?

**Comment by perost** [comment]
>Does that fix this issue?

No, see my comment in that thread.

**Comment by OpenModelica-Hudson** [comment]
The test suite is unstable according to [OpenModelica_TEST_PULL_REQUEST 2018-08-13_12-02-36](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5940/).

**Comment by OpenModelica-Hudson** [comment]
The tests run correctly according to [OpenModelica_TEST_PULL_REQUEST 2018-08-13_12-17-40](https://test.openmodelica.org/hudson//job/OpenModelica_TEST_PULL_REQUEST/5941/console).

**Pull request closed without merging**
